### PR TITLE
CLDR-14066 update charts

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14066
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by macchiati** [comment]
This fixes some chart problems, and I also added a patch for the problem with ia.xml (which unblocks other tickets)

**Comment by macchiati** [comment]
Ready for review. Mostly charts work, but a couple of patches to get tests to pass.

**Comment by macchiati** [comment]
BTW, Krisiti, I was able to get all the tsvs to show up as tables except when they were too big, or in one case that I can fix:

https://github.com/unicode-org/cldr-staging/blob/master/docs/charts/38/tsv/locale-missing.tsv

**Comment by srl295** [comment]
@macchiati LGTM but needs squash

**Comment by srl295** [comment]
> i approve but needs to be squashed

i should say "probably" — did you intend for 8 commits? Since there are a lot of things going here

**Comment by srl295** [comment]
FWIW master started failing with 229e26539e8bddba715314cad08defa827607de5 (final testing)

**Pull request merged**
