### PR TITLE
CLDR-13809 add sgn-* to languageAlias

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13809
- [X] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by pedberg-icu** [comment]
I want to wait until we have the discussion in the CLDR TC about accepting this ticket before doing the review. That will not likely happen until next week.

**Comment by macchiati** [comment]
We do not want to do these; our policy is not to add the category "redundant" because they are redundant.

**Comment by FrankYFTang** [comment]
Reopen per  https://unicode-org.atlassian.net/browse/CLDR-13809

**Comment by macchiati** [comment]
Just approved; thanks for pushing through on this, Frank!

Mark

**Pull request merged**
