### PR TITLE
CLDR-16210 Revert some changes involving NNBS U+202F

### PR DESCRIPTION
**Pull request by btangmu**
-Revert changes in eight xml files in common/main

-Revert changes in DAIP  and unit test

-Comments

CLDR-16210

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
This effectively reverts all the changes (except comments) to DisplayAndInputProcessor.java that were made in https://github.com/unicode-org/cldr/pull/2391

It also effectively reverts all the 46 spacing changes (from U+202F to either U+0020 or U+00A0) that would have been made if CLDRModify -fp had been run after https://github.com/unicode-org/cldr/pull/2391

Those same 46 changes would have been made if CLDRModify -fp had been run just before https://github.com/unicode-org/cldr/pull/2433

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
Ah, clicked too soon!

**Comment by btangmu** [comment]
also skip the 4 failing unit test items for now

**Review by macchiati — APPROVED** [review]

**Comment by btangmu** [comment]
there were 2 things done in https://github.com/unicode-org/cldr/pull/2391

* Coalesce multiple interior spaces
* Recognize U+202F as one kind of space in various patterns, including path-specific normalization related to wantsRegularSpace, wantsNBSP, wantsNNBSP

the second one turns out to have been problematic; as we discussed in email and slack, the strategy here is first to "Revert the changes in DAIP that changed spaces" without distinguishing the above two things; subsequently we can restore the beneficial changes...

**Comment by macchiati** [comment]
What we need to do in #2 is distinguish the paths that need/allow an NNBSP
/ NSP (U+202F / U+2009) from those that didn't, so we don't mash some
characters. (And then of course there is the ideographic space)

I think we need some categories of paths, so that we can answer the
following questions for each set:

   1. What set of the 5 spaces is allowed?
   2. Which of the allowed ones is preferred (this might also vary by
   locale)? Might be an ordering like : Nonbreaking > breaking then full >
   narrow
   3. What do we do if we hit a disallowed space?
   4. What do we do if we have a sequence of multiple spaces?

Note: the answer for #4 I think we can derive from the first two, something
like the following (for [SPACE, NBSP, NNBSP, SPACE]

   1. If a specific space occurs later in the sequence, we remove it. Thus
   we only have unique cases, such as [SPACE, NBSP, NNBSP]
   2. If there are only disallowed ones, we do #3.
   3. If there is at least one allowed space, we remove all disallowed
   ones. Eg [NBSP, NNBSP]
   4. The only case left is multiple allowed ones. If there is a preferred
   one, pick it; otherwise take the first in codepoint order

**Comment by macchiati** [comment]
Thanks Tom!

**Pull request merged**
