### PR TITLE
CLDR-15275 ST forum stuck on loading if user lacks permission

### PR DESCRIPTION
**Pull request by btangmu**
-Replace non-existent params.special.showError with simple inline error message

-Two new subroutines loadBad and loadOk

CLDR-15275

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
I've just tried "re-run all jobs"

**Comment by btangmu** [comment]
@srl295 any idea what the error means?

**Comment by btangmu** [comment]
Here's something: https://github.com/ansible-community/ansible-lint/issues/1795

**Comment by srl295** [comment]
> Here's something: [ansible-community/ansible-lint#1795](https://github.com/ansible-community/ansible-lint/issues/1795)

yes i just found that.  

I'll work on a patch to incorporate that ver until the action catches up

**Comment by srl295** [comment]
> > Here's something: [ansible-community/ansible-lint#1795](https://github.com/ansible-community/ansible-lint/issues/1795)
> 
> yes i just found that.
> 
> I'll work on a patch to incorporate that ver until the action catches up

patch: https://github.com/unicode-org/cldr/pull/1682

**Comment by btangmu** [comment]
Here goes "re-run all jobs" again...

**Comment by srl295** [comment]
> Here goes "re-run all jobs" again...

you can try but you you may need to rebase it on main if you wanted my other changes

**Comment by btangmu** [comment]
See https://github.com/unicode-org/cldr/pull/1684

**Comment by srl295** [comment]
@btangmu you don't need a new PR… just rebase

**Comment by btangmu** [comment]
@srl "just rebase" -- there was also a problem with my commit message and I wanted a clean start :-)

**Pull request closed without merging**
