### PR TITLE
CLDR-13636 Make ExampleGenerator faster, clear cache less

### PR DESCRIPTION
**Pull request by btangmu**
-Revise TestExampleGeneratorDependencies and related code

-Look through all locales, skip if json file already exists

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13636
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
I'm unable to merge -- "Merging is blocked" and "You’re not authorized to merge this pull request" even though "All checks have passed" including signed CLA, and I'm logged into github. This seems to be a problem that comes and goes.

**Comment by macchiati** [comment]
Do you see the following, or does it happen after you hit the Squash &
Merge?

[image: Screenshot 2020-03-16 at 10.59.33.png]
Mark

**Comment by btangmu** [comment]
> Do you see the following, or does it happen after you hit the Squash & Merge? [image: Screenshot 2020-03-16 at 10.59.33.png] Mark

Looks like you meant to paste an image here, but it only shows up as "[image: Screenshot 2020-03-16 at 10.59.33.png]".

There's no "Squash & Merge" button shown for me.

**Comment by macchiati** [comment]
It shows for me, so let me know the ones you want to Squash & Merge until
we get this figured out.

Mark

**Comment by btangmu** [comment]
> It shows for me, so let me know the ones you want to Squash & Merge until we get this figured out. Mark

Once any of my PRs has been approved, it's more than fine with me for anybody to merge it. Thanks!

**Pull request merged**
