### PR TITLE
CLDR-8802 add Currency abstracts

### PR DESCRIPTION
**Pull request by srl295**
CLDR-8802
- also switch off DEBUG on some of the mappers

image

note that the xpath binding is only on the currency **name**, perhaps we should use a prefix model so that other items (symbol, count-one, count-many, etc) are also handled.

### CODE REVIEW

**Comment by srl295** [comment]
guide for this is here http://cldr.unicode.org/development/updating-abstracts

**Review by macchiati — CHANGES_REQUESTED** [review]
The changes look good, but can you fix the presentation of the information? I should have brought this up earlier. Look at:

https://user-images.githubusercontent.com/855219/103574372-69612580-4e95-11eb-86e4-bfe18136e2cd.png

The format looks broken because "more" overlaps with the text. It is more apparent with other examples where the last line is longer.

I suggest you move the "more" line _below_ the box.

**Comment by srl295** [comment]
image

How does this look?
- removed the border
- the 'more' is part of the box, so what I actually did is _replace_ the last line with the 'more' (made it opaque instead of translucent)

**Comment by btangmu** [comment]
> How does this look?

Looks good!

**Comment by srl295** [comment]
> [View Diff Across Force-Push](https://github.com/unicode-org/cldr/compare/unicode-org:d1a4493..unicode-org:e90d981)

CSS change only. Done.

**Review by btangmu — APPROVED** [review]

**Comment by srl295** [comment]
@macchiati any thoughts on this? would like to merge before the codebase goes stale…

**Review by macchiati — APPROVED** [review]

**Pull request merged**
