### PR TITLE
CLDR-13120 Remove test reference to TestBasic_ja.xml

### PR DESCRIPTION
**Pull request by JCEmmons**
[CLDR-13120]

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13120
- [x] Updated PR title and link in previous line to include Issue number

[CLDR-13120]: https://unicode-org.atlassian.net/browse/CLDR-13120

### CODE REVIEW

**Comment by JCEmmons** [comment]
Fixed the commit comment. just waiting for Travis.

**Comment by JCEmmons** [comment]
ant not installed on travis?

**Comment by srl295** [comment]
@JCEmmons it was working last week… anyway opened https://github.com/unicode-org/cldr/pull/87 — please shepherd this PR (you can push to its branch) as needed?

**Comment by srl295** [comment]
@JCEmmons I'm guessing we are now on 'xenial' — i didn't check the build env but https://changelog.travis-ci.com/draft-pull-requests-support-105121 seems to imply that you're supposed to ask for ant if you want it.

**Comment by srl295** [comment]
This test has been dead code 3 years ago https://github.com/JCEmmons/cldr/commit/76aa50d27ddc67a620038a5e9be1a41c5a939320#diff-8dc4cbd57d3e341cc14e9ad63922f7a3L1292

**Pull request merged**
