### PR TITLE
CLDR-14787 UI polish on transfer votes

### PR DESCRIPTION
**Pull request by srl295**
- also fix a typo and access for CLDR-14804

CLDR-14787

- [X] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
## Link for kicking off the process

Updated flyover text. 
image

**Comment by srl295** [comment]
@stenshamn @btangmu @macchiati @DavidLRowe how about "Copy votes from…" for the link?

**Comment by macchiati** [comment]
Copy votes to this vetter
Or
Copy votes to here

**Comment by srl295** [comment]
- no longer shows a 'preview' on mouseover in the choose-source-user page
- "one button" per locale as per below:
image

**Comment by srl295** [comment]
text is "copy votes to this vetter"
image

**Comment by srl295** [comment]
@btangmu feel free to merge if we're getting close to push to prod

**Review by macchiati — APPROVED** [review]
Lgtm

**Review by btangmu — APPROVED** [review]

**Pull request merged**
