### PR TITLE
Cldr 15291 remove invalid and duplicate files

### PR DESCRIPTION
**Pull request by pedberg-icu**
CLDR-15291

- [ ] This PR completes the ticket.

This fixes some problems in the brs/v41data branch for CLDR 41 data import:
* Removes the mul*.xml files, which are for a sandbox and should not be checked into CLDR
* Removes the seed/main versions of kgp.xml/kgp_BR.xml/sc.xml/sc_IT.xml in favor of the common/main versions; the latter either have identical contents of (in the case of kgp.xml) are much more complete.

### CODE REVIEW

**Comment by pedberg-icu** [comment]
Oops, opened this against wrong branch will redo

**Comment by srl295** [comment]
@pedberg-icu  I'll change the merge target to v41

**Comment by srl295** [comment]
you don't have to redo just edit

**Comment by srl295** [comment]
@pedberg-icu  you can reopen and click Edit at top and change the target

**Comment by srl295** [comment]
image

**Comment by pedberg-icu** [comment]
> @pedberg-icu you can reopen and click Edit at top and change the target

Oh, I did not know you could use Edit to change the merge target. Good to know, thanks!

**Pull request closed without merging**
