### PR TITLE
CLDR-13779 First pass E13.1

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13779
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by macchiati** [comment]
TODO: add skintones to Couples with Heart and Couples Kissing

**Comment by macchiati** [comment]
Sorry, but had to resolve merge. Can you rereview?

**Comment by macchiati** [comment]
I think these are all the emoji we need for Submission.

If you look at the derivedAnnotations, you'll see that we already have names for the combinations without skin tones. There is still some code (and spec) work to do for the derivedAnnotations to add the combinations with skin tones, but we won't need additional translations.

Now, we do need the right images. I didn't get them yet, so they are just the base images. But this will get us up and running.

		<annotation cp="👩‍❤‍💋‍👨">couple | kiss | man | woman</annotation>
		<annotation cp="👩‍❤‍💋‍👨" type="tts">kiss: woman, man</annotation>
		<annotation cp="👨‍❤‍💋‍👨">couple | kiss | man</annotation>
		<annotation cp="👨‍❤‍💋‍👨" type="tts">kiss: man, man</annotation>
		<annotation cp="👩‍❤‍💋‍👩">couple | kiss | woman</annotation>
		<annotation cp="👩‍❤‍💋‍👩" type="tts">kiss: woman, woman</annotation>
		<annotation cp="👩‍❤‍👨">couple | couple with heart | love | man | woman</annotation>
		<annotation cp="👩‍❤‍👨" type="tts">couple with heart: woman, man</annotation>
		<annotation cp="👨‍❤‍👨">couple | couple with heart | love | man</annotation>
		<annotation cp="👨‍❤‍👨" type="tts">couple with heart: man, man</annotation>
		<annotation cp="👩‍❤‍👩">couple | couple with heart | love | woman</annotation>
		<annotation cp="👩‍❤‍👩" type="tts">couple with heart: woman, woman</annotation>

**Comment by pedberg-icu** [comment]
OK, that makes sense.
- Peter E

**Pull request merged**
