### PR TITLE
CLDR-15024 get correct coverage information

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-15024

Note that the old comment says specifically "does not skip inheritance marker", but made a function call that **did** skip the inheritance marker.

Note that we would still have to change our process for generating charts, as in the ticket.

- [ ] This PR completes the ticket.

### CODE REVIEW

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
@macchiati LGTM but test failures, summarized here: https://github.com/unicode-org/cldr/actions/runs/1192443901

**Comment by srl295** [comment]
@macchiati actually, click "Files Changed" as if to review your own PR… scroll down… you'll see the test failures in context.

**Comment by macchiati** [comment]
Thanks! Made a fix, and we'll see how the tests do.

Mark

**Comment by macchiati** [comment]
Can you review so I can merge?

**Review by srl295 — APPROVED** [review]

**Pull request merged**
