### PR TITLE
CLDR-17049 fix retain in fr PNF initials

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17049

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by pedberg-icu** [comment]
> Rich, Peter, Dragan, if this would cause problems for the integration, we can hold off on it.

I do not think it will be a problem

**Review by pedberg-icu — DISMISSED** [review]

**Review by pedberg-icu — APPROVED** [review]

**Comment by pedberg-icu** [comment]
I fixed the test data to match the pattern changes (tests were failing).

**Comment by pedberg-icu** [comment]
I am going to go ahead and merge so we have for CLDR-ICU integration

**Comment by macchiati** [comment]
Thanks!

**Pull request merged**
