### PR TITLE
CLDR-14748 Use GitHub Action Commands to improve test output clarity

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14748

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
@AEApple trying some things to make test failures more clear and accessible

**Comment by srl295** [comment]
image

**Comment by srl295** [comment]
Example test run: https://github.com/unicode-org/cldr/actions/runs/1057415106

**Comment by AEApple** [comment]
Those example test runs look nice!

**Comment by srl295** [comment]
Oooh , i should do something for console checks!

**Review by sffc — APPROVED** [review]
The example you linked above only shows the test output in the GitHub Actions UI; do the annotations also show up correctly in a PR with errors (in a file at a specific line)?

**Comment by srl295** [comment]
> The example you linked above only shows the test output in the GitHub Actions UI; do the annotations also show up correctly in a PR with errors (in a file at a specific line)?

not in forks, due to permissions………………………

**Comment by srl295** [comment]
@sffc https://github.com/srl295/cldr/commits/cldr-14748 has my experiments

**Pull request merged**
