### PR TITLE
CLDR-4903 simpler display of exemplar sets

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-4903

The code and tests are now complete. I'd like to merge this before doing the DAIP step.

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by macchiati** [comment]
Results are in https://docs.google.com/spreadsheets/d/1mqabnPh9CN0DVEep2Uqgw4RVI7tTvt89jl4fFkcXnts/edit#gid=0 for comparison.

**Comment by DavidLRowe** [comment]
> Results are in https://docs.google.com/spreadsheets/d/1mqabnPh9CN0DVEep2Uqgw4RVI7tTvt89jl4fFkcXnts/edit#gid=0 for comparison.

I looked at main exemplar for "bal".
- The "source" lists the characters in order by Unicode value. The "formatted" version lists them in apparently random order. I would think that would make it harder to visually determine what characters are included.
-  The "source" has a range U+0631 to U+0634. The "formatted" changes the range into four individual characters. (Three other ranges were preserved.)
- The hyphen replacement does make it easier to see that a range is indicated.

The listing for "bal_Arab" is a duplicate of "bal" (since bal_Arab has no exemplar data and is falling back to bal, I suppose). Is it needed?

For "az", "source" has "iIİ" since both dotted-i and dotless-i are used. The "formatted" line has "i I İ ı", though I wonder if that should be "i İ ı I" (or "ı I i İ") to match the case mapping used in Azerbaijani.

**Comment by macchiati** [comment]
Converting this to draft. I'm going to change the ticket fixVersion to 44. It turns out that more substantial surgery needs to be done on DAIP than I anticipated.

**Review by srl295 — APPROVED** [review]
LG so far

**Comment by macchiati** [comment]
@DavidLRowe I regenerated the data. Re your comments:

- The "formatted" version lists them in apparently random order. I would think that would make it harder to visually determine what characters are included.
I think the issue is that bal is RTL. The order in this test is the default root order.

- The listing for "bal_Arab" is a duplicate of "bal" (since bal_Arab has no exemplar data and is falling back to bal, I suppose). Is it needed?
This is just a verbose listing from a test, so no need to abbreviate

- For "az", "source" has "iIİ" since both dotted-i and dotless-i are used. The "formatted" line has "i I İ ı", though I wonder if that should be "i İ ı I" (or "ı I i İ") to match the case mapping used in Azerbaijani.
The order for this test is just the root order.

**Review by srl295 — APPROVED** [review]
Looks reasonable.

**Comment by srl295** [comment]
(for the record) so working on CLDR-13180, something broke with this.  It looks like perhaps the encoding is happening _backwards_ when users vote.  I'm going to re-review this PR.

Example: voted for `c q d x` results in a vote in the database for `[{\[cdqx\]}]` (as if, `[cqdx]` but then escaped as a string!) 

Also `c q d x` is shown as a 'red' losing candidate — it doesn't match up with the winning `[{\[cdqx\]}]` 

image

https://cldr-smoke.unicode.org/cldr-apps/v#/agq/Alphabetic_Information/2703e9d07ab2ef3a

**Comment by srl295** [comment]
@macchiati  see https://unicode-org.atlassian.net/browse/CLDR-13180 discussion

**Pull request merged**
