### PR TITLE
CLDR-16929 CLDRModify: add upgrade tool

### PR DESCRIPTION
**Pull request by srl295**
- -fG
- fixed purpose, upgrades Basic paths to unconfirmed
- ignores truly missing paths

Usage: CLDRModify cldr-modify -fG -mvmw

CLDR-16929

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
example run:

```
1 Locales:      [vmw]
%vmw    Unchanged Value Upgrade to contributed  «.»/=   →       ≡       //ldml/numbers/symbols[@numberSystem="latn"]/group[@draft="unconfirmed"]    →       //ldml/numbers/symbols[@numberSystem="latn"]/group[@draft="contributed"]
%vmw    Unchanged Value Upgrade to contributed  «↑↑↑»/= →       ≡       //ldml/numbers/symbols[@numberSystem="latn"]/percentSign[@draft="unconfirmed"]      →       //ldml/numbers/symbols[@numberSystem="latn"]/percentSign[@draft="contributed"]
%vmw    Unchanged Value Upgrade to contributed  «agostu»/=      →       ≡       //ldml/dates/calendars/calendar[@type="gregorian"]/months/monthContext[@type="format"]/monthWidth[@type="wide"]/month[@type="8"][@draft="unconfirmed"]  →       //ldml/dates/calendars/calendar[@type="gregorian"]/months/monthContext[@type="format"]/monthWidth[@type="wide"]/month[@type="8"][@draft="contributed"]
%vmw    Unchanged Value Upgrade to contributed  «abril»/=       →       ≡       //ldml/dates/calendars/calendar[@type="gregorian"]/months/monthContext[@type="format"]/monthWidth[@type="wide"]/month[@type="4"][@draft="unconfirmed"]  →       //ldml/dates/calendars/calendar[@type="gregorian"]/months/monthContext[@type="format"]/monthWidth[@type="wide"]/month[@type="4"][@draft="contributed"]
```

And note that it leaves non-Basic paths alone, see `szl`:

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
If you run GenerateAllCharts, it will regenerate the computed coverages (as well as all the changed charts), and you can check those in (fixing the coverageLevels.xml to get the tests to pass, but you've done that before).

**Comment by srl295** [comment]
> If you run GenerateAllCharts, it will regenerate the computed coverages (as well as all the changed charts), and you can check those in (fixing the coverageLevels.xml to get the tests to pass, but you've done that before).

Yes, I've run showcoverage and that's how I've been able to say which locales will make basic. 

I'm going to do that update as another pass to keep it separate from the one off data PRs. See other PRs

**Comment by srl295** [comment]
> If you run GenerateAllCharts, it will regenerate the computed coverages (as well as all the changed charts), and you can check those in (fixing the coverageLevels.xml to get the tests to pass, but you've done that before).

Yes, I've run showcoverage and that's how I've been able to say which locales will make basic. 

I'm going to do that update as another pass to keep it separate from the one off data PRs. See other PRs

**Pull request merged**
