### PR TITLE
CLDR-18072 Clean up links in CLDR site

### PR DESCRIPTION
**Pull request by btangmu**
-Fix links in seven files, per spreadsheet; rows in spreadsheet have been struck through

-Mark this file as OBSOLETE: design-proposals/xmb.md; keep the reference to it from docs/site/sitemap.tsv

CLDR-18072

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Unless there is a strong reason not to, we want to keep old links working. 

The easiest way to do that is 
* in the sitemap, just move the file to the last under the archive section (above the sitemap)
* in the file in question, add OBSOLETE in the title and first <h1>

cf:
@AEApple

**Comment by btangmu** [comment]
> keep old links working

OK, I've restored xmb.md, adding "OBSOLETE", and I've restored its link from sitemap.tsv

**Review by macchiati — APPROVED** [review]

**Comment by AEApple** [comment]
Longer term can we consider changing the theme of obsolete pages to further differentiate them?

**Comment by macchiati** [comment]
Sure

**Comment by srl295** [comment]
> Longer term can we consider changing the theme of obsolete pages to further differentiate them?

Yes. That would be adding a new layout **obsolete** and then

`layout: obsolete` in the front matter (where the title is)

**Pull request merged**
