### PR TITLE
CLDR-14460 XPathParts remove synchronized block

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14460

On a quick test, seems to give about a 50% speedup in JSON generation.

### CODE REVIEW

**Review by macchiati — APPROVED** [review]
Nice

**Comment by srl295** [comment]
@btangmu like to get your review, then we can merge this

**Review by btangmu — APPROVED** [review]
This is great! I wonder if we have other ConcurrentHashMap with needless sync

**Comment by srl295** [comment]
very possibly.

**Comment by macchiati** [comment]
Might be worthwhile doing a search for "synchroniz"
Mark

**Pull request merged**
