### PR TITLE
CLDR-15962 Update supplementalData's nameOrder

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-15962

- [ ] This PR completes the ticket.

### CODE REVIEW

**Review by richgillam — DISMISSED** [review]
I *think* this looks good, but I frankly don't know enough about what's going on here to be absolutely sure.

**Comment by macchiati** [comment]
We have some supplemental data that is supposed to tell us which locales are themselves surnameFirst. This checks that if we look at the locale date, no locale X has X in its surnameFirst list, if X is not in the supplemental data.

Is that at all clearer?

**Comment by macchiati** [comment]
As a concrete case, the supplemental data was saying that Tamil was givenFirst, but the Tamil locale (ta.xml) was formatting Tamil names as surnameFirst. That was a whoops, so I put in a test and updated the data so it doesn't happen for Tamil (or similar other ones).

**Comment by richgillam** [comment]
>We have some supplemental data that is supposed to tell us which locales are themselves surnameFirst. This checks that if we look at the locale date, no locale X has X in its surnameFirst list, if X is not in the supplemental data.
>
>Is that at all clearer?

Yes, that helps a lot.  I didn't know we had that.

>As a concrete case, the supplemental data was saying that Tamil was givenFirst, but the Tamil locale (ta.xml) was formatting Tamil names as surnameFirst. That was a whoops, so I put in a test and updated the data so it doesn't happen for Tamil (or similar other ones).

Makes sense.

**Review by richgillam — APPROVED** [review]
Looks good.

**Pull request merged**
