### PR TITLE
CLDR-16815 fix vote-for-inheritance showing up again

### PR DESCRIPTION
**Pull request by srl295**
- need to include both triple up arrow (soft) AND explicit (hard) votes

CLDR-16815

URLS for testing:

with this PR, these should both show users under the info panel voting for all values

https://cldr-smoke.unicode.org/cldr-apps/v#/mt//6e373b70f56b2bde (now broken!)
https://cldr-smoke.unicode.org/cldr-apps/v#/tk//e8ba06720b375aa (now fixed!)

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
Thanks. Maybe push this Monday if smoke looks ok

**Comment by macchiati** [comment]
Or beforehand, since otherwise the visible vote counts are wrong for Monday
for most of the world

**Comment by srl295** [comment]
The visible counts are correct. It just doesn’t show who voted for
inheritance in some casss unless you show the transcript. If smoke looks ok
feel free to push.

**Comment by srl295** [comment]
I’m also not sure there aren’t other latent bugs here since a common case
was already broken.

**Pull request merged**
