### PR TITLE
CLDR-15180 Update locales.txt with new locales

### PR DESCRIPTION
**Pull request by AEApple**
CLDR-15180

Update locales.txt with 3 new locales for Google

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by AEApple** [comment]
Why is the Jira ticket number not being recognized?

**Review by macchiati — DISMISSED** [review]

**Review by srl295 — DISMISSED** [review]
LGTM, warnings unrelated

**Comment by srl295** [comment]
> Why is the Jira ticket number not being recognized?

because of the ` - ` hypen after the number.

**Comment by AEApple** [comment]
> > Why is the Jira ticket number not being recognized?
> 
> because of the `-` hypen after the number.

Can you update the comment to put in a warning about that or update the check so it doesn't consider anything following the space as part of the check?

**Comment by srl295** [comment]
> > > Why is the Jira ticket number not being recognized?
> > 
> > 
> > because of the `-` hypen after the number.
> 
> Can you update the comment to put in a warning about that or update the check so it doesn't consider anything following the space as part of the check?

- The ` - ` actually does make the commit message harder to read so I would propose to remove that hyphen.
- I did file https://github.com/unicode-org/jira-github-pr-check/issues/36 to improve the warning message.

**Review by srl295 — APPROVED** [review]
LGTM

**Pull request merged**
