### PR TITLE
CLDR-14931 Change timing of automatic Survey Tool database backups

### PR DESCRIPTION
**Pull request by btangmu**
-Change backup starting time to 14:53 UTC = 7:53 PDT or 6:53 PST

-Comments in backup-db-playbook.yml and backup_sh.j2

CLDR-14931

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
This PR doesn't quite finish the ticket, since we'll still need to run backup-db-playbook.yml (I don't think the playbook itself runs automatically)

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
LGTM. Not sure using a temporary disk would speed things up much.

**Comment by btangmu** [comment]
> LGTM. Not sure using a temporary disk would speed things up much.

Hard to predict... here someone advises "Make sure your output is going to a different drive(s) than the one(s) the database files are stored on - this will make a massive difference with spinning disks as the drive heads will not be constantly flicking between the location being read from and the location being written to"   https://dba.stackexchange.com/questions/20/how-can-i-optimize-a-mysqldump-of-a-large-database

I might test that manually on smoketest...

**Comment by srl295** [comment]
> > LGTM. Not sure using a temporary disk would speed things up much.
> 
> Hard to predict... here someone advises "Make sure your output is going to a different drive(s) than the one(s) the database files are stored on - this will make a massive difference with spinning disks as the drive heads will not be constantly flicking between the location being read from and the location being written to" https://dba.stackexchange.com/questions/20/how-can-i-optimize-a-mysqldump-of-a-large-database
> 
> I might test that manually on smoketest...

the main benefit would be , if it would reduce downtime.

**Pull request merged**
