### PR TITLE
CLDR-15291 BRSv41§A03: -z FINAL_TESTING

### PR DESCRIPTION
**Pull request by srl295**
CLDR-15291

- [ ] This PR completes the ticket.

First step before checking in XML

### CODE REVIEW

**Comment by btangmu** [comment]
Errors include:

 am [Amharic]	error	▸Units|Duration|decade|short-one-nominative◂	〈{0} dec〉	【】	〈{0} አስር አመታት〉	«=»	【】	⁅value too wide⁆	❮Error: Too wide by about 100% (with common fonts).❯	https://st.unicode.org/cldr-apps/v#/am//349f0131a9908fba
Error:  am: value too wide @ Units|Duration|decade|short-one-nominative

Should this PR be merged in spite of errors, and the errors then corrected in separate PRs?

**Comment by AEApple** [comment]
> Should this PR be merged in spite of errors, and the errors then corrected in separate PRs?

Yes, we had agreed we were going to fix the errors in xml, unless there are new unexpected errors.

**Review by btangmu — APPROVED** [review]

**Comment by srl295** [comment]
@AEApple  well, there's no new xml in this ticket. 

Could we try using a separate branch for fixing these issues, and then merge it back into main?

**Comment by srl295** [comment]
let's try it anwyay…

**Comment by srl295** [comment]
See https://github.com/unicode-org/cldr/pull/1690 for the branch.

**Pull request merged**
