### PR TITLE
CLDR-12007 XPathParts.cloneAsThawed copy dtdData instead of making it…

### PR DESCRIPTION
**Pull request by btangmu**
[CLDR-12007]

- copy dtdData instead of making it null
- remove part of TestRegularized so that it passes
- DistinguishedXPath.getDistinguishingXPath call XPathParts.getTestInstance instead XPathParts.set 
- comment out a few temporary debugging println for [CLDR-12020]

[CLDR-12020]: https://unicode-org.atlassian.net/browse/CLDR-12020

[CLDR-12007]: https://unicode-org.atlassian.net/browse/CLDR-12007

### CODE REVIEW

**Comment by srl295** [comment]
- perhaps printfs should be turned on/off with a debugging switch? or at least a final boolean?
- PR looks structurally OK  - it's common to use a short first line of the commit, skip a line, then have shorter lines after. 
- mention [CLDR-12007] in the body of the PR so that it gets linked.
- instead of 'issue 12020' write:  [CLDR-12020]

**Comment by btangmu** [comment]
Thanks, Steven! I see the [CLDR-12020] link requires square brackets. Good to know.

About those temporary println statements, my intention is to delete them before finishing [CLDR-12020] and anyway before shakedown, otherwise I would have made them dependent on a DEBUG boolean.

**Comment by btangmu** [comment]
I will squash and make a new pull request.

**Comment by srl295** [comment]
@btangmu there's no need to make a new pull request… you can squash and force push to the same branch.

**Comment by btangmu** [comment]
@srl I did the squashing by making a new branch. That seemed cleaner and safer to me than forcing to the same branch or messing with the existing pull request. Locally now I still have both t12007_XPathParts and t12007_XPathParts_squashed. I'll add a link from the new PR to this one to keep the history of discussions.

**Comment by srl295** [comment]
It’s actually cleaner to keep the PR because then history is retained. And
squashing on the same branch is fine.

**Pull request closed without merging**
