### PR TITLE
CLDR-15347 add likelySubtag sd_IN → sd_Deva_IN and supporting demographics

### PR DESCRIPTION
**Pull request by pedberg-icu**
CLDR-15347

- [x] This PR completes the ticket.

Add likelySubtags from sd_IN to sd_Deva_IN; Deva is the official script for Sindhi in India (Arab, Guru, Koj also used); in Pakistan it is Arab.

Update the territoryInfo for sd_Deva in IN.

### CODE REVIEW

**Review by DavidLRowe — APPROVED** [review]
LGTM

**Comment by roozbehp** [comment]
Where is the source for the claim the Indian Sindhi is more commonly or officially written in Devanagari? (I believe I've seen claims that Arabic is more common for Sindhi in both countries.)

**Comment by DavidLRowe** [comment]
The article cited (https://en.wikipedia.org/wiki/Languages_with_official_status_in_India), claims "Each official language has a designated official script using which it is written for official purposes." and lists Sindhi under Devanagari. Is there a better source of information?

**Comment by roozbehp** [comment]
> The article cited (https://en.wikipedia.org/wiki/Languages_with_official_status_in_India), claims "Each official language has a designated official script using which it is written for official purposes." and lists Sindhi under Devanagari. Is there a better source of information?

That section of the Wikipedia article appears to be unsourced. I think someone should consult the Ethnologue or ask SIL.

**Comment by DavidLRowe** [comment]
I'm not sure that "more common" is the criterion that CLDR uses, but I'll defer to @macchiati on that. If Deva is the official script for the language (as used in India), that might carry more weight.

Ethnologue has for Sindhi (Pakistan): "Arabic script, Naskh variant [Arab], primary usage. Devanagari script [Deva], used in India. Gurmukhi script [Guru], used in India. Khojki script [Khoj]." which doesn't really specify which script is most used for the language in India.

**Comment by pedberg-icu** [comment]
@roozbehp Well, http://ncpsl.gov.in (NATIONAL COUNCIL FOR PROMOTION OF SINDHI LANGUAGE, Ministry of Education, Govt of India) has its main title in Devanagari. Also there is the practical issue that the only sd locale that CLDR has for India is sd_Deva_IN.

**Comment by roozbehp** [comment]
LGTM mostly based on the NCPSL website. Uneasy though.

**Comment by pedberg-icu** [comment]
OK, I checked with Karan Miśra. He says "Sindhi—as specified in the 22 scheduled languages of India—is in the Devanagari script".

**Pull request merged**
