### PR TITLE
CLDR-13180 Use locale-sensitive DAIP on display

### PR DESCRIPTION
**Pull request by srl295**
CLDR-13180

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — APPROVED** [review]
LGTM

**Comment by srl295** [comment]
@macchiati feel free to test if you want (staging or wherever), i just won't be able to

**Comment by macchiati** [comment]
I'll try it out, but no hurry to get it done by Monday.

**Comment by srl295** [comment]
trying it out locally

**Comment by macchiati** [comment]
Great, thanks!

**Pull request merged**
