### PR TITLE
CLDR-14927 Explain TZDB links and aliases

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-14927

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by macchiati** [comment]
Can one of you review this?

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
@macchiati  looks like 'check' was not required for merge.  Can you squash it so that it attempts a rebuild?

**Comment by srl295** [comment]
looks like tests didn't run, probably due to github issues yesterday

**Comment by macchiati** [comment]
Steven, the "check Expected — Waiting for status to be reported" appears to be hung. How can we unblock it?

**Comment by srl295** [comment]
> Steven, the "check Expected — Waiting for status to be reported" appears to be hung. How can we unblock it?

I suggested above squashing it. Basically you need to make some commit change to it so that it rebuilds.

**Pull request merged**
