### PR TITLE
CLDR-16969 CLDRModify passes before alpha0

### PR DESCRIPTION
**Pull request by DraganBesevic**
CLDR-16969

**This must be merged with merge commit, not squashed**

- [x] This PR completes the ticket.

CLDRModify no arguments

- foreignSpaceReplacement and nativeSpaceReplacement - added xml:space=“preserve”
- put elements and attributes in canonical order
- reordering emoji annotations 

CLDRModify -fQ

- Added TTS names to annotations (without regard for capitalization - investigate!)
- Merged annotations into a single value (cv, bew) - investigate!

CLDRModify -fP

- Deduplicating and reordering exemplars
- Updated time format with NNBSP
- Issue with kxv_Deva, causing unit test failures on exemplar sets - file reverted, investigate!

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — APPROVED** [review]
@pedberg-icu @srl295 In the generation of the XML data by the ST, if we added the xml:space it would reduce the noise in this step.

**Comment by srl295** [comment]
> @pedberg-icu @srl295 In the generation of the XML data by the ST, if we added the xml:space it would reduce the noise in this step.

Think there's a ticket for that to make that permanent for this xpath.

**Comment by srl295** [comment]
Please rename PR to start with: CLDR-16969

**Comment by pedberg-icu** [comment]
> Please rename PR to start with: CLDR-16969

@srl295  ?? The name _does_ start with CLDR-16969 (the name was fixed immediately after the PR was created)

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
> > Please rename PR to start with: CLDR-16969
> 
> @srl295 ?? The name _does_ start with [CLDR-16969](https://unicode-org.atlassian.net/browse/CLDR-16969) (the name was fixed immediately after the PR was created)

OK, I was just responding to the email. I probably misread the thread. 

@macchiati  https://unicode-org.atlassian.net/browse/CLDR-16455 is for xml:space

**Pull request merged**
