### PR TITLE
CLDR-15913 Make LogicalGrouping thread-safe.

### PR DESCRIPTION
**Pull request by Yqwed**
LogicalGrouping.getPaths might be called from different threads created in GenerateProductionData.

Wrapping the existing cache into Multimaps.synchronizedMultimap is not enough as underlying ArrayList is also should be synchronized: it is traversed in new TreeSet<>(cache.get()) and modified in cache.putAll() calls.

CLDR-15913

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by Yqwed** [comment]
Please let me know if LogicalGrouping change is fine to land on its own. I will then revert GenerateProductionData and handle it in a following PR.

**Comment by srl295** [comment]
@Yqwed  I'll update the PR. I'm actually going to land it on maint-42  - thank you!

**Review by srl295 — APPROVED** [review]
LGTM, like to get someone else to review the synchronized part that I added

**Comment by srl295** [comment]
@markusicu  @pedberg-icu  verified that this builds OK

**Review by pedberg-icu — APPROVED** [review]

**Review by markusicu — APPROVED** [review]
looks plausible, but I don't know this code

**Comment by srl295** [comment]
@Yqwed  Thanks ! Confirmed that the output remains the same with and without this.

@pedberg-icu  go ahead and merge if you'd like if i miss it

**Comment by pedberg-icu** [comment]
I did a CLDR-ICU integration using the updated (re-parallelized) tooling from this PR and had no problems.

**Comment by Yqwed** [comment]
Thanks, Steven!

**Pull request merged**
