### PR TITLE
CLDR-13919 Error E_UNKNOWN interrupts data entry

### PR DESCRIPTION
**Pull request by btangmu**
-Guard against accessing theRow.winningVhash if theRow is null or undefined

-Comments

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13919
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by srl295** [comment]
It does guard, but only logs. What is the impact if those functions do not continue processing?

**Comment by btangmu** [comment]
> It does guard, but only logs. What is the impact if those functions do not continue processing?

Good question. I don't know. I was unable to repro the bug, or figure out how theRow could be undefined. If theRow is null or undefined, that evidently violates assumptions made when the code was originally written. If a function is called with invalid arguments, I think it's better to return than to continue processing, especially if to continue processing will throw an exception trying to dereference a null pointer.

If and when theRow is null or undefined again, we'll probably eventually see other symptoms of the underlying cause.

We'll be better equipped to prevent such errors when more of the js code is strict and covered by tests.

**Comment by srl295** [comment]
we might want to have a kind of 'popup message' (and/or something indicated
on the server side) so we can catch these.

I'm guessing that the server side here is some kind of an illegal state,
possibly even a stale session, where no rows are coming back.

**Comment by macchiati** [comment]
> popup message

Maybe just a console warning or logging the problem? A visible warning to
users, one that they can't do anything about is, just disruptive and
confusing for them.

Mark

**Pull request merged**
