### PR TITLE
CLDR-14251 Modernize: remove v.jsp; add SurveyTool.java, CldrGui.js

### PR DESCRIPTION
**Pull request by btangmu**
-New SurveyTool.java with most of the Java from v.jsp

-New CldrGui.js with most of the HTML from v.jsp

-Remove SurveyAjax.includeEvilJavaScript; handle more such items with CldrStatus.js

-Move SurveyAjax.includeJavaScript and related code to SurveyTool.java

-Extend statusJSON, new class StatusForFrontEnd to include more info needed by front end

-More js unit tests; encapsulate parseAsMimeType in new TestCldrTest.js

-Change dojo config parseOnLoad to false, instead use dojo/parser in cldrGui.run

-In redesign/review.js, use dojo/ready instead of jquery equivalent: wait for cldrGui.run

-Skip dojo/ready where superfluous

-Use XMLHttpRequest instead of dojo/request in cldrStAjax, per vanilla-js.com

-Rename dojo dependencies in showV for clarity, e.g. dojoxBusyButton for BusyButton

-Normalize error handlers for cldrStAjax.sendXhr: err parameter is always a string

-New CldrText.js to replace stui.str and stui.sub; no more dojo/string or loadStui

-New WHAT_ADMIN_PANEL so front end does not need vap for URL if logged in as admin

-Restore/revise comment about fonts in surveytool.css (removed in PR 877)

-Fix CLDR-14365 by calling hideRightPanel from loadHandler for Date, Zones, Numbers reports

-Run npx prettier on all .js files except those that are minified

-Remove dead code; clean up

-Comments

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14251
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
This is identical to https://github.com/unicode-org/cldr/pull/893 except that I ran "npx prettier" (with default options) on all the js files except those that are minified

**Comment by btangmu** [comment]
There are so many changes in this PR, it may have some bugs. Still, I suggest that we merge it, to keep the momentum going with modernization, and to avoid the branch getting so far removed from the main branch that merging becomes problematic.

Reviewing this PR is complicated by the reformatting of all the JS files. For that reason, I made draft PR #893 which is identical but without the JS reformatting. I suggest looking at PR #893 to see what the (non-formatting) changes are.

There's a new warning from Dojo, which is probably a bug in Dojo and not worth fixing assuming we manage to remove Dojo in the coming weeks:

dojo/parser::parse() error SyntaxError: invalid regular expression flag r
    Dojo 88
    showV CldrSurveyVettingLoader.js:20
    run CldrGui.js:41
    <anonymous> survey.js:1369
    Dojo 14
    <anonymous> survey.js:1366
parser.js.uncompressed.js:900:5

Error parsing in _ContentSetter#Setter_DIV_0 SyntaxError: invalid regular expression flag r
    Dojo 88
    showV CldrSurveyVettingLoader.js:20
    run CldrGui.js:41
    <anonymous> survey.js:1369
    Dojo 14
    <anonymous> survey.js:1366
ContentPane.js.uncompressed.js:598:4

Error dijit_Dialog_0 running custom onLoad code: This deferred has already been resolved ContentPane.js.uncompressed.js:443:4
    Dojo 82
    showV CldrSurveyVettingLoader.js:20
    run CldrGui.js:41
    <anonymous> survey.js:1369
    Dojo 14
    <anonymous> survey.js:1366

**Comment by btangmu** [comment]
Just to clarify: the Dojo warning is annoying but there doesn't appear to be any related problem with Survey Tool running.

**Review by macchiati — APPROVED** [review]
I agree on merging them. So that we don't block you, I'm approving since Steven is out.

**Comment by srl295** [comment]
sgtm will review later when i can

**Comment by srl295** [comment]
if it's truly identical i can review https://github.com/unicode-org/cldr/pull/892 - hard to review with the prettier.  I recommend that the prettier type change be a separate PR so it can be reviewed separately.

**Comment by btangmu** [comment]
> if it's truly identical i can review #892 - hard to review with the prettier. I recommend that the prettier type change be a separate PR so it can be reviewed separately.

Yes, it's truly identical. The only change between #892 and #893 is prettier; I was careful to do it that way. Since Mark already approved and I already merged the PR, it's late for another PR. If you're concerned that prettier may have had bad effects, you could check out the earlier version and run prettier on it. I think the results are really good, and only affect the formatting, not what the code does. The extreme irregularities of the old formatting were severely impeding my progress.

FYI I now have extensive further changes on another branch. I'm making more distinction between the old versions of js files that depend on dojo (directly or indirectly), and the new versions that don't. I'm adding a boolean USE_DOJO in SurveyTool.java that determines which versions of the js files are used, so for a while at least we'll be able to switch back and forth, until we can remove the dojo code permanently.

**Pull request merged**
