### PR TITLE
CLDR-14826 add Belarusian classical locale

### PR DESCRIPTION
**Pull request by DavidLRowe**
CLDR-14826

- [x] This PR completes the ticket.

I think the file included in this PR will complete the ticket. Please correct me if I'm wrong!

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Hmm. I see the Priority on https://unicode-org.atlassian.net/browse/CLDR-14826 is set to "assess", so perhaps this pull request is premature? I'm afraid I'm unclear on what the procedure is.

**Comment by srl295** [comment]
> Hmm. I see the Priority on https://unicode-org.atlassian.net/browse/CLDR-14826 is set to "assess", so perhaps this pull request is premature? I'm afraid I'm unclear on what the procedure is.

it means it wasn't given a more specific priority . please go ahead and update. I've bumped the version to 40

**Comment by srl295** [comment]
@DavidLRowe test failures:

```
223
be_tarask [Belarusian (Taraskievica orthography)]	error	▸Numbers|Symbols|Symbols_|group◂	〈,〉	【】	〈 〉	«=»	【】	⁅must not start or end with space⁆	❮Error: This item must not start or end with whitespace, or be empty.❯	https://st.unicode.org/cldr-apps/v#/be_tarask//a1ef41eaeb6982d
```

Not sure what the issue is here. Looks like the item might be a space or have a space.

```
224
be_tarask [Belarusian (Taraskievica orthography)]	error	▸Numbers|Compact_Decimal_Formatting|Short_Currency_|10-digits-short-one◂	〈¤0B〉	【】	〈0 млрд ¤ 〉	«=»	【】	⁅must not start or end with space⁆	❮Error: This item must not start or end with whitespace, or be empty.❯	https://st.unicode.org/cldr-apps/v#/be_tarask//25c68f50dbcb3dcf
225
be_tarask [Belarusian (Taraskievica orthography)]	error	▸Numbers|Compact_Decimal_Formatting|Short_Currency_|10-digits-short-few◂	〈¤0B〉	【】	〈0 млрд ¤ 〉	«=»	【】	⁅must not start or end with space⁆	❮Error: This item must not start or end with whitespace, or be empty.❯	https://st.unicode.org/cldr-apps/v#/be_tarask//4dba61e64dee6022
226
be_tarask [Belarusian (Taraskievica orthography)]	error	▸Numbers|Compact_Decimal_Formatting|Short_Currency_|10-digits-short-many◂	〈¤0B〉	【】	〈0 млрд ¤ 〉	«=»	【】	⁅must not start or end with space⁆	❮Error: This item must not start or end with whitespace, or be empty.❯	https://st.unicode.org/cldr-apps/v#/be_tarask//147950bb55034bed
227
be_tarask [Belarusian (Taraskievica orthography)]	error	▸Numbers|Compact_Decimal_Formatting|Short_Currency_|10-digits-short-other◂	〈¤0B〉	【】	〈0 млрд ¤ 〉	«=»	【】	⁅must not start or end with space⁆	❮Error: This item must not start or end with whitespace, or be empty.❯	https://st.unicode.org/cldr-apps/v#/be_tarask//15f38a11195dc9e9
228
# be_tarask [Belarusian (Taraskievica orthography)]	Summary	basic	Items (including inherited):	31461
229
# be_tarask [Belarusian (Taraskievica orthography)]	Summary	basic	Subtotal error:	5
230
```

For these, just remove the space at the end after the `¤`

**Comment by srl295** [comment]
@DavidLRowe 

```xml
			<group draft="provisional"> </group>
```

needs to be a NBSP. Can do this if needed: (it'll get normalized later)

```xml
			<group draft="provisional">&#x00A0;</group>
```

**Comment by srl295** [comment]
alsothe commit message needs to be fixed and the commits squashed into one.

**Comment by DavidLRowe** [comment]
@srl295 I think this is ready for review.

**Review by srl295 — APPROVED** [review]
RSLGTM

spot checked `0 млрд ¤` and the group.

**Pull request merged**
