### PR TITLE
CLDR-18006 site: updates to top bar

### PR DESCRIPTION
**Pull request by srl295**
- drop Site Map from header
- drop "temporary navigation" notice

CLDR-18006

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

## Review Notes

- check the main and site map pages' top nav bar
- still doesn't line up 100%

image

### CODE REVIEW

**Comment by srl295** [comment]
@macchiati this means you can't get to the site map unless you're on the home page. Maybe that's OK?

**Comment by macchiati** [comment]
They still aren't vertically centered. Look at the following:

```
<!DOCTYPE html>
<html>
<head>
<style>
.verticalCenter {
  display: flex;
  align-items: center;
}

</style>
</head>
<body>

<div class='verticalCenter'>
  <img src="https://cldr.unicode.org/assets/img/logo60s2.gif" style='margin-right:1em'><span>Unicode CLDR Project ❱ CLDR Technical Committee ❱ CLDR Keyboard Subcommittee</span>

</div>
</body>
</html>
```

In an online test, say, https://www.w3schools.com/cssref/tryit.php?filename=trycss_text-indent

Not complete, but you can see the idea. Narrow the window, and the alignment still works.

**Comment by macchiati** [comment]
As to the sitemap, for now we can have it just in the first subpages. We can discuss later whether we need it on each page, and where to put it. (People generally look for it in a footer.)

**Comment by srl295** [comment]
Yes, I specifically said that they were not vertically centered.

**Comment by macchiati** [comment]
Right, I was just pointing out a simple method to vertically center them.

**Comment by srl295** [comment]
image

give this a try

**Comment by macchiati** [comment]
It is not as good as the flex approach when the breadcrumb exceeds the window width.
Screenshot 2024-10-10 at 09 17 02

However, it is good enough for v46 release, if you want to spin off a future ticket to take care of that.

**Review by macchiati — APPROVED** [review]
But open a ticket to refine (or add to existing ticket)

**Comment by srl295** [comment]
> It is not as good as the flex approach when the breadcrumb exceeds the window width. Screenshot 2024-10-10 at 09 17 02
> 
> However, it is good enough for v46 release, if you want to spin off a future ticket to take care of that.

it's using flex, at least partly…

**Comment by macchiati** [comment]
I opened a new subtask https://unicode-org.atlassian.net/browse/CLDR-18017 as you suggested.

**Pull request merged**
