### PR TITLE
CLDR-17736 Update approximate widths

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17736

May fix some of the fulah items

FYI, this should be a yearly BRS item

NOTE
The check-console gets two errors, because the abbreviated forms are longer than the wide values. Looking at a variety of fonts, these are in fact errors that should show up in the survey tool.

However, if the console-check is run with BUILD mode (as it should be), then these two errors should not block merging.

"ई. स. पू. युग"
"ईसापूर्व युग"

"جماد ۱"
"جماعه"

mr [Marathi]	error	▸Date_&_Time|Gregorian|Eras_-_abbreviated|0-variant◂	〈BCE〉	【】	〈ई. स. पू. युग〉	«=»	【】	⁅abbreviated date field too wide⁆	❮Error: Abbreviated value "ई. स. पू. युग" can't be longer than the corresponding wide value "ईसापूर्व युग"❯	https://st.unicode.org/cldr-apps/v#/mr//efe32222ec06f22

ps [Pashto]	error	▸Date_&_Time|Islamic|Months_-_abbreviated_-_Formatting|May◂	〈Jum. I〉	【】	〈جماد ۱〉	«=»	【】	⁅abbreviated date field too wide⁆	❮Error: Abbreviated value "جماد ۱" can't be longer than the corresponding wide value "جماعه"❯	https://st.unicode.org/cldr-apps/v#/ps//6f92de7116b2180f

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by srl295 — COMMENTED** [review]
code changes LGTM

- the data is very verbose, is it really necessary to have the codepoint name? If it was just runs of widths, I'd think filling in entire blocks might be smaller even. I see:

```
xxxx5-xxxxB ; 0 ; # LONG NAME OF SOMETHING
xxxxD-xxxxF ; 0 ; # LONG NAME OF SOMETHING
```

but probably xxxxC is also `0`

**Comment by srl295** [comment]
console check is run in -z BUILD currently

**Comment by macchiati** [comment]
> console check is run in -z BUILD currently

@srl295 
I'm confused. CheckWidths.java is supposed to only emit warnings when in BUILD. Could you look that code over, because as far as I can see it does that. So it shouldn't emit errors and thus block a merge. I think these are the relevant lines:

```
183: CheckStatus.Type errorType = CheckStatus.warningType;
192: errorType = CheckStatus.errorType;
206: errorType = CheckStatus.warningType;
208: errorType = CheckStatus.errorType;
219: new CheckStatus()
```

**Comment by macchiati** [comment]
P.S. This is not a blocker for Vetting Phase, though I'd like to get it in very soon, since I think it solves the Fulah errors.

**Comment by srl295** [comment]
> P.S. This is not a blocker for Vetting Phase, though I'd like to get it in very soon, since I think it solves the Fulah errors.

ok . i will work on it while waiting for results of the sanity check.

**Comment by srl295** [comment]
@macchiati I pulled down this PR and was able to repro the message

```shell
$ cldr-check -z BUILD -f mr
[-e, -z, BUILD, -f, mr]
#-f     file_filter     ≔       mr
#-t     test_filter     ≝       .*
#-o     organization    ≝       .*
#-p     path_filter     ≝       .*
#-e     errors_only     ≔       null
#-s     source_directory        ≝       /Users/srl295/src/cldr2/common/main/,/Users/srl295/src/cldr2/common/annotations/,/Users/srl295/src/cldr2/seed/main/
#-z     phase   ≔       BUILD
#-g     generate_html   ≝       /Users/srl295/src/cldr-staging/docs/charts/46//errors/
#-y     subtype_filter  ≝       .*
#-S     source_all      ≝       common,seed,exemplars
Source directories:

    /Users/srl295/src/cldr2/common/main (/Users/srl295/src/cldr2/common/main)
    /Users/srl295/src/cldr2/common/annotations  (/Users/srl295/src/cldr2/common/annotations)
    /Users/srl295/src/cldr2/seed/main   (/Users/srl295/src/cldr2/seed/main)
filtered tests: [CheckAnnotations, CheckChildren, CheckCoverage, CheckDates, CheckForCopy, CheckDisplayCollisions, CheckExemplars, CheckForExemplars, CheckForInheritanceMarkers, CheckNames, CheckNumbers, CheckMetazones, CheckLogicalGroupings, CheckAlt, CheckAltOnly, CheckCurrencies, CheckCasing, CheckConsistentCasing, CheckQuotes, CheckUnits, CheckWidths, CheckPlaceHolders, CheckPersonNames, CheckNew]
Locale  Status  ▸PPath◂ 〈Eng.Value〉   【Eng.Ex.】     〈Loc.Value〉   «fill-in»       【Loc.Ex】      ⁅error/warning type⁆    ❮Error/Warning Msg❯     Full Path    AliasedSource/Path?
/Users/srl295/src/cldr2/common/main/mr.xml:2043:54: error
mr [Marathi]    error   ▸Date_&_Time|Gregorian|Eras_-_abbreviated|0-variant◂    〈BCE〉 【】    〈ई. स. पू. युग〉 «=»     【】    ⁅abbreviated date field too wide⁆    ❮Error: Abbreviated value "ई. स. पू. युग" can't be longer than the corresponding wide value "ईसापूर्व युग"❯   https://st.unicode.org/cldr-apps/v#/mr//efe32222ec06f22
# mr [Marathi]  Summary modern  Items:  10969   Raw Missing:    144     Raw Provisional:        0
# mr [Marathi]  Summary modern  Total missing from general exemplars:   20      [\u200B ॲ a b c d e f g i l m n o p r s u x z]
# mr [Marathi]  Summary modern  Subtotal error: 1
# mr Elapsed time: : 5.732 s

# Total error:  1

# Total elapsed time: : 9.784 s

<< FAILURE - Error count is 1 . >>
```

**Comment by srl295** [comment]
@macchiati digging in, the error is coming from this code

https://github.com/macchiati/cldr/blob/d53cd8d713b86ef939a8faab47dbd82e2f403bd8/tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java#L491-L504

which seems to not have anything to do with the  -z BUILD switch, but unconditionally is `errorType`

**Comment by macchiati** [comment]
Excellent, I was stuck but can now fix it

**Review by srl295 — APPROVED** [review]
may eventually want to make this a common function

**Comment by macchiati** [comment]
> may eventually want to make this a common function

I was thinking that too.

**Pull request merged**
