### PR TITLE
CLDR-14154 fix double variant issue in aliases

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14154
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by macchiati** [comment]
Peter, if your review and the tests pass, please go ahead and Merge

**Review by FrankYFTang — APPROVED** [review]
LGTM

**Review by srl295 — COMMENTED** [review]
PMLGTM

**Comment by macchiati** [comment]
This was merged long ago. Maybe the activity is meant for the Jira ticket?

**Pull request merged**
