### PR TITLE
CLDR-15165 2nd batch from minimal review

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-15165

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by macchiati** [comment]
Fixed the bug in Slovak, so ready for review (sorry, was in meetings all afternoon).

**Review by AEApple — APPROVED** [review]
LGTM

Note: It would be easier to review if we were consistent about the ordering of the cases especially between the change and the review sheet (e.g. nominative is last in sk, but first in sv). It would be nice to clean up in the future to have consistent punctation and '...' when the minimal pair is part of a sentence fragment.

**Comment by macchiati** [comment]
Good points. Could you file a ticket?

Mark

**Comment by AEApple** [comment]
Done. [CLDR-15196](https://unicode-org.atlassian.net/browse/CLDR-15196)

**Pull request merged**
