### PR TITLE
CLDR-17868 v46 BRS: derived annotations, cldrmodify

### PR DESCRIPTION
**Pull request by srl295**
CLDR-17868

I also fixed a tool issue that's in several of our tools:  where missing empty parents aren't added.  New class `CLDRTreeWriter` to support writing a tree full of data.  It tracks additions and deletions and fills in missing items.   Examples:

1. if `ca_ES_VALENCIA.xml` is  added, it will automatically write `ca_ES.xml`
2. if you request to remove `sr_Cyrl` it wont' allow it since it has children, it will instead just write an empty file.

`CLDRTreeWriter` is AutoCloseable ;and must be closed after use.

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — DISMISSED** [review]
Looks like the annotations/* ones were mostly because collation changed.

**Review by macchiati — CHANGES_REQUESTED** [review]
> where missing empty parents aren't added

That is a good addition, *for the main directory*. Logically, all of the other directories are read in conjunction with main, so an empty file in main is sufficient.

So the tool (and files) needs to be changes to only create empty files, etc in the main directory.

**Comment by srl295** [comment]
I'll file a ticket separately for the parent locale issue.

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
CLDR-17906 for further parent locale issues

**Pull request merged**
