### PR TITLE
CLDR-14316 doc: document SurveyTool setup

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14213

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
wip…

**Comment by btangmu** [comment]
see also: https://docs.google.com/document/d/1wkJsoQXPcGN_dlCzXzwhfjQoq9Mes7VezIRmNrHWV8c/edit

**Comment by srl295** [comment]
@btangmu I'm planning to leave this open until after the merge (no reason to put it into 44)

**Comment by srl295** [comment]
@btangmu I'd like to merge this in v45  so moving out of draft

**Comment by srl295** [comment]
@btangmu PTAL.  If this is an improvement let's merge it otherwise let me know what you'd like to see.  You had asked about logging for example.

**Review by btangmu — APPROVED** [review]
LGTM -- FYI my own local setup has "root" instead of "surveytool" for the mysql user -- the username doesn't matter as long as you're consistent

also, I always import an existing db from a dump/backup rather than creating a new db, and that might be worthwhile to suggest as an alternative in this doc

My server.env also has these two lines:

WLP_DEBUG_SUSPEND=n
WLP_DEBUG_ADDRESS=7777

-- I'm not sure if they're needed, and I don't remember when/why I added them

A link to this doc might also be helpful here, even though it's also outdated: https://docs.google.com/document/d/1wkJsoQXPcGN_dlCzXzwhfjQoq9Mes7VezIRmNrHWV8c/edit#heading=h.ozmz4163qnxu

**Comment by srl295** [comment]
you can run it as root, but i wouldn't recommend it.  particularly, we might miss if a SQL action requires elevated privileges. some of the forum report code manipulates stored procedures for example.

is that document owned by the U+CLDR-TC drive? If not would you consider moving it there?

I don't know what the suspend is, but https://www.ibm.com/docs/en/was-liberty/core?topic=liberty-customizing-environment says that 7777 is the default port.

**Pull request merged**
