### PR TITLE
CLDR-17516 Revise flag interface

### PR DESCRIPTION
**Pull request by btangmu**
-Move flagging instructions lower, immedately before Request button

-Move that code from cldrInfo to cldrForum

-Revising wording of instructions for clarity and consistency

-Remove unhelpful message, Losing items may be flagged...

-Revise flagging Request button css so flag icon is visible even when not hovering, and changes color when hovering, for emphasis

-Add hover text for the Stop icon in the Others column, same text as shown with Stop icon in the Info Panel

-New reminder in dialog for entering flagging Request post: ...MUST provide justification...

-Disallow making a flagging Request post with unchanged pre-fill contente

-Remove dead code from css

CLDR-17516

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by btangmu** [comment]
This screenshot illustrates the hover text for the stop icon in the Others column, as well as the same text in the Info Panel, now displayed right above the forum Request button, which now has a colorless flag when not hovering on it:

image

**Comment by btangmu** [comment]
This screenshot illustrates the new reminder in the dialog for making a Request post:

image

**Comment by btangmu** [comment]
This screenshot shows the Info Panel after making a flagging Request post:

image

**Comment by btangmu** [comment]
My second commit addresses a problem with LTR vs RTL, and I made a new ticket for pre-existing examples of similar problems: https://unicode-org.atlassian.net/browse/CLDR-17846

**Comment by macchiati** [comment]
... is not winning

Is misleading alone. Better to give the root cause:

... requires TC approval to win

**Comment by btangmu** [comment]
> requires TC approval to win

@macchiati I've made that change (3rd commit)

**Comment by srl295** [comment]
> This screenshot illustrates the new reminder in the dialog for making a Request post:
> 
> > _… !! … examples of common usage…_

perfect opportunity to link to the guide from https://unicode-org.atlassian.net/browse/CLDR-17104 when available.

**Review by srl295 — APPROVED** [review]

**Pull request merged**
