### PR TITLE
CLDR-8383 CI against mysql, disrecommend derby

### PR DESCRIPTION
**Pull request by srl295**
CLDR-8383 

- allow web tests to take a JDBC URL, org.unicode.cldr.unittest.web.jdbcurl
- start mysql in github actions, set it up before test run

### CODE REVIEW

**Comment by srl295** [comment]
Travis will still test against derby…for now.

**Comment by srl295** [comment]
when derby support is removed, travis will no longer build, which will be fine per CLDR-11585 which was to obviate it anyway.

**Comment by srl295** [comment]
I've also updated the surveytool-is-broken messages to recommend mysql, and to have the Mysql Configurator button right there.

**Comment by srl295** [comment]
also, docs at .http://cldr.unicode.org/development/running-survey-tool/setup have been updated.

I think this is all done for the most part:  will be a followup PR when we actually remove Derby.

**Review by macchiati — APPROVED** [review]

**Pull request merged**
