### PR TITLE
CLDR-17830 BRS update subdivision translations

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17830

Adds names from wikidata. Note that some items disappear, because the codes were deprecated.

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by AEApple** [comment]
What leads some of these items to be provisional status, while the newer items have status contributed?

**Comment by macchiati** [comment]
I'll have to look into that.

**Comment by macchiati** [comment]
The documentation is basically to run the tool. It is run after we have
updated the subdivision codes (a separate step). Countries change their
codes all the time, and we don't really try to track that beyond keeping
the old codes in a deprecated list.

**Comment by macchiati** [comment]
Updated tooling to change the new values to provisional, for consistency.

**Comment by macchiati** [comment]
Ping, would like to merge this by EOD if possible

**Comment by AEApple** [comment]
any idea why so many island territories are being removed? Is that expected?

**Comment by btangmu** [comment]
> The documentation is basically to run the tool

Meaning WikiSubdivisionLanguages.java, I assume -- that wasn't obvious in the earlier version of this PR. I'll approve with a rubber stamp

**Review by btangmu — APPROVED** [review]

**Comment by macchiati** [comment]
Over the years, I've looked into some of the big revamps for various regions. Sometimes it is because of big revamps in governmental structures, sometimes just to make the codes match the actual governmental structures more clearly.

**Comment by macchiati** [comment]
Right, WikiSubdivisionLanguages.java. Sorry for being to terse.

**Pull request merged**
