### PR TITLE
CLDR-17202 kbd: add a Hiragana Flick keyboard

### PR DESCRIPTION
**Pull request by srl295**
CLDR-17202

- [ ] This PR completes the ticket.

Adds a simple 'flick' type Hiragana keyboard.

image

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
Not a lot of time but could I get a review to include this sample file with 45?

**Comment by srl295** [comment]
> the whitespace is a bit unwieldy, should probably be fixed
> 
> didn't check the Japanese but otherwise looks good to me

would you be able to approve the PR? 

It's perhaps excessively indented.

**Comment by miloush** [comment]
it's more about the indentation not corresponding to the level of the elements

**Review by miloush — APPROVED** [review]

**Comment by miloush** [comment]
image

**Pull request merged**
