### PR TITLE
CLDR-15662 LocaleCompletion (third) Meter fix missing count

### PR DESCRIPTION
**Pull request by btangmu**
-Do not assume hasError is true when addMissing needs to be called

-Test (hasError || statusMissing) instead of only hasError

-Fix a few warnings shown by IntelliJ

-Comments

CLDR-15662

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
Can you update the unit test also? TestLocaleCompletion

**Comment by btangmu** [comment]
@srl295 this draft pr points to a something, however I don't think it can be a full solution

further testing shows that we can get statusMissing == true, hasError == false, and results.size() == 0 at the point in question

locally, for French, dash has 159 missing; this pr changes locale completion from 2594 / 2595 to 2594 / 3123 -- increasing the difference from 1 to 529 ( = 2594 / 3123) -- that's a lot more than the 159 "Missing" per Dash, so what are the other 529 - 159 = 370?

the distinction between "missing" and "statusMissing" is mysterious...

seems like if LocaleCompletion.handleGetLocaleCompletion shared more code with VettingViewer.handleOnePath they would be more likely to be consistent -- as it stands they're both incredibly complicated and it would seemingly take a miracle for them to be consistent with each other; presumably VettingViewer.handleOnePath is currently the more accurate of the two

**Comment by btangmu** [comment]
> Can you update the unit test also? TestLocaleCompletion

there's a comment: "TODO Temporarily disabled for CLDR-15585, restore when data for es is fleshed out"

does it still need to be disabled, or has es been fleshed out? how would it get fleshed out?

**Comment by srl295** [comment]
> > Can you update the unit test also? TestLocaleCompletion
> 
> there's a comment: "TODO Temporarily disabled for [CLDR-15585](https://unicode-org.atlassian.net/browse/CLDR-15585), restore when data for es is fleshed out"
> 
> does it still need to be disabled, or has es been fleshed out? how would it get fleshed out?

Ouch. I thought that had to do with limited submission locales, let me check.

**Comment by srl295** [comment]
> > > Can you update the unit test also? TestLocaleCompletion
> > 
> > 
> > there's a comment: "TODO Temporarily disabled for [CLDR-15585](https://unicode-org.atlassian.net/browse/CLDR-15585), restore when data for es is fleshed out"
> > does it still need to be disabled, or has es been fleshed out? how would it get fleshed out?
> 
> Ouch. I thought that had to do with limited submission locales, let me check.

https://github.com/unicode-org/cldr/pull/2038 should re-enable this test.

**Pull request closed without merging**
