### PR TITLE
CLDR-17077 Fix some unit systems

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17077

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Rich, Peter, Dragan; we can hold off on this too, if it would affect the integration

**Comment by macchiati** [comment]
The updated results are in
* https://docs.google.com/spreadsheets/d/1wmlNKyQUyS-7oKGRoYown0LASozOvtoPx4qj9AvhBIg/edit#gid=1205825385
* https://docs.google.com/spreadsheets/d/1wmlNKyQUyS-7oKGRoYown0LASozOvtoPx4qj9AvhBIg/edit#gid=833794066

**Comment by macchiati** [comment]
Need to fix some example generation, so still draft

**Review by pedberg-icu — APPROVED** [review]

**Comment by richgillam** [comment]
Belated LGTM.  Thanks for making the fixes!

**Pull request merged**
