### PR TITLE
CLDR-15353 adjust PK language populations

### PR DESCRIPTION
**Pull request by DavidLRowe**
CLDR-15353

- [ ] This PR completes the ticket.

Outstanding request: renaming "lah" from "Lahnda" to "Western Punjabi"

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Figures updated in the XML file directly (rather than the raw .txt file). 

The order of some entries changed in order to keep the entries in decreasing order according to percentage of population.

No evidence for "tg_Arab" in PK, so Tajik (Arabic) entry removed.

**Review by macchiati — APPROVED** [review]
The changes look good. However, as for the language name change, those would revert if the file is reformatted. For 'lah', best is to change the language name in en.com.

**Comment by DavidLRowe** [comment]
@macchiati change in en.xml (rather than en.com)?

Should I add that to this PR?

**Comment by macchiati** [comment]
Yup, typo

**Comment by DavidLRowe** [comment]
The only change since the last review is that en.xml is now updated to use "Western Panjabi" for "lah".

**Review by macchiati — APPROVED** [review]

**Pull request merged**
