### PR TITLE
CLDR-15205 spec: add an anchor (anchor.js)

### PR DESCRIPTION
**Pull request by srl295**
- Use package anchor-js to add links to h2 and below

CLDR-15205

- [X] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
Note: due to the complication of how spec builds work [aka CLDR-15464 ] this won't be visible on merge.

I've done a side build at https://corp.unicode.org/~srloomis/tmp/dist13781/dist/tr35.html so it can be investigated.   The  tiny Javascript used is rolled up into `dist/js/anchor.min.js` so would be available alongside the normal release.

**Comment by srl295** [comment]
image

**Comment by macchiati** [comment]
I noticed that the structure (and appearance) is different for regular GFM format.

Here is https://github.com/unicode-org/cldr/blob/main/docs/ldml/tr35.md#Parts

<h2 dir="auto"><a id="user-content-parts" class="anchor" aria-hidden="true" href="#parts"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><a name="user-content-parts" href="#Parts">Parts</a></h2>

[It appears that much of the difference is the use of an svg icon. Maybe we could use the emoji link symbol instead of an image: 🔗 ]

And here is your doc:  https://corp.unicode.org/~srloomis/tmp/dist13781/dist/tr35.html#Parts

<h2 id="parts"><a name="Parts" href="#Parts">Parts</a>
<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="#parts" style="font: 1em / 1 anchorjs-icons; padding-left: 0.375em;"></a></h2>

I just want to make sure that we are using a "tried and true" way of doing this.

**Review by pedberg-icu — APPROVED** [review]

**Comment by macchiati** [comment]
I had some comments on this. I think we can go ahead and merge, and do
refinements after if needed.

**Pull request merged**
