### PR TITLE
CLDR-16339 Improve inheritance messaging

### PR DESCRIPTION
**Pull request by btangmu**
-Change [This item is inherited] to [This item is inherited from the ... locale]

-Change [This item is aliased from another location] to either [This item is inherited from another field in this locale] or [This item is inherited from another field in the ... locale]

-Rename with item_description_... instead of pClass_... for clarity

-Change styles of some Info Panel buttons to match other buttons (e.g., Dashboard)

-Make some hover titles more descriptive: Close the Info Panel, Reload the Info Panel, Explain inheritance for this item

-Link the Inheritance Explainer window to its button; add a Close button

CLDR-16339

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Can you put this up on cldr-staging so we can try it out?

**Comment by btangmu** [comment]
@macchiati @srl295 it's running on cldr-staging now

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
Probably want to hold off merging

**Review by srl295 — APPROVED** [review]

**Comment by btangmu** [comment]
I'll go ahead and merge now that you've both approved, and push to production already happened.

About my reversion of the button styles: I'm not at all attached to the old styles, and look forward to transitioning, as long as we aim for some consistency between elements shown simultaneously, like Info Panel and Dashboard close-boxes.

**Comment by srl295** [comment]
> I'll go ahead and merge now that you've both approved, and push to production already happened.

+1

> About my reversion of the button styles: I'm not at all attached to the old styles, and look forward to transitioning, as long as we aim for some consistency between elements shown simultaneously, like Info Panel and Dashboard close-boxes.

don't have an opinion here

**Pull request merged**
