### PR TITLE
CLDR-14276 update ckb single character + add locale tags

### PR DESCRIPTION
**Pull request by layik**
[CLDR-14276](https://unicode-org.atlassian.net/browse/CLDR-14276)

- [x] This PR completes the ticket. I have addressed all bits mentioned in this [comment](https://unicode-org.atlassian.net/browse/CLDR-14276?focusedCommentId=165044) by @DavidLRowe 

Related (closed) PR was #823 by @jwtiyar. Note for @jwtiyar: the characters you have mentioned in the #823 only h-doucheshme needed replacing. David's suggestions is the bulk of this PR.

[CLDR-14276]: https://unicode-org.atlassian.net/browse/CLDR-14276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by srl295** [comment]
@layik can you sign the CLA by clicking here please <https://cla-assistant.io/unicode-org/cldr?pullRequest=2412> thanks!

**Comment by layik** [comment]
Done @srl295.

**Comment by layik** [comment]
For the sake of completeness, I dug up CLDR-5645 which argues for the opposite of current PR. 

Since then, the only side which opposes current PR being Kurdish Wikipedia administrators, at least one of them, has switched position. In any case, there is a [consensus](http://unicode.ekrg.org/) accepted by KRG. Therefore, current PR should stand.

**Comment by layik** [comment]
ping!

**Comment by macchiati** [comment]
Question: the ticket mentions 3 characters. 
a. ه = U+0647 (This one become ھ when typed with another character).
b. ە = U+06D5
c. ک = U+06A9

The main change I see is to replace ھ by  ە in the main set and the index set, because ە and ک are already present.

Note that ه will need to be removed from the auxiliary set, because those shouldn't overlap.

Other changes to get to Basic look reasonable.

**Comment by layik** [comment]
Dear Mark @macchiati. Thank you for taking time and question/note. I shall refresh my memory/look closely, and 
> that ه will need to be removed from the auxiliary set, because those shouldn't overlap.

Will commit and update this PR asap. cc @jwtiyar.

**Comment by DavidLRowe** [comment]
@layik Currently you have removed U+06BE from the main exemplar and added U+0647.
- As @macchiati noted, U+0647 needs to be removed from the auxiliary exemplar (so that there is no overlap between the main and auxiliary exemplars)
- Do you need to add U+06BE to the auxiliary exemplar? That is, might this character appear in a non-Kurdish word included in a Kurdish text, for example?
- For the dates/timeZoneNames/gmtFormat item, should there be a space between `{0}` and `گرینیچ` ?

Thanks for your work on this contribution.

**Comment by layik** [comment]
OK updated branch and open on my dev env. 

Thank you @DavidLRowe. So far this is my "clear" understanding hence following this comment by a commit.

1. I removed U+0647 from auxiliary and replaced it with your suggestion of U+06BE
2. I added a space between گرینیچ and the placeholder.

Anything else?

Kind regards

**Review by DavidLRowe — DISMISSED** [review]
LGTM

**Comment by DavidLRowe** [comment]
@layik If you click on the "Details" link to the right of the "single-commit" check, you should have the option to "Squash branch". This will rewrite your branch with a single commit that incorporates all the changes of the individual commits in the pull request. This new commit must begin with the CLDR ticket number (to satisfy the jira-ticket check), so make sure the commit message is something like `CLDR-14276 update ckb single character + add locale tags` (as in the title).

Once you've done that, I can start the checks again and everything should pass. Thanks!

**Comment by layik** [comment]
Done @DavidLRowe :) Looks scary with " Layik dismissed ..." log.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
Thanks for your perseverance!

**Comment by jwtiyar** [comment]
> Done @DavidLRowe :) Looks scary with " Layik dismissed ..." log.

Well done kak @layik .

**Comment by layik** [comment]
Thank you @macchiati, @DavidLRowe and kake @jwtiyar

**Pull request merged**
