### PR TITLE
CLDR-16051 tzdata 2022d updates

### PR DESCRIPTION
**Pull request by yumaoka**
CLDR-16051

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by pedberg-icu** [comment]
There are 36 TestPathHeadersAndValues  test failures like
```
2022-09-29T22:26:55.7715240Z     TestPathHeadersAndValues
2022-09-29T22:26:55.7724570Z ##[error] (TestPaths.java:169)  Error: Locale: br,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Uzhgorod"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:26:55.7913497Z ##[error] (TestPaths.java:169)  Error: Locale: br,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:26:56.2207710Z ##[error] (TestPaths.java:169)  Error: Locale: br_FR,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Uzhgorod"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:26:56.2303924Z ##[error] (TestPaths.java:169)  Error: Locale: br_FR,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:26:59.5837230Z ##[error] (TestPaths.java:169)  Error: Locale: ceb,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Uzhgorod"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:26:59.5938570Z ##[error] (TestPaths.java:169)  Error: Locale: ceb,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:26:59.7190260Z ##[error] (TestPaths.java:169)  Error: Locale: ceb_PH,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Uzhgorod"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:26:59.7291345Z ##[error] (TestPaths.java:169)  Error: Locale: ceb_PH,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:27:02.1811424Z ##[error] (TestPaths.java:169)  Error: Locale: cy,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:27:02.5464468Z ##[error] (TestPaths.java:169)  Error: Locale: cy_GB,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:27:10.2114094Z ##[error] (TestPaths.java:169)  Error: Locale: en_AU,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:27:11.6395135Z ##[error] (TestPaths.java:169)  Error: Locale: en_CA,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:27:16.2176823Z ##[error] (TestPaths.java:169)  Error: Locale: en_IN,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
...
2022-09-29T22:29:09.0309768Z ##[error] (TestPaths.java:169)  Error: Locale: yo,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Uzhgorod"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:29:09.0417448Z ##[error] (TestPaths.java:169)  Error: Locale: yo,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:29:09.1919419Z ##[error] (TestPaths.java:169)  Error: Locale: yo_BJ,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Uzhgorod"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:29:09.2014432Z ##[error] (TestPaths.java:169)  Error: Locale: yo_BJ,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:29:09.3206675Z ##[error] (TestPaths.java:169)  Error: Locale: yo_NG,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Uzhgorod"]/exemplarCity,	 IsExtraPath: false
2022-09-29T22:29:09.3298731Z ##[error] (TestPaths.java:169)  Error: Locale: yo_NG,	 Value=null, 	Path: //ldml/dates/timeZoneNames/zone[@type="Europe/Zaporozhye"]/exemplarCity,	 IsExtraPath: false
```

I wonder whether the exemplarCity values for  Europe/Uzhgorod and Europe/Zaporozhye in various locales need to be deleted.

**Comment by yumaoka** [comment]
Oh.. `mvn verify` does not cover this test path/case.

>I wonder whether the exemplarCity values for Europe/Uzhgorod and Europe/Zaporozhye in various locales need to be deleted.

I wanted to avoid this - this is really "deprecating" zone. The problem is that ZoneParser seems to rely on zone.tab. I think patching zone.tab to include these two zones will eliminate all issues. I'll also look at ZoneParser that collect available zones from zone.tab to include out of list zones.

**Comment by yumaoka** [comment]
@pedberg-icu I took a different approach to handle these two zones. I added these two zones to the list generated from tz data file `zone.tab`. By doing so, all test passed without special casing these two exemplar cities.

**Review by markusicu — APPROVED** [review]
lgtm FWIW

**Review by pedberg-icu — APPROVED** [review]

**Comment by pedberg-icu** [comment]
> @pedberg-icu I took a different approach to handle these two zones. I added these two zones to the list generated from tz data file `zone.tab`. By doing so, all test passed without special casing these two exemplar cities.

Thanks, that seems good to me.

**Comment by pedberg-icu** [comment]
I am going to go ahead and merge this, hope that is OK

**Pull request merged**
