### PR TITLE
CLDR-15034 super basic keyboard charts

### PR DESCRIPTION
**Pull request by srl295**
CLDR-15034

- [ ] This PR completes the ticket.

image

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
i posted it up live https://www.unicode.org/~srloomis/tmp/kbd-chart/

**Comment by miloush** [comment]
Maybe use different colors for gap?

I think we should also have a SGCaps keyboard amongst simple examples.

**Comment by DavidLRowe** [comment]
For the AZERTY keyboard, shift layer, the key to the left of the "1" is empty. On the chart the key disappears and the remaining keys on the top row are shifted left. (But the Tab and CapsLock keys aren't there either, so maybe this isn't relevant to this stage in the charts.)

**Comment by srl295** [comment]
> Maybe use different colors for gap?

good idea. 

> I think we should also have a SGCaps keyboard amongst simple examples.

what is SGCaps?

**Comment by miloush** [comment]
Keyboard like Czech or [S]wiss [G]erman for which Shift keys are not the same as Caps keys: https://kbdlayout.info/features/SGCAPS. But maybe it's not that important, it's like 5% of keyboard in Windows that use it, it just wasn't obvious from the examples how this is solved.

**Comment by srl295** [comment]
> For the AZERTY keyboard, shift layer, the key to the left of the "1" is empty. On the chart the key disappears and the remaining keys on the top row are shifted left. (But the Tab and CapsLock keys aren't there either, so maybe this isn't relevant to this stage in the charts.)

Good catch.

Actually, there's no key there in the layout file. But looking at some screenshots, I think it's a bug and there should be a gap there… or perhaps the superscript-2 is repeated in the unshifted layer.

Anyway the chart is accurate, in fact helpful in spotting the issue!

**Comment by srl295** [comment]
> Keyboards like Czech or [S]wiss [G]erman for which Shift keys are not the same as Caps keys: https://kbdlayout.info/features/SGCAPS. But maybe it's not that important, it's like 5% of keyboard in Windows that use it, it just wasn't obvious from the examples how this is solved.

got it… filed https://unicode-org.atlassian.net/browse/CLDR-16653

**Comment by DavidLRowe** [comment]
On a standard AZERTY layout, the key above the Tab key produces a superscript 2 on the unshifted layer and nothing on the shifted layer. Do you have a way to represent a key that does nothing?!

**Comment by srl295** [comment]
> 

yes, it would be a gap.

**Comment by srl295** [comment]
Charts are now auto generated and pushed… https://cldr-smoke.unicode.org/spec/keyboard-preview/charts/keyboard/static/

Yes, i'm fixing the encoding issue, so embarassing 🙈

**Comment by macchiati** [comment]
Best to have the cells have a constant width, with the actual character in
them. The name can be in a mouse-hover. A bit larger font also. Agree about
different color for the gap.

**Comment by srl295** [comment]
> Best to have the cells have a constant width, with the actual character in them. The name can be in a mouse-hover. A bit larger font also. Agree about different color for the gap.
> […](#)

All done except for the font size and width. I'll capture that.

**Comment by mcdurdin** [comment]
> for which Shift keys are not the same as Caps keys

I think this is a special case of a more general issue -- Shift is not the same as Caps for English either, e.g. punctuation and digits. I think that separate Caps and Shift layers solves both of these.

**Pull request merged**
