### PR TITLE
CLDR-16039 add lmo

### PR DESCRIPTION
**Pull request by DavidLRowe**
CLDR-16039

- [X] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
```diff
diff --git a/common/supplemental/supplementalMetadata.xml b/common/supplemental/supplementalMetadata.xml
index 064239d81b..24a0583ea3 100644
--- a/common/supplemental/supplementalMetadata.xml
+++ b/common/supplemental/supplementalMetadata.xml
@@ -1819,6 +1819,7 @@ For terms of use, see http://www.unicode.org/copyright.html
                        kk_KZ kkj_CM kl_GL kln_KE km_KH kn_IN ko_KR kok_IN kpe_LR ks_Arab ks_Arab_IN
                        ks_Deva_IN ksb_TZ ksf_CM ksh_DE ku_TR kw_GB ky_KG
                        la_VA lag_TZ lb_LU lg_UG lij_IT lkt_US ln_CD lo_LA lrc_IR lt_LT lu_CD luo_KE
+                       lmo_IT
                        luy_KE lv_LV
                        mai_IN mas_KE mdf_RU mer_KE mfe_MU mg_MG mgh_MZ mgo_CM mi_NZ mk_MK ml_IN mn_MN
                        mn_Mong_CN mni_Beng mni_Beng_IN mni_Mtei_IN moh_CA mr_IN ms_Arab_MY ms_MY mt_MT
```

but this is a generated file, if i recall…

**Comment by DavidLRowe** [comment]
@srl295 Do I need to wait until the revisions to the tests are available in main?

**Comment by srl295** [comment]
> ```diff
> ```diff
> diff --git a/common/supplemental/supplementalMetadata.xml b/common/supplemental/supplementalMetadata.xml
> index 064239d81b..24a0583ea3 100644
> --- a/common/supplemental/supplementalMetadata.xml
> +++ b/common/supplemental/supplementalMetadata.xml
> @@ -1819,6 +1819,7 @@ For terms of use, see http://www.unicode.org/copyright.html
>                         kk_KZ kkj_CM kl_GL kln_KE km_KH kn_IN ko_KR kok_IN kpe_LR ks_Arab ks_Arab_IN
>                         ks_Deva_IN ksb_TZ ksf_CM ksh_DE ku_TR kw_GB ky_KG
>                         la_VA lag_TZ lb_LU lg_UG lij_IT lkt_US ln_CD lo_LA lrc_IR lt_LT lu_CD luo_KE
> +                       lmo_IT
>                         luy_KE lv_LV
>                         mai_IN mas_KE mdf_RU mer_KE mfe_MU mg_MG mgh_MZ mgo_CM mi_NZ mk_MK ml_IN mn_MN
>                         mn_Mong_CN mni_Beng mni_Beng_IN mni_Mtei_IN moh_CA mr_IN ms_Arab_MY ms_MY mt_MT
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> but this is a generated file, if i recall…
> ```

@DavidLRowe  `GenerateMaximalLocales` on your branch will add lmo_IT to defaultContent… so i think it's a safe change to make. (It makes other changes which are manually backed out).

**Comment by srl295** [comment]
> @srl295 Do I need to wait until the revisions to the tests are available in main?

no. 

go ahead and aply the patch i showed above and this should pass and be ready for commit

**Comment by DavidLRowe** [comment]
Summary of changes: 
Add new files: lmo.xml, lmo_IT.xml
In attributeValueValidity.xml, add lmo to variable id='$language' element 
In coverageLevels.xml, modify the regex in coverageVariable key=%language80 element to include lmo
In supplementalData.xml add territories="IT" to language type="lmo" element
In supplementalMetadata.xml, add "lmo_IT" to defaultContent element

**Comment by DavidLRowe** [comment]
@srl295 ready for your review, at your convenience.

**Review by srl295 — APPROVED** [review]

**Pull request merged**
