### PR TITLE
CLDR-16115 TZ Database 2022f updates

### PR DESCRIPTION
**Pull request by yumaoka**
CLDR-16115

- [x] This PR completes the ticket.

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
LGTM

has it been a while since CLDR updated its copy of tzdb?

**Comment by srl295** [comment]
any reason this should be in 42 maint also?

**Review by pedberg-icu — APPROVED** [review]

**Review by markusicu — APPROVED** [review]
lgtm tnx!

**Comment by pedberg-icu** [comment]
> any reason this should be in 42 maint also?

Sounds like a good topic for the CLDR meeting tomorrow

**Comment by yumaoka** [comment]
> has it been a while since CLDR updated its copy of tzdb?

No, I updated it about a month ago. There are big diff between 2022e and 2022f. TZ database maintainer no longer define one zone rule per country - instead, many of them were changed to Link to another zone, and moved to backward.

**Pull request merged**
