### PR TITLE
CLDR-14884 add ajp S. Levantine Arabic

### PR DESCRIPTION
**Pull request by DavidLRowe**
CLDR-14884

- [X] This PR completes the ticket.

### CODE REVIEW

**Comment by DavidLRowe** [comment]
@srl295 Tell me more about "ars". Is that an alias somewhere?

@pedberg-icu If you think there are issues to resolve with this pull request, perhaps it would be better to close it. Because I end up modifying %language80 for each addition, I end up submitting these PRs one by one, waiting for one to be merged before submitting the next.

**Comment by srl295** [comment]
> @srl295 Tell me more about "ars". Is that an alias somewhere?

not that i could find. @pedberg-icu can you expand?

> @pedberg-icu If you think there are issues to resolve with this pull request, perhaps it would be better to close it. Because I end up modifying %language80 for each addition, I end up submitting these PRs one by one, waiting for one to be merged before submitting the next.

On that point, can you find the ticket where we talked about _not_ needing to bump %language80 every time?

**Comment by pedberg-icu** [comment]
> > @srl295 Tell me more about "ars". Is that an alias somewhere?
> 
> not that i could find. @pedberg-icu can you expand?

The alias is in the CLDR-ICU conversion tooling, so that does not help CLDR (though I suppose one thing tha should be done in CLDR is add an entry to parentLocales in supplementalData). The things that we *do* have in CLDR for ars are:
- code listed in attributeValeValidity $languageExceptions, display name in moden coverage and in English, so we get the display name
- it is in likelySubtags.xml
- it is in plurals.xml (shoes rules with ar)
- it is in languageData in supplementalData, and we also have territoryInfo data for it.

> > @pedberg-icu If you think there are issues to resolve with this pull request, perhaps it would be better to close it. Because I end up modifying %language80 for each addition, I end up submitting these PRs one by one, waiting for one to be merged before submitting the next.

Yes, I think it would be better to close this one.

**Comment by srl295** [comment]
> > > @srl295 Tell me more about "ars". Is that an alias somewhere?
> > 
> > 
> > not that i could find. @pedberg-icu can you expand?
> 
> The alias is in the CLDR-ICU conversion tooling, so that does not help CLDR (though I suppose one thing that should be done in CLDR is add an entry to parentLocales in supplementalData). 

In my opionion: yes, that should be in CLDR, and remove that mapping data from ICU, other than the request to add the locale.

>The things that we _do_ have in CLDR for ars are:
> 
> * code listed in attributeValeValidity $languageExceptions, display name in moden coverage and in English, so we get the display name
> * it is in likelySubtags.xml
> * it is in plurals.xml (shoes rules with ar)
> * it is in languageData in supplementalData, and we also have territoryInfo data for it.
> 
> > > @pedberg-icu If you think there are issues to resolve with this pull request, perhaps it would be better to close it. Because I end up modifying %language80 for each addition, I end up submitting these PRs one by one, waiting for one to be merged before submitting the next.
> 
> Yes, I think it would be better to close this one.

**Pull request closed without merging**
