### PR TITLE
CLDR-14634 adjust hebrew plural rules (reformatted)

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-14634

Neglected to reformat after the change. Cleaner to do it on this ticket.

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by AEApple** [comment]
I don't understand why this is impacting day periods? I thought this was just about plurals? Could we consider doing the day periods as part of a separate ticket/PR?

**Review by AEApple — CHANGES_REQUESTED** [review]
Please separate out the Marathi day period changes into a separate PR for better tracking if possible. Thank you!

**Comment by macchiati** [comment]
My mistake; didn't switch to main before creating a branch, so this is
branching from the Marathi PR. Once that is merged I'll rebase.

**Comment by AEApple** [comment]
> My mistake; didn't switch to main before creating a branch, so this is branching from the Marathi PR. Once that is merged I'll rebase.

Great!

**Review by AEApple — APPROVED** [review]

**Pull request merged**
