### PR TITLE
CLDR-14736 add bal and bal_Latn locales

### PR DESCRIPTION
**Pull request by DavidLRowe**
CLDR-14736

- [ ] This PR completes the ticket.

It's possible that this PR completes the ticket, but there may be one other item that should change.
- Currently common/supplemental/likelySubtags.xml contains an entry for 'bal', but not one for 'bal_Latn'. But the data in likelySubtags.xml is generated from another source, so potentially another change is needed.

### CODE REVIEW

**Comment by srl295** [comment]
@DavidLRowe 
```
      Error: (TestCLDRFile.java:720) Can only one have 1 instance of bal in main, but have in [seed, exemplars]
```

you probably need to remove `bal.xml` from exemplars (make sure it doen'st have any extra information we need to keep!

**Comment by DavidLRowe** [comment]
@srl295 Thanks! A quick look indicates that exemplars/main/bal.xml doesn't have anything that isn't in the new files. So, I can delete that file, but there's a "one commit" requirement, so I'll need some git command to combine the new commit with the existing one. I know in theory that this is possible, but have never done it. What do you suggest? Is this written up in some CLDR workflow document?

**Comment by srl295** [comment]
@DavidLRowe if you click 'details' under the single-commit check (whether it is passing or failing) there's a 'Squash branch' button that will do that combine for you.

**Comment by srl295** [comment]
@DavidLRowe https://github.com/unicode-org/cldr/blob/master/CONTRIBUTING.md#requirements-for-merged-prs but doesn't tell you how to do the squash. Can you file a ticket asking for more documentation?

**Comment by srl295** [comment]
@DavidLRowe see if my #1267 ticket helps at all?

**Comment by DavidLRowe** [comment]
@macchiati Obviously there's something I don't understand. This PR is failing with:
Error: (TestInheritance.java:306) Script should not be empty in default content for: bal,bal_PK
Error: (TestInheritance.java:306) Region should be empty in default content for: bal,bal_PK
Error: (TestInheritance.java:306) Missing default content for: bal_PK
Error: (TestInheritance.java:326) Unexpected parent locale for locale bal_Latn. Expected: root Got: bal

Is this test looking at the identity block? or something else?

bal.xml
```
<identity>
	<version number="$Revision$"/>
	<language type="bal"/>
</identity>
```

bal_PK.xml
```
<identity>
	<version number="$Revision$"/>
	<language type="bal"/>
	<territory type="PK"/>
</identity>
```

bal_Latn.xml
```
<identity>
	<version number="$Revision$"/>
	<language type="bal"/>
	<script type="Latn"/>
</identity>
```

bal_Latn_PK.xml
```
<identity>
	<version number="$Revision$"/>
	<language type="bal"/>
	<script type="Latn"/>
	<territory type="PK"/>
</identity>
```

**Comment by srl295** [comment]
@DavidLRowe I'm wondering if it's looking for `bal_Arab_PK` which is what is in likely subtags?

**Comment by macchiati** [comment]
With very few exceptions, when a language is commonly written in 2+
scripts, you need a fully fleshed out tree. Example:

zh_Hans_CN.xml
zh_Hans_HK.xml
zh_Hans_MO.xml
zh_Hans_SG.xml
zh_Hans.xml
zh_Hant_HK.xml
zh_Hant_MO.xml
zh_Hant_TW.xml
zh_Hant.xml
zh.xml

Otherwise the tests will fail.

(Not your fault for not getting this. This is one of the things that needs
to go in updated documentation, since we don't have a single person doing
this anymore)
Mark

**Comment by DavidLRowe** [comment]
I'm going to close this PR and start a new one.

**Pull request closed without merging**
