### PR TITLE
CLDR-16650 Cherry-pick v43.1 maint/maint43 fixes to main branch, part 1

### PR DESCRIPTION
**Pull request by pedberg-icu**
CLDR-16650

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true
DISABLE_JIRA_ISSUE_MATCH=true

**Note: This needs to be merged using a _merge commit_ (must be temporarily enabled in settings), _not_ the normal _squash and merge_.**

Merge the 4 CLDR 43.1 commits on maint/maint-43 branch (so far) back to main.

### CODE REVIEW

**Comment by pedberg-icu** [comment]
> @pedberg-icu probably need to run spotless.

@srl295 Where is documentation on how to run spotless? I have not done that before. Thanks!

**Comment by srl295** [comment]
> > @pedberg-icu probably need to run spotless.
> 
> @srl295 Where is documentation on how to run spotless? I have not done that before. Thanks!

https://github.com/unicode-org/cldr/blob/main/tools/README.md#spotless

Just run `mvn --file=tools/pom.xml spotless:apply` from the command line

**Review by srl295 — DISMISSED** [review]
RSLGTM

**Comment by pedberg-icu** [comment]
> Just run `mvn --file=tools/pom.xml spotless:apply` from the command line

@srl295 Thanks! That seems to have made the verifier happy (the chnages were pretty minor!). Needs a re-stamp, thanks.

**Comment by pedberg-icu** [comment]
@srl295 @macchiati @AEApple ping

**Pull request merged**
