### PR TITLE
CLDR-16929 promotion: skip some items for ie and prg

### PR DESCRIPTION
**Pull request by srl295**
- see CLDR-16381 for detailed discussion

CLDR-16929

- [ ] This PR completes the ticket.

@macchiati  see CLDR-16381 comments - I think these are in error and should  be skipped from preventing promotion:

```
CLDR-16381: Skipping ie / ⓒ country_data
CLDR-16381: Skipping ie / ⓒ likely_subtags
CLDR-16381: Skipping ie / ⓑ own_regions
CLDR-16381: Skipping ie / ⓒ time_cycle
CLDR-16381: Skipping prg / ⓒ country_data
CLDR-16381: Skipping prg / ⓒ likely_subtags
CLDR-16381: Skipping prg / ⓑ own_regions
CLDR-16381: Skipping prg / ⓒ time_cycle
```

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — CHANGES_REQUESTED** [review]
I disagree. If we can't supply core data for these locales, we should remove them.

**Comment by srl295** [comment]
> I disagree. If we can't supply core data for these locales, we should remove them.

I think there is Core data, it's just being interpreted differently… Let's discuss. I meant to make this draft.

**Comment by srl295** [comment]
> I disagree. If we can't supply core data for these locales, we should remove them.

prg has core data: likely territory 001 which has hour data. It also has translation for 001.

**Comment by srl295** [comment]
I'm going to abandon this PR and fix `prg` and `ie` per TC discussion

**Pull request closed without merging**
