### PR TITLE
CLDR-9996 Add 7 new graphics units, with translation hints

### PR DESCRIPTION
**Pull request by pedberg-icu**
Add 7 new graphics units (e.g. em, pixel, pixel-per-inch, dot-per-inch) per
[CLDR-9996](https://unicode-org.atlassian.net/browse/CLDR-9996) Add units for pixels , ems, and display resolution
and proposal
[Units: pixels, ems, display resolution](https://sites.google.com/site/cldr/development/development-process/design-proposals/units-pixels-ems-display-resolution)
with translation hints.

### CODE REVIEW

**Comment by macchiati** [comment]
Can you check something? I think right now, whenever we have the X-per-Y
unit, we have both X as a unit and Y as a unit. For consistency, I think we
want to add

<unit type="graphics-dot">

Mark

**Comment by macchiati** [comment]
Can you check something? I think right now, whenever we have the X-per-Y unit, we have both X as a unit and Y as a unit. For consistency, I think we want to add 

<unit type="graphics-dot">

**Comment by sffc** [comment]
> I think right now, whenever we have the X-per-Y unit, we have both X as a unit and Y as a unit.

That would be a nice, but there are cases where we do not obey that invariant.  Examples:

- `liter-per-100kilometers`
- `meter-per-second-squared`

**Comment by pedberg-icu** [comment]
> Can you check something? I think right now, whenever we have the X-per-Y unit, we have both X as a unit and Y as a unit.

As Shane pointed out, we do not always do that. And I have not seen any interest in having "dot" as a unit, I only saw interest in dot-per-length as a resolution.

**Comment by pedberg-icu** [comment]
> Can you also update tr35-general.html? Also please add it as a diff to tr35.html.

I was planning to do that under a separate PR. Rick is updating tr-35 today and I did not want to get in his way (e.g. forcing a rebase) since this is his first time using git...

**Comment by macchiati** [comment]
Ok, we can go with that.

Mark

**Pull request merged**
