### PR TITLE
CLDR-14074 Update annotations for existing locales

### PR DESCRIPTION
**Pull request by andrew-z**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-_____
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by andrew-z** [comment]
Just draft PR for sharing, not for review yet

**Comment by andrew-z** [comment]
@macchiati @Kristi27 
This PR draft is just to demonstrate the level and amount of changes I'm proposing to bring to existing locales. Please take a look at major languages here and let me hear your thoughts. There validation issues there which I haven't addressed fully yet.

**Comment by Kristi27** [comment]
@andrew-z Please update the description with the CLDR ticket number. Also, this ticket isn't accepted yet and we still need to discuss this one.

**Comment by Kristi27** [comment]
I hadn't realized that these are existing locales :) 
For existing, we need to first discuss/accept the jira ticket. Then, look at this PR.

**Comment by macchiati** [comment]
These need to be for later, and should be incorporated with bulk uploads, not PRs. It is worth working out the kinks here in terms of testing and diffing, but the diffing needs to be different; it shows as every line changed, which doesn't allow people to see what kinds of changes are going on.

**Comment by andrew-z** [comment]
@Kristi27 @macchiati Yep, got it. I was using this draft PR just to demonstrate the scale and quality of updates I'm proposing. Closing this for now.

**Pull request closed without merging**
