### PR TITLE
CLDR-16918 Keyboard LDML editorial

### PR DESCRIPTION
**Pull request by miloush**
These should be all editorial, before https://github.com/unicode-org/cldr/pull/3277

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
Thanks!

**Review by macchiati — APPROVED** [review]
Ok to merge, recognizing that there are many outstanding issues to resolve.

**Comment by srl295** [comment]
@miloush Uhoh!  please rebase this on main.  i should remove the `keyboard-preview` branch.

**Comment by miloush** [comment]
@srl295 had to create new branch for that - https://github.com/unicode-org/cldr/tree/keyboard-preview-janed has the same edits based on main. Should I make a PR to main or can you merge it into your PR or do you want me to do it on your fork?

**Comment by srl295** [comment]
> @srl295 had to create new branch for that - https://github.com/unicode-org/cldr/tree/keyboard-preview-janed has the same edits based on main. Should I make a PR to main or can you merge it into your PR or do you want me to do it on your fork?

you can make a PR against main,  make the PR and the commit start with `CLDR-15034 ` or one of your other PRs as appropriate

**Pull request closed without merging**
