### PR TITLE
CLDR-12003 hi inconsistent localization of Macao

### PR DESCRIPTION
**Pull request by stenshamn**
##### Checklist

- [x ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-12003
- [x ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
Looks good to me. Do you want me to merge, or should we wait for others?

**Comment by stenshamn** [comment]
> Looks good to me. Do you want me to merge, or should we wait for others?

I have nothing else, so unless @pedberg-icu objects, we can merge.

**Comment by macchiati** [comment]
Ok, Peter, you can go ahead and merge.

Mark

**Review by pedberg-icu — DISMISSED** [review]
Certainly no objection, approved & will merge

**Comment by pedberg-icu** [comment]
> Certainly no objection, approved & will merge

Actually, I noticed that this PR is tarfget for the master branch, not the maint/maint-39 branch. And if I try to re-target to the maint-39 branch it picks up all kinds of other changes. Did you create this PR against the maint-39 branch?

**Comment by stenshamn** [comment]
Closing this PR and starting over.

**Pull request closed without merging**
