### PR TITLE
CLDR-15151 Tag does not work for Push to Production

### PR DESCRIPTION
**Pull request by btangmu**
-Change the prompt from ...(main, hash, tag) to ...(hash: 40 hex digits)

CLDR-15151

- [x] This PR completes the ticket.

DISABLE_JIRA_ISSUE_MATCH=true

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
SGTM

**Comment by btangmu** [comment]
Oops I accidentally pushed to this branch instead of one for CLDR-15178 -- I'll fix it shortly

**Comment by btangmu** [comment]
@srl295 sorry i messed this up and need another review -- same as what you already approved but I accidentally made another commit and then reverted it

**Comment by srl295** [comment]
> @srl295 sorry i messed this up and need another review -- same as what you already approved but I accidentally made another commit and then reverted it

OK but this branch is still wrong, it's the `und` fix

**Comment by btangmu** [comment]
> > @srl295 sorry i messed this up and need another review -- same as what you already approved but I accidentally made another commit and then reverted it
> 
> OK but this branch is still wrong, it's the `und` fix

Too many tickets and branches today! I'll try to sort it all out!!

**Comment by srl295** [comment]
But see my comments on the "und" ticket.

**Comment by btangmu** [comment]
see https://github.com/unicode-org/cldr/pull/1611

**Pull request closed without merging**
