### PR TITLE
CLDR-8666 Report improvements

### PR DESCRIPTION
**Pull request by srl295**
- hide report response if not logged in
- summary ui with vetting

CLDR-8666

- [ ] This PR completes the ticket.

image

will add spreadsheet download tomorrow

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
image

**Comment by macchiati** [comment]
What we want is, for each locale, and for *each* report, is
its status (approved, ...), its votes: acceptable=3, unacceptable=2,
voters=3
So 4 columns per report. Can use abbreviated titles on the columns

**Comment by srl295** [comment]
> What we want is, for each locale, and for *each* report, 
> is its status (approved, ...), 

We have that, that's the second, third, fourth columns

> its votes: acceptable=3, unacceptable=2, voters=3 So 4 columns per report. Can use abbreviated titles on the columns

I only have totals now, but will split it out.

**Comment by macchiati** [comment]
I don't see that in your screen shots.

**Comment by srl295** [comment]
> I don't see that in your screen shots.

image

I've circled the table header, showing the "Numbers", "Datetime", and "Zones" columns.  
Each row is a different locale.

**Comment by macchiati** [comment]
What I see is:
LocaleNumbersDatetimeZonesOverall
as—Assamese
<https://cldr-smoke.unicode.org/cldr-apps/v?vap=buildup-keyword-arkansas#/as//>

 approved: notAcceptable

 approved: acceptable

 approved: notAcceptable   acceptable=1  unacceptable=2  totalVoters=1
That doesn't have the *per Report* vote counts.

**Comment by macchiati** [comment]
That's not *per report* counts. Per report would look like:

| Locale | Numbers | accept. | unaccept. | Datetime | accept. | unaccept. |
Zones | accept. | unaccept. |
| es | Approved | 3 | 2 | Missing | 0 | 2 | Missing | 1 | 2 |

**Comment by srl295** [comment]
> What I see is: LocaleNumbersDatetimeZonesOverall as—Assamese <https://cldr-smoke.unicode.org/cldr-apps/v?vap=buildup-keyword-arkansas#/as//> approved: notAcceptable approved: acceptable approved: notAcceptable acceptable=1 unacceptable=2 totalVoters=1 That doesn't have the *per Report* vote counts.

Sorry if my reply was broken up.  i was trying to reply differently to the clauses of your request:

- status of each report: done
- totals for each report: todo

**Comment by macchiati** [comment]
Ah, I understand.

**Comment by srl295** [comment]
see #2149 for more updates

**Pull request merged**
