### PR TITLE
CLDR-14952 v40 checkin common/main from SurveyTool

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14952

- [X] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
Splitting into multiple commits for review.

**Comment by srl295** [comment]
New:

 create mode 100644 common/annotations/dsb.xml
 create mode 100644 common/annotations/hsb.xml

**Review by pedberg-icu — APPROVED** [review]
Everything I have looked at seems reasonable. The test failures are probably easier to fix once the data is in xml. If we can temporarily ignore the test failures to enable merging the PR, I support doing that.

**Comment by srl295** [comment]
You can make a pr against my pr if you want.

**Comment by srl295** [comment]
https://github.com/unicode-org/cldr/actions/runs/1099406782 I'll take a pass at fixing this sometime this morning

**Comment by srl295** [comment]
- I did a re-export on top of latest master instead fo what’s in production (i.e. updated data / code ) there was no (zero) change in the output XML.  Whew.

- on a quick glance the errors seem straightforward to fix… they are all collision errors that should have been caught before.

**Comment by macchiati** [comment]
I agree with Peter. If there are a small number of failures, it is simplest to override the tests, and move everything into XML. That way people can more easily work on it. Can you do that?

**Pull request merged**
