### PR TITLE
CLDR-17298 Add parts per billion

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17298

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by richgillam — DISMISSED** [review]
LOKTM

**Comment by macchiati** [comment]
I think this should now fix the test failures (they work locally), so crossing my fingers and marking as ready for review

**Review by DraganBesevic — APPROVED** [review]

**Comment by macchiati** [comment]
Dragan previously approved, but there was a spotless error that I needed to fix. Can someone rubber stamp?

**Review by richgillam — APPROVED** [review]

**Review by te2687076-web — COMMENTED** [review]
macchiati:CLDR-17298-Add-parts-per-billion #5190 Fixes #5190

**Pull request merged**
