### PR TITLE
CLDR-6396 Combine seed and common

### PR DESCRIPTION
**Pull request by btangmu**
-Move all files from seed to common

-Add README.md in seed and its subdirectories

CLDR-6396

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
this pr proposes merger into a new feature branch CLDR-6396-combine-seed-common, **not** main

errors are expected; testing locally produced the following:
 Error summary:
CLDR/TestAttributeValues/TestValid
CLDR/TestBasic/TestCoreData
CLDR/TestBasic/TestCurrencyFallback
CLDR/TestCLDRFile/TestForStrayFiles
CLDR/TestCLDRLocaleCoverage/TestLanguageNameCoverage
CLDR/TestLocalCurrency/TestConsistency
CLDR/TestLocale/TestLanguageRegions
CLDR/TestPaths/TestPathHeadersAndValues
CLDR/TestSupplementalInfo/Test10765
CLDR/TestSupplementalInfo/TestDefaultScripts

<< 80 TEST(S) FAILED >>

**Review by srl295 — APPROVED** [review]
LGTM!!

I'd put a bug link in the readme so someone can follow the trail. But minor.

**Comment by btangmu** [comment]
> LGTM!!
> 
> I'd put a bug link in the readme so someone can follow the trail. But minor.

do you mean a link to this ticket? we could add that in a follow-up

**Comment by srl295** [comment]
I closed #589  as it has not had activity. i did not find other PRs that would be affected by this.

**Comment by btangmu** [comment]
> I closed #589 as it has not had activity. i did not find other PRs that would be affected by this.

thanks for checking that!

**Comment by srl295** [comment]
> > LGTM!!
> > I'd put a bug link in the readme so someone can follow the trail. But minor.
> 
> do you mean a link to this ticket? we could add that in a follow-up

Right.  low priority though.

**Comment by btangmu** [comment]
It looks like that PR would be straightforward to fix in terms of changing seed to common

**Pull request merged**
