### PR TITLE
CLDR-18136 Fix datetimeSkeleton typo in yue

### PR DESCRIPTION
**Pull request by sffc**
CLDR-18136

A typo originating in #4217 that I found after testing CLDR 46.1 BETA1 in ICU4X.

### CODE REVIEW

**Review by pedberg-icu — APPROVED** [review]

**Comment by sffc** [comment]
Thanks; does this need to be merged to a maintenance branch?

**Comment by AEApple** [comment]
Peter will cherrypick after the fix is merged in main.

**Comment by sffc** [comment]
> Peter will cherrypick after the fix is merged in main.

It is already merged in main.

**Comment by pedberg-icu** [comment]
I will cherry-pick over to maint/maint-46 today and then tag maint/maint-46 as release-46-1-beta3.

**Pull request merged**
