### PR TITLE
CLDR-14967 Raise error for missing formatting pattern characters

### PR DESCRIPTION
**Pull request by btangmu**
-Fix UnitPathType.getPathType to recognize durationUnit.../durationUnitPattern

CLDR-14967

- [x] This PR completes the ticket.

### CODE REVIEW

**Review by srl295 — APPROVED** [review]

**Comment by btangmu** [comment]
The change results in new data errors:
```
kab [Kabyle] error ▸Units|Duration|Duration_Patterns|hm◂ 〈h:mm〉 【】 〈r:dd〉 «=» 【】 ⁅invalid duration unit pattern⁆ ❮Error: The hour indicator should be either h or hh for duration.❯ https://st.unicode.org/cldr-apps/v#/kab//586299d2628a1573 

kab [Kabyle] error ▸Units|Duration|Duration_Patterns|hms◂ 〈h:mm:ss〉 【】 〈r:dd:nn〉 «=» 【】 ⁅invalid duration unit pattern⁆ ❮Error: The hour indicator should be either h or hh for duration.❯ https://st.unicode.org/cldr-apps/v#/kab//211f0bf0fe46eaa2 

kab [Kabyle] error ▸Units|Duration|Duration_Patterns|ms◂ 〈m:ss〉 【】 〈d:nn〉 «=» 【】 ⁅invalid duration unit pattern⁆ ❮Error: The minutes symbol (m or mm) is missing.❯ https://st.unicode.org/cldr-apps/v#/kab//2562c4aebc8b385b 

....

sd_Deva [Sindhi (Devanagari)] error ▸Units|Duration|Duration_Patterns|hm◂ 〈h:mm〉 【】 〈क:मिमि〉 «=» 【】 ⁅invalid duration unit pattern⁆ ❮Error: The hour indicator should be either h or hh for duration.❯ https://st.unicode.org/cldr-apps/v#/sd_Deva//586299d2628a1573 

sd_Deva [Sindhi (Devanagari)] error ▸Units|Duration|Duration_Patterns|hms◂ 〈h:mm:ss〉 【】 〈क:मिमि〉 «=» 【】 ⁅invalid duration unit pattern⁆ ❮Error: The hour indicator should be either h or hh for duration.❯ https://st.unicode.org/cldr-apps/v#/sd_Deva//211f0bf0fe46eaa2 

sd_Deva [Sindhi (Devanagari)] error ▸Units|Duration|Duration_Patterns|ms◂ 〈m:ss〉 【】 〈मि:सेसे〉 «=» 【】 ⁅invalid duration unit pattern⁆ ❮Error: The minutes symbol (m or mm) is missing.❯ https://st.unicode.org/cldr-apps/v#/sd_Deva//2562c4aebc8b385b 
```

 If they really are errors, then this code change should be committed, and then the data should be fixed.

**Comment by btangmu** [comment]
@srl295  thanks for merging!

**Comment by srl295** [comment]
@btangmu oof - i would have fixed those first.

I'll open a PR to fix these.

**Comment by srl295** [comment]
Please review #1423

**Pull request merged**
