### PR TITLE
CLDR-14379 Remove incorrect baseUnit for torque

### PR DESCRIPTION
**Pull request by hugovdm**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14379
- [X] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
Does what it says, but please change the PR title also

**Comment by hugovdm** [comment]
I have squashed. I think this PR would do well waiting for a confirmation from @macchiati too?

**Comment by hugovdm** [comment]
Draft status for a little while - I'm considering this a bit:

```
			<unit type="torque-newton-meter">
				<displayName>newton-meters</displayName>
				<unitPattern count="one">{0} newton-meter</unitPattern>
				<unitPattern count="other">{0} newton-meters</unitPattern>
			</unit>
```

I want to double check, but I think ICU will do the right thing despite the "torque" unit type being otherwise unknown to measunit_extra.cpp.

**Review by macchiati — APPROVED** [review]
Didn't know you were waiting on me.

**Comment by hugovdm** [comment]
Also waiting on https://unicode-org.atlassian.net/browse/CLDR-14379 (I'm not yet that familiar with CLDR's ticket process).

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
> Also waiting on https://unicode-org.atlassian.net/browse/CLDR-14379 acceptance (I'm not yet that familiar with CLDR's ticket process - CLDR meetings I assume).

I clicked on the jira checker and asked it to 'update status'. It doesn't do so automatically.

**Comment by hugovdm** [comment]
Merging. Thanks!

**Comment by hugovdm** [comment]
Actually no: I'm not authorized for CLDR - I need one of you to click the merge button. Thanks!

**Pull request merged**
