### PR TITLE
CLDR-17728 Rename "Palestinian territories" to "Palestine"

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
CLDR-17728

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
For the locale data, we do not intake data like this via PRs. If the ticket is approved, then the data would be handled by translators, via the survey tool.

**Comment by Jules-Bertholet** [comment]
@macchiati the data is already present for all these languages, just in the wrong place (as an alternative `"short"` name instead of the primary name). Does the survey tool have a mechanism for performing this bulk update? Or would we need to manually cut and paste the existing name for hundreds of languages?

**Comment by macchiati** [comment]
Ah, I looked again at the PR. Since the 'short' name is already supplied,
there isn't anything more to do. That is, the implementations using CLDR
can choose which they want.

**Comment by Jules-Bertholet** [comment]
> That is, the implementations using CLDR can choose which they want.

But, unless they choose to do additional work, they will use the long name by default. Also, the choice of primary name determines the name of the flag emoji (🇵🇸).

**Pull request closed without merging**
