### PR TITLE
CLDR-13038 tweak names to avoid collisions

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13038
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by macchiati** [comment]
Made a mistake and didn't branch off of master. Will wait for other to go through.

**Comment by Kristi27** [comment]
Mark, this is confusing. The name changes to avoid collision looks fine, but there are a number of other changes in this commit.

**Comment by macchiati** [comment]
Sorry for the confusion. I branched wrong, and it is including changes that will be in the master but aren't yet. So what I meant is that you can wait on the review til the other is merged.

**Comment by macchiati** [comment]
> You need to update CLDR's copy of emoji-test.txt to fix the test failures.

Ok, done.

**Comment by macchiati** [comment]
Closing this one to start afresh

**Pull request closed without merging**
