### PR TITLE
CLDR-13563 Add conjunction/disjunction rules for languages that have exceptions. 

### PR DESCRIPTION
**Pull request by younies**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13563
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by sffc** [comment]
@srl295 Are you onboard with putting this stuff in the spec text, as was the original CLDR proposal, or should we go back to the drawing board and design a data-based solution?

**Comment by macchiati** [comment]
The plan was (and is) to do spec changes now to indicate how
implementations can extend the format, then for a future version work on a
data-based solution. Added comments to the review.

Mark

**Comment by younies** [comment]
> 1. We need a lead-in that states that:
>    More sophisticated implementations can fine tune the results of list formatting. For example, for the following four cases: 1. As per discussion, we'd like all four languages
> 2. We don't need the "general rule"; that is already in the data. What we need to describe are the changes for special cases.
> 
> Easiest to do this first with a google doc to get the wording right, and then pour it into HTML.

I have just added the spec in this doc http://bit.ly/cldr-list-pattern-proposed-spec, which we can agree on the format before I am going to edit this pull request

**Comment by sffc** [comment]
I missed the CLDR meeting; do we have agreement on putting this locale data table in the spec?

If not, my preference would be to hack ICU 67 for Spanish only, since that's the language for the original issue.

**Comment by macchiati** [comment]
The committee didn't want to put binding rules in the spec, because it is
clear that other supported languages have similar issues (two were voiced
right off the bat). So it would be misleading to only require a couple. So
the table will be going in, but as *examples* of what implementations can
do, not binding. For the next release more information needs to be done,
and we need to consider a data-driven solution.

But for this release, ICU (or other clients) can put in all or some or none.

As far as ICU goes, we know how to fix both Spanish and Italian, so I
suggest that we add those. And if we get the info about Hebrew and Korean
very soon, they could also be added.

Mark

**Comment by sffc** [comment]
OK.

This is fine for the time being, but a "non-binding" spec solution is the
worst long-term outcome in my opinion, because it means that spec-compliant
implementations will not necessarily produce the same output, even if they
use the same data.  This is really important for ECMA-402 polyfills,
OmnICU, etc., in order to be consistent with ICU.

We should remove the wishy-washy text from the spec as soon as possible
(CLDR 38) and replace it with either hard text or data.

**Comment by macchiati** [comment]
I agree with you that we need that. This should just be temporary. We need
to do the work to make sure that we at least cover the to languages, and
come up with a MR data solution.

{phone}

**Comment by macchiati** [comment]
We need to do Spanish and Hebrew, but not italian (until its rules are settled)

**Pull request closed without merging**
