### PR TITLE
CLDR-15877 Add English name for bgc

### PR DESCRIPTION
**Pull request by AEApple**
CLDR-15877

Add English name for bgc

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by AEApple** [comment]
So neither bgc nor raj are at modern coverage. Should I add an the exception, or should we move both to modern and remove the exception for raj?

Also should we add a test so that if a locale is added as a TC org locale that we automatically add the locale name to modern since by adding the locale to locales.txt the TC org is signaling that they plan to bring the locale up to at least Basic coverage that cycle?

**Comment by pedberg-icu** [comment]
> So neither bgc nor raj are at modern coverage. Should I add an the exception, or should we move both to modern and remove the exception for raj?

I would say that in general we should add them both at modern coverage and remove the exceptions. However at the end of a release that will cause the coverage statistics for all CLDR languages to drop. So for 42 I think we add the exception, then file a separate ticket for 43 to put them both at modern coverage and remove the exception.

> Also should we add a test so that if a locale is added as a TC org locale that we automatically add the locale name to modern since by adding the locale to locales.txt the TC org is signaling that they plan to bring the locale up to at least Basic coverage that cycle?

Agree, also sounds like a se[arate ticket for 43.

**Comment by macchiati** [comment]
Agreed

**Review by pedberg-icu — APPROVED** [review]

**Comment by AEApple** [comment]
For future reference filed the following tickets:

- CLDR-15883 to add language names for bgc & raj in v43
- CLDR-15882 to consider adding tests against locales.txt to make sure locales listed by TC orgs have their language names covered at modern.

**Review by Maxxisthename — APPROVED** [review]

**Pull request merged**
