### PR TITLE
CLDR-15029 Rename unittest.TestUtilities to unittest.TestHelper

### PR DESCRIPTION
**Pull request by btangmu**
-Avoid confusion with util.TestUtilities

CLDR-15029

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by btangmu** [comment]
@srl295 This PR seems to be stuck on "license/cla Expected — Waiting for status to be reported"; any idea why or how to give it a nudge?

Also, @macchiati and @srl295 there turn out to be 11 more duplicate class/file names; please see my comment in the ticket for those: https://unicode-org.atlassian.net/browse/CLDR-15029

**Comment by srl295** [comment]
@btangmu the recheck URL is of this form: <https://cla-assistant.io/check/unicode-org/cldr?pullRequest=4035>

**Review by srl295 — APPROVED** [review]

**Comment by btangmu** [comment]
> the recheck URL ...

FYI I cheated by clicking on Details by "single-commit", then "Update github status"

**Comment by srl295** [comment]
> > the recheck URL ...
> 
> FYI I cheated by clicking on Details by "single-commit", then "Update github status"

that's the commit checker, not the CLA checker.

**Pull request merged**
