### PR TITLE
CLDR-13306 Generate disruptive data churn report

### PR DESCRIPTION
**Pull request by btangmu**
-This PR has only preliminary minor improvements and clean-up

-ChartDelta: report when finished and report file-creation directories

-Remove duplicate new PathDescription from ExampleGenerator.java

-Avoid deprecation warning for DtdData.getInstance; cache getCldrBaseDirectory as CLDR_BASE_DIR

-Refactor to obviate single-line getValueSplitter; call DtdData.getValueSplitter directly instead

-Remove dead/unused code from ChartDelta.java and Chart.java, make private where possible

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13306
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
This PR has only preliminary minor improvements and clean-up. It takes into account the discussions in https://github.com/unicode-org/cldr/pull/573

**Comment by btangmu** [comment]
> > This PR has only preliminary minor improvements and clean-up. It takes into account the discussions in #573
> 
> Cleanup LGTM but might be good to change the commit/PR title to reflect its state, since there's no "disruptive data churn report' generated by this commit…

I almost always use the title of the issue as the title of the PR, which is the default in github. Then I add details in the subsequent lines. This seems helpful for mentally associating the PR with the ticket. Is there a set of guidelines or best practices we should follow for this kind of thing?

**Comment by srl295** [comment]
> > > This PR has only preliminary minor improvements and clean-up. It takes into account the discussions in #573
> > 
> > 
> > Cleanup LGTM but might be good to change the commit/PR title to reflect its state, since there's no "disruptive data churn report' generated by this commit…
> 
> I almost always use the title of the issue as the title of the PR, which is the default in github. Then I add details in the subsequent lines. This seems helpful for mentally associating the PR with the ticket. Is there a set of guidelines or best practices we should follow for this kind of thing?

That's generally a good practice, my only point is that if the commit does NOT actually generate a disruptive churn report, the commit (and PR) could reflect that. Otherwise we will have this commit `CLDR-13306 Generate disruptive data churn report` that doesn't actually generate such a report. It's minor, but will add confusion later if we are trying to find which commit actually added that report.

I would suggest that the commit be named something like "cleanup ChartDelta and ExampleGenerator"?

**Comment by btangmu** [comment]
> I would suggest that the commit be named something like "cleanup ChartDelta and ExampleGenerator"?

OK, I'll do that. It means omitting the ticket name, so I have mixed feelings about it. Normally I have the ticket name as the first line of the commit (and PR) message, and leave it to subsequent lines to say what the commit actually does.

**Pull request closed without merging**
