### PR TITLE
CLDR-13862 Add length preference for usage focal-length

### PR DESCRIPTION
**Pull request by kipcole9**
Add unit preference category `length`, usage `focal-length`

### CODE REVIEW

**Comment by macchiati** [comment]
Added the ticket to the agenda for next week.

**Comment by macchiati** [comment]
Kip, you'll need to squash the ticket to fix the commit message before this can be merged.

**Comment by sffc** [comment]
@kipcole9 Are you planning on rewriting the commit message to CLDR format so we can merge this PR?

**Comment by kipcole9** [comment]
Apologies, I will Squash the commits in the next 24 hours.

**Comment by kipcole9** [comment]
Commits squash and I believe RTM.  Please advise is any other changes are required,

**Pull request merged**
