### PR TITLE
CLDR-14913 Add Download XML button to Survey Tool

### PR DESCRIPTION
**Pull request by btangmu**
-New back-end api/GenerateVxml.java, alternative to legacy admin-OutputAllFiles.jsp

-New front-end cldrGenerateVxml.mjs, GenerateVxml.vue

-Changes to OutputFileManager.java, support button/api as alternative to jsp

-Comments involving related VXML tickets

CLDR-14913

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by btangmu** [comment]
This still doesn't work correctly. The visual feedback isn't sufficient: it has a stop button, but says "Current status: WAITING" even while in progress. The browser never gets updated with the information that would get displayed using admin-OutputAllFiles.jsp...

**Comment by btangmu** [comment]
console check error not related to this PR/ticket:

Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.util.ConcurrentModificationException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5011)
	at org.unicode.cldr.test.TestCache.getBundle(TestCache.java:121)
	at org.unicode.cldr.test.ConsoleCheckCLDR.lambda$main$0(ConsoleCheckCLDR.java:627)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2739)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at org.unicode.cldr.test.CheckCLDR.setCldrFileToCheck(CheckCLDR.java:723)
	at org.unicode.cldr.test.TestCache$TestResultBundle.<init>(TestCache.java:45)
	at org.unicode.cldr.test.TestCache$1.load(TestCache.java:109)
	at org.unicode.cldr.test.TestCache$1.load(TestCache.java:105)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)

**Comment by macchiati** [comment]
Can you file a ticket for this? We don't want it to get lost, and we'll
need the ticket number anyway.

**Comment by btangmu** [comment]
> Can you file a ticket for this? We don't want it to get lost, and we'll need the ticket number anyway.

https://unicode-org.atlassian.net/browse/CLDR-17346

**Comment by btangmu** [comment]
This PR is outdated. Later PRs were merged, with most of the same changes or better.

**Pull request closed without merging**
