### PR TITLE
CLDR-15323 Fix fileutilities for Windows

### PR DESCRIPTION
**Pull request by Manishearth**
CLDR-15323

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by Manishearth** [comment]
@srl295 would it be possible to get a release that includes this so that unicodetools builds can work on Windows again?

**Comment by srl295** [comment]
> @srl295 would it be possible to get a release that includes this so that unicodetools builds can work on Windows again?

Can you write CLDR asking for this ticket to be assigned to you ? Otherwise tomorrow AM

**Review by srl295 — DISMISSED** [review]

**Comment by Manishearth** [comment]
> Can you write CLDR asking for this ticket to be assigned to you ? 

Not sure what you mean by writing CLDR, but I think you already assigned it to me. Either way, tomorrow is great for a release, I don't need this immediately (i'd just prefer to not carry around a bunch of hacks in my build 😄 )

**Comment by srl295** [comment]
Writing  the CLDR list.

I assigned it but it’s not accepted.

**Review by srl295 — APPROVED** [review]

**Comment by Manishearth** [comment]
Is there anything I need to wait for for this to get pulled in by Maven in Eclipse? Or something I need to press?

**Pull request merged**
