### PR TITLE
CLDR-14803 Rename "Dizzy Face" to "Face With X Eyes"

### PR DESCRIPTION
**Pull request by AEApple**
Rename 😵  U+1F635 DIZZY FACE to "Face With X Eyes"

CLDR-14803

- [x] This PR completes the ticket.

### CODE REVIEW

**Review by macchiati — CHANGES_REQUESTED** [review]
Let's hold off on this for a minute; I need to check the code points.

**Comment by srl295** [comment]
@AEApple also, if you click on the details of the failure it shows:

```
    TestNamesVsEmojiData {
241
      Error: (TestAnnotations.java:177) : 😵‍💫: expected "face with spiral eyes", got "face with X eyes"
242
```

**Comment by AEApple** [comment]
I thought the whole point was that the emoji was expected to have an updated name?

It does look like it aligns with the code point from what's listed in the issue description, unless there is another version? but the emoji looks different to me.

**Comment by srl295** [comment]
> I thought the whole point was that the emoji was expected to have an updated name?
> 
> It does look like it aligns with the code point from what's listed in the issue description, unless there is another version? but the emoji looks different to me.

The error message isn't very helpful. It should mention what the source code comment says:

```java
    /** The English name should line up with the emoji-test.txt file */
```

as to what to do with this information or how emoji-test.txt got there:   🤷

**Comment by macchiati** [comment]
The face that was requested for change was:'

 😵 	U+1F635	DIZZY FACE (this is the formal Unicode name, not the cldr name)

The face that was changed in the PR was the new dizzy face.

😵‍💫 	U+1F635, U+200D, U+1F4AB	DIZZY FACE, ZERO WIDTH JOINER, DIZZY SYMBOL

So, looking a the lines, it is the first two that are the right character for the ticket. However, we already have a cldr name for that, fixed earlier. So let me post a reply in the ticket, and take it up with the ESC.

<annotation cp="😵">dead | face | knocked out | knocked-out face</annotation>
<annotation cp="😵" type="tts">knocked-out face</annotation>
<annotation cp="😵‍💫">dizzy | face with spiral eyes | hypnotized | spiral | trouble | whoa</annotation> 
<annotation cp="😵‍💫" type="tts">face with spiral eyes</annotation>

**Comment by AEApple** [comment]
Sounds good!

**Pull request closed without merging**
