### PR TITLE
CLDR-17866 BRSv46 CLDRModify passes before alpha1

### PR DESCRIPTION
**Pull request by pedberg-icu**
CLDR-17866

- [x] This PR completes the ticket.

CLDRModify passes before alpha1:

1. With no arguments:
    * en_ZA, remove trailing space after element
    * he, replace entity ref for LRM with actual char
    * others, reorder entries (in annotations, specifically reorder entries for "₨", "﷼" due to collation updates)
2. With -fP: reformat/reorder exemplar & parseLenient sets, adjust literal quoting.

Note that the -fQ pass was explicitly skipped per Mark comment on previous CLDRModify PR: " I don't think we should add the tts names to the keywords, unless the keywords are empty, because it works against the guidance that people should break up the search keywords by word where possible...I suggest that we hold off adding the tts name, and just do the daip (which reorders)".

**Note: This should be merged with a Rebase merge (temporarily enable in Settings), not a Squash merge.**

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
I might need to rerun these for #3941

**Comment by AEApple** [comment]
Makes sense, but shouldn't we just approve and merge this one and then just do another CLDRModify pass if there are additional changes that need to be modified?

**Review by srl295 — APPROVED** [review]
RSLGTM

**Comment by srl295** [comment]
> Makes sense, but shouldn't we just approve and merge this one and then just do another CLDRModify pass if there are additional changes that need to be modified?

sorry, i had meant to approve this.

**Pull request merged**
