### PR TITLE
CLDR-16994 BRS: Run GenerateDtd

### PR DESCRIPTION
**Pull request by srl295**
CLDR-16994

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — CHANGES_REQUESTED** [review]
I don't recall ever getting a ticket to add xsd files for all of CLDR.

**Comment by srl295** [comment]
> I don't recall ever getting a ticket to add xsd files for all of CLDR.

CLDR-15990 TC approved oct 5 2022

**Review by macchiati — CHANGES_REQUESTED** [review]
As remarked in email, this is ok if the generation tool is revised to indicate in the header of each .xsd that the XSD files are in tech preview.

**Comment by srl295** [comment]
> As remarked in email, this is ok if the generation tool is revised to indicate in the header of each .xsd that the XSD files are in tech preview.

@macchiati can I do that in a PR connected to the XSD tool? This is just the BRS task.

**Comment by srl295** [comment]
> > As remarked in email, this is ok if the generation tool is revised to indicate in the header of each .xsd that the XSD files are in tech preview.
> 
> @macchiati can I do that in a PR connected to the XSD tool (a follow on to merged #3108)? This is just the BRS task re-running the tool once again.

nevermind… i guess I'd need to run the generator again anyway!

**Review by macchiati — APPROVED** [review]

**Pull request merged**
