### PR TITLE
CLDR-14010 Bulk replace http -> https

### PR DESCRIPTION
**Pull request by KOLANICH**
CLDR-14010

Bulk replace http -> https for the websites known supporting it using HTTPSEverywhere ruleset.

Was applied using https://github.com/KOLANICH-tools/https-everywhere-py/tree/bulk_replace tool (as a byproduct of debugging the tool).

Some human reviewing was done and some dead links were replaced with more alive analogues and some sites known to have https but that are not in the rulesets were also fixed in some places. Also for some files the changes have been reverted, mostly for the ones copyed from external sources.

CLA won't be signed, but you can consider the contribution as the one in public domain. Also it is likely that it is below the threshold of originality since it is a result of just applying the software and some mechanistic procedures.

Anyway, if you don't want to accept the PR, you can use the tool linked to make a your own PR.

### CODE REVIEW

**Comment by srl295** [comment]
@KOLANICH Interesting and good work! Comments:
- we'll ned a bug for the PR title and commit message
- Some files are external, automatically generated, etc. so may need to be excluded.

**Comment by srl295** [comment]
> CLA won't be signed, but you can consider the contribution as the one in public domain. Also it is likely that it is below the threshold of originality since it is a result of just applying the software and some mechanistic procedures.

Please consider signing the CLA so we can evaluate this contribution.

**Comment by KOLANICH** [comment]
>we'll ned a bug for the PR title and commit message

Could you create it for me?

>Some files are external, automatically generated, etc. so may need to be excluded.

I have tried to avoid them in manual checking phase. If you see the files in which fixes need to be reverted, please name them.

**Comment by srl295** [comment]
> > we'll ned a bug for the PR title and commit message
> 
> Could you create it for me?

<https://unicode-org.atlassian.net/browse/CLDR-14010>

(you can just write CLDR-14010 within the repo, it's linked)

> 
> > Some files are external, automatically generated, etc. so may need to be excluded.
> 
> I have tried to avoid them in manual checking phase. If you see the files in which fixes need to be reverted, please name them.

**Comment by KOLANICH** [comment]
>https://unicode-org.atlassian.net/browse/CLDR-14010
>(you can just write CLDR-14010 within the repo, it's linked)

Thanks. I have edited the head post.

>/docs/rfc is an IETF RFC and shouldn't be changed here
>anything in the /data/ subdirectory is mostly external data sources and should be left alone.

Thanks, I will fix that when I have time.

**Comment by srl295** [comment]
> > https://unicode-org.atlassian.net/browse/CLDR-14010
> > (you can just write CLDR-14010 within the repo, it's linked)
> 
> Thanks. I have edited the head post.
> 
> > /docs/rfc is an IETF RFC and shouldn't be changed here
> > anything in the /data/ subdirectory is mostly external data sources and should be left alone.
> 
> Thanks, I will fix that when I have time.



> > https://unicode-org.atlassian.net/browse/CLDR-14010
> > (you can just write CLDR-14010 within the repo, it's linked)
> 
> Thanks. I have edited the head post.

commit message needs to match

> 
> > /docs/rfc is an IETF RFC and shouldn't be changed here
> > anything in the /data/ subdirectory is mostly external data sources and should be left alone.
> 
> Thanks, I will fix that when I have time.

thanks… also the CLA

**Comment by KOLANICH** [comment]
>also the CLA

The quote from the top message in this issue:

>CLA won't be signed, but you can consider the contribution as the one in public domain. Also it is likely that it is below the threshold of originality since it is a result of just applying the software and some mechanistic procedures.

I don't sign any legally binding aggreements when it is not really benefiting me. Here it me who donates the contribution to the project. I have said "public domain", and that must be enough for you to accept the content without legal risks.

CLA-bots (a third-party webapp requiring me to sign into their website using my GH acc), CLAs in PSF-fashion, when one yas to fax a scan of ID, DCOs, requiring people use their legal names and all of this KYC-stuff is just destroying free open-source software movement. The foundation of FOSS movement is that just a file called `License.md` + knowledge which content is covered by it should be enough to use that content. Then some overparanoid lawyers said "not enough intimidating; let's also collect personal data, oathes, etc, etc, etc...." I feel it is not very far from tye times when collection of biometric data as a "proof" that the person who has sent the DCO  is the one having that legal name would become standard. What would be required next, a certificate from a psychiatrist, narcologist and proctologist?! I refuse to play such games.

>Anyway, if you don't want to accept the PR, you can use the tool linked to make a your own PR.

**Comment by srl295** [comment]
@KOLANICH The only agreement here is the exact text of the license. And it only needs GitHub login to do so.

**Comment by KOLANICH** [comment]
>The only agreement here is the exact text of the license. And it only needs GitHub login to do so.

https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license

>Whenever you add Content to a repository containing notice of a license, you license that Content under the same terms, and you agree that you have the right to license that Content under those terms.

So, in this case the CLA bot is unnecessary.

**Comment by macchiati** [comment]
I'm sorry, but we simply cannot accept contributions without a signed CLA.

**Comment by KOLANICH** [comment]
I have expected that it can be the response. Quite some corporate repos have rejected my contributions on that basis.

Fortunately, you can close the PR and use the tool to redo the changes from a user that has the CLA signed, and send a PR from that user.

**Comment by srl295** [comment]
superseded by #2396

**Pull request closed without merging**
