### PR TITLE
CLDR-14573 Add full data of Kaingang and Nheengatu locales

### PR DESCRIPTION
**Pull request by robertgmelo**
CLDR-14573 - Add full data of Kaingang and Nheengatu locales
- Kaingang (kgp) data (common and keyboard)
- Nheengatu (yrl) data (common and keyboard)
- Update supplemental data

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
test timeout in ansible-lint unrelated, dealing with it in CLDR-14408

**Comment by srl295** [comment]
LGTM for supplemental and spot check of data. Lots of good work here!

- @macchiati should this be in seed first and with a lower draft status? It does seem to be fairly complete, though.

**Review by srl295 — COMMENTED** [review]
LGTM so far but question about status

**Review by macchiati — CHANGES_REQUESTED** [review]
The keyboard changes shouldn't go in here. The android, etc directories are snapshots of the respective platforms, and not used by those platforms. The Keyboard subcommittee is working to change that... They could go into the und directory, under a separate ticket/PR.

otherwise looks good.

**Comment by DavidLRowe** [comment]
kgp.xml seems to have one `unit` element that references 
`type="consumption-liter-per-100kilometers"`
rather than
`type="consumption-liter-per-100-kilometer"`
but it still seems to pass the tests, so I don't know what to say! (@srl295 Steven, do you have any thoughts? Is this an issue with the test?)

It still seems as though that ought to be corrected (from `-per-100kilometers` to `-per-100-kilometer`). Other than that (and the keyboard changes), it seems fine.

**Comment by srl295** [comment]
> kgp.xml seems to have one `unit` element that references
> `type="consumption-liter-per-100kilometers"`
> rather than
> `type="consumption-liter-per-100-kilometer"`
> but it still seems to pass the tests, so I don't know what to say! (@srl295 Steven, do you have any thoughts? Is this an issue with the test?)
> 
> It still seems as though that ought to be corrected (from `-per-100kilometers` to `-per-100-kilometer`). Other than that (and the keyboard changes), it seems fine.

Can you file a new ticket and include the whole element? that does sound like a bug.

**Comment by robertgmelo** [comment]
I can adjust the PR with David's and Mark's suggestions, and create a new PR for the keyboards. In addition, abandon #1094, #1095 and #1096. What do you think, @srl295 @DavidLRowe ?

**Comment by srl295** [comment]
> I can adjust the PR with David's (it seems we have an alias, but I can fix), and Mark's suggestions, and create a new PR for the keyboards. In addition, abandon #1094, #1095 and #1096. What do you think, @srl295 @DavidLRowe ?

Sounds good. 

>  (it seems we have an alias, but I can fix), 

yes, looks like it's valid, but not preferred.

**Comment by DavidLRowe** [comment]
@robertgmelo If you change the unit @type and remove the keyboard files, you can then squash the commits on this PR (using the  tool you get by clicking on "Details" link next to "single-commit" test result) and it should be fine. (That is, no need to make another PR. Just make changes to this one.) 

Then 1094-1096 as well as #1339 can be closed (without merge).

@srl295 Presumably we don't need a ticket, since there was an alias to the old unit type?

**Comment by robertgmelo** [comment]
Sure, sure. I'll replace old units with newest names as per alias values (unit.xml). 

Regarding another PR, I meant for keyboards, to put files on `und` directory.

**Comment by robertgmelo** [comment]
I've updated the changes accordingly, and created a new PR containing only keyboard data (#1352).

**Comment by DavidLRowe** [comment]
> Regarding another PR, I meant for keyboards, to put files on `und` directory.

Oops! Sorry for the misunderstanding!

**Review by DavidLRowe — DISMISSED** [review]
LGTM

**Review by srl295 — DISMISSED** [review]

**Comment by DavidLRowe** [comment]
@macchiati Robert made the changes you requested (moving the keyboard stuff to a new PR), so could you re-review this PR?

**Comment by srl295** [comment]
@DavidLRowe  @robertgmelo needs rebase. Almost there!

**Comment by DavidLRowe** [comment]
Sorry, @srl295 , I'm out of my depth here!

**Comment by robertgmelo** [comment]
Las month everything was ok, but now I'm seeing two conflicting files (files that were removed).

I'll rebase again tomorrow morning my timezone.

**Comment by srl295** [comment]
@robertgmelo Please rebase by tomorrow morning for this to go in.

**Review by DavidLRowe — DISMISSED** [review]
AFAICT this looks good.

**Comment by DavidLRowe** [comment]
@macchiati You requested that the keyboard information be removed from this PR. That has been done, but GH thinks you ought to re-review this PR.

**Comment by robertgmelo** [comment]
Not really :( 
I'm checking. it seems on country names.

**Review by macchiati — APPROVED** [review]
Looks good now.

**Comment by robertgmelo** [comment]
All test have passed! I'd say we are ready to go!

**Review by srl295 — APPROVED** [review]

**Pull request merged**
