### PR TITLE
CLDR-11312 Valid HTML

### PR DESCRIPTION
**Pull request by btangmu**
-Fix some warnings/errors per validator.w3.org

-Remove id for td cells, change styles and selectors to use class instead

-The type attribute for the style element is not needed and should be omitted

-The type attribute is unnecessary for JavaScript resources

-Attribute execute not allowed on element div at this point (in v.jsp)

-Element a not allowed as child of element ul in this context; gear menu ul add li

-The border attribute is obsolete. Specify class border: 0 instead (in iconHtml)

-The aria-labelledby attribute must point to an element; delete attribute

-Duplicate ID stchanged_btn; delete unused id

-Delete superfluous hidden votedcell and errcell

-Delete surveyConfig and theTable.config; use tr.querySelector() instead

-Delete superfluous style for empty Dashboard statuscell

-Delete unused function wrapRadios

-Delete ineffective Close button referencing non-existent function dismissChangeNotice

-Delete superfluous assignment theTable = theDiv.theTable

-Save time by skipping some initialization of theTable when it is re-used

-Avoid id=null, instead use removeAttribute(id) where needed

-Fix stray end tag input and stray end tag td, change latter to th in hidden.html

-An img element must have an alt attribute

-Fix colspan attribute values, 7 not 9; in Dashboard, 5 not 7

-Remove commented-out code

-Comments

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-11312
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
LGTM, IMHO. Still I'm making it a "draft" PR to begin, due to the large number and variety of changes. It's probably best for at least a couple reviewers to take a careful look.

Note: travis errors are expected due to unresolved problems with new XML in PR #303

It's OK with me if we wait until those errors are resolved before merging this PR.

**Comment by btangmu** [comment]
I just noticed that I made LIMITED_SUBMISSION = false in this PR, which I did for testing but didn't really intend to be part of the PR. Will it be false for v38?

**Comment by srl295** [comment]
Lgtm so far. Drop the r@. Can’t explain showers ==0 off the top of my head.

**Comment by macchiati** [comment]
It will be false for the v38.

Mark

**Comment by btangmu** [comment]
About the r@, it could be that upgrading jQuery would solve the issue. Anyway it turns out not to be important for this ticket since for the elements that needed changing, we always have the tr already and can get the td by tr.querySelector(class).

I'll go ahead and make this "ready for review" (turn off draft status).

**Pull request merged**
