### PR TITLE
CLDR-16433 Apply fixes from the PNF working group

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-16433

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by srl295 — DISMISSED** [review]
DTD already fixed?

**Comment by macchiati** [comment]
Yes, should be.

**Review by richgillam — APPROVED** [review]
Table looks good.  I think everything else looks good too.

**Comment by macchiati** [comment]
Thanks!

**Comment by macchiati** [comment]
would like to merge, any later changes in separate PR

**Review by richgillam — APPROVED** [review]

**Pull request merged**
