### PR TITLE
CLDR-16548 create choctaw nation

### PR DESCRIPTION
**Pull request by stenshamn**
CLDR-16548

- [X] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
LGTM but commit message needs work

**Comment by srl295** [comment]
@stenshamn close.

The commit message is `CLDR-16548-create-choctaw-nation`

it needs to be `CLDR-16548 create-choctaw-nation`

**Review by rickmcgowan — APPROVED** [review]
Changes for Choctaw look good. Thanks.

**Comment by stenshamn** [comment]
> @stenshamn close.
> 
> The commit message is `CLDR-16548-create-choctaw-nation`
> 
> it needs to be `CLDR-16548 create-choctaw-nation` - need a space after the 8 not a dash.

Thanks. Updated the commit message.

**Pull request merged**
