### PR TITLE
CLDR-13489 Move "Updating DTDs" into the git repository: no changes yet.

### PR DESCRIPTION
**Pull request by hugovdm**
Should I make changes within this pull request, or do we want to discuss HTML-vs-Markdown first?

Rationale: I think it's useful to have the documentation live next to the code so that we can ask people to update it while they update DTDs, for example.

##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13489
- [X] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by hugovdm** [comment]
Mark: please also confirm that the documentation from cldr.unicode.org is appropriately licensed for inclusion in the git repository, given that it's governed by the CLA?

**Comment by hugovdm** [comment]
Mark: please also confirm that the documentation from cldr.unicode.org is appropriately licensed for inclusion in the git repository, given that it's governed by the CLA?

**Comment by sffc** [comment]
Given that you're making a new directory, I believe this PR should be in Markdown, not HTML.

**Comment by sffc** [comment]
Reopening and closing to trigger some missing updates on the JIRA side.

**Pull request closed without merging**
