### PR TITLE
CLDR-16132 TZ Database 2022f updates for maint-42

### PR DESCRIPTION
**Pull request by pedberg-icu**
(cherry picked from commit ab072679a9369d9f6540b953d5ec638e1cfa3b06)

CLDR-16132

- [x] This PR completes the ticket.

Cherry-pick changes for tzdata 2022f from https://github.com/unicode-org/cldr/pull/2505 into maint-42 branch

### CODE REVIEW

**Comment by markusicu** [comment]
"Commit d36bfaf is for CLDR-16115, but the PR is for CLDR-16132" -- you may need to change the PR to be for the original ticket, and set the fixVersions of that to both 42 and 43. Or maybe @srl295 has a better idea.

**Comment by pedberg-icu** [comment]
> Instead, update the commit message to say [CLDR-16132](https://unicode-org.atlassian.net/browse/CLDR-16132) at top and then further down mention that it's a cherry pick of [CLDR-16115](https://unicode-org.atlassian.net/browse/CLDR-16115)

OK, I did that. Initially I could not find the commit on the branch in my fork to amend, until I realized that somehow this PR ended up on a branch off the main repo instead of off my fork (but I have the same branch in both my fork and my copy of the main repo...), must have switched directories at some point.

**Comment by srl295** [comment]
> > Instead, update the commit message to say [CLDR-16132](https://unicode-org.atlassian.net/browse/CLDR-16132) at top and then further down mention that it's a cherry pick of [CLDR-16115](https://unicode-org.atlassian.net/browse/CLDR-16115)
> 
> OK, I did that. Initially I could not find the commit on the branch in my fork to amend, until I realized that somehow this PR ended up on a branch off the main repo instead of off my fork (but I have the same branch in both my fork and my copy of the main repo...), must have switched directories at some point.
> 
> Should I re-do this on my fork?

no, it's fine

**Comment by srl295** [comment]
commit message is great

**Review by srl295 — APPROVED** [review]

**Pull request merged**
