### PR TITLE
CLDR-16776 Transform bug in es-fa

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-16776

Simple bug.

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by roozbehp — APPROVED** [review]

**Review by pedberg-icu — DISMISSED** [review]

**Comment by macchiati** [comment]
@roozbehp, the tests are failing because the 'golden data' test file has different results.

Could you check those out, and see if they are ok? If so, I'll fix the test file.

**Comment by roozbehp** [comment]
> @roozbehp, the tests are failing because the 'golden data' test file has different results.
> 
> Could you check those out, and see if they are ok? If so, I'll fix the test file.

I checked the errors reported in GitHub. They all appear to be improvements, based on my limited understanding of Spanish pronunciation and a handful of thorough spot checks I did (by searching Google for a recorded pronunciation of the Spanish words).

So feel free to fix the golden data test file.

**Comment by macchiati** [comment]
Great, thanks!

**Comment by macchiati** [comment]
@roozbehp I made changes in the test file. They were:

adahuesca: "آذااویسکا" became "آذااوسکا"
aldehuela: "آلدیاویلا" became "آلدیاولا"
brihuega: "بریاویغا" became "بریاوغا"
escorihuela: "ایسکوریاویلا" became "ایسکوریاولا"
huelago: "اویلاغو" became "اولاغو"
huelamo: "اویلامو" became "اولامو"
huelma: "اویلما" became "اولما"
huelva: "اویلوا" became "اولوا"
huelves: "اویلویس" became "اولویس"
hueneja: "اوینیخا" became "اونیخا"

You can see what the Spanish sounds like by going to the following URL and hitting the speaker button.

https://translate.google.com/?sl=es&tl=en&text=adahuesca%0Aaldehuela%0Abrihuega%0Aescorihuela%0Ahuelago%0Ahuelamo%0Ahuelma%0Ahuelva%0Ahuelves%0Ahueneja&op=translate

**Review by roozbehp — APPROVED** [review]

**Comment by macchiati** [comment]
Ah, the listing of errors in github wasn't complete, so I'll have to add a few more.

**Comment by macchiati** [comment]
All the tests pass, so if I can get an approval...

**Review by roozbehp — APPROVED** [review]

**Pull request merged**
