### PR TITLE
CLDR-17947 site: css: fix breakage

### PR DESCRIPTION
**Pull request by srl295**
merge conflict broke css for img

compare the images https://cldr.unicode.org/index/keyboard-workgroup to https://c6075b6b.cldr.pages.dev/index/keyboard-workgroup

CLDR-17947

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
If the image width was the problem, it now appears solved:
https://cldr.unicode.org/index/language-support-levels#language-selection-ui

**Comment by macchiati** [comment]
Note that the h1, h2, ... styles are still incorrect.

Eg, https://cldr.unicode.org/downloads/cldr-46#current-levels

This is an h4 element, but italic. All of them down to h5 should be bold
and non-italic. It appears that our h4 is not overriding the font-style
correctly; all of *our* site styles should have

font-weight: bold;
font-style: normal;

except for h6, which will have

font-weight: bold;
font-style: italic;

**Comment by srl295** [comment]
> Note that the h1, h2, ... styles are still incorrect. Eg, https://cldr.unicode.org/downloads/cldr-46#current-levels This is an h4 element, but italic. All of them down to h5 should be bold and non-italic. It appears that our h4 is not overriding the font-style correctly; all of *our* site styles should have font-weight: bold; font-style: normal; except for h6, which will have font-weight: bold; font-style: italic;
 
this is just the PR for the broken curly brace. I wasn't aware something was incorrect.

**Comment by macchiati** [comment]
Moved my comment to https://unicode-org.atlassian.net/browse/CLDR-17947?focusedCommentId=177549

**Pull request merged**
