### PR TITLE
CLDR-14177 RBNF for Nepali

### PR DESCRIPTION
**Pull request by grhoten**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14177
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by grhoten** [comment]
@srl295 @macchiati @iwsfutcmd Can one of you please review and approve these changes?

I ran these rules through [Number Format Tester](https://st.unicode.org/cldr-apps/numbers.jsp), and it seems fine to me. Please note that I worked with the author to get these in good shape.

**Comment by iwsfutcmd** [comment]
can we verify with native speakers that निल ("nil") is the correct translation of NaN? I'm not finding it in any of my Nepali dictionaries. If it's just a borrowing of the English word "nil", I'd be worried that it may be confused for 0.

**Comment by grhoten** [comment]
You make a good point. I'd rather just remove the translation, since it seems suspect, and it's not a common thing to translate.

**Comment by grhoten** [comment]
I have removed the suspect NaN translation.

**Review by iwsfutcmd — APPROVED** [review]
LGTM

**Review by srl295 — COMMENTED** [review]
RSLGTM if @iwsfutcmd  likes it

structure looks good

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
@grhoten I'll merge if needed (assume you don't have priv)

**Comment by grhoten** [comment]
Yes, please merge it. I never got authority to merge when we switched to GitHub.

**Pull request merged**
