### PR TITLE
CLDR-16758 fix 'import old votes'

### PR DESCRIPTION
**Pull request by srl295**
CLDR-16758

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by btangmu — APPROVED** [review]

**Comment by srl295** [comment]
fixed version 

image

**Review by btangmu — APPROVED** [review]
excellent!

**Review by pedberg-icu — APPROVED** [review]

**Comment by macchiati** [comment]
Great. Sounds like people don't have to re-import

**Comment by btangmu** [comment]
@macchiati there's also a major bug in auto-import, so after a fix is committed (I should have it ready shortly), I think we'll need to reset everyone's auto-import flag, causing auto-import to run again the next time they log in

**Pull request merged**
