### PR TITLE
CLDR-14060 fix chart generation (churn)

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14060
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
This conflicts with https://github.com/unicode-org/cldr/pull/608 which is still open.

The last sample churn report I provided was based on PR 608.

I see this PR adds useful integration with the GenerateAllCharts.java but shouldn't that happen after merging PR 608?

**Comment by macchiati** [comment]
Ah, i'd thought you were done with the churn report.

Can you method what I did in 616 into yours, and then we'll drop 616?

**Comment by btangmu** [comment]
Yes, I'll make another PR for integration with the GenerateAllCharts.java.

**Comment by btangmu** [comment]
Please see https://github.com/unicode-org/cldr/pull/617

I'll close this one.

**Pull request closed without merging**
