### PR TITLE
CLDR-15368 VOTE_USES_NEW_API=true, replaces WHAT_SUBMIT

### PR DESCRIPTION
**Pull request by btangmu**
-Front end: new VOTE_USES_NEW_API = true, getSubmitUrl, and related modernization in cldrVote.js

-Back end: use the same resolved CLDRFile for daip and calculateShowRowAction

-Back end: rename pvi to dataRow

-Back end: if value is empty in api post request, make it null, meaning abstain

-Both front and back end: rename submitResultRaw to submitResult for consistency

-Updated package-lock.json (unrelated to changes for this ticket)

-Comments

CLDR-15368

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
@srl295 I unintentionally included changes to tools/cldr-apps/js/package-lock.json -- should that be in the pr or not?

**Comment by srl295** [comment]
> @srl295 I unintentionally included changes to tools/cldr-apps/js/package-lock.json -- should that be in the pr or not?

My bump of the Node version may have caused it, #2423 — a new version of the lockfile is now made.  If you want that could be a separate PR just for the lockfile.  

I think it's fine just to note it.

**Comment by btangmu** [comment]
Revised to address safety issue -- sanitize "loc" (from http request) with "loc = locale.getBaseName()"

**Review by srl295 — APPROVED** [review]
no change since i reviewed last

**Pull request merged**
