### PR TITLE
CLDR-14523 fix BRS problems

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14523
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by yumaoka** [comment]
@macchiati There are some test failures with this change. Please take a look.

https://github.com/unicode-org/cldr/pull/1053/checks?check_run_id=1930119403
```
Error summary:
CLDR/LikelySubtagsTest/TestCompleteness
CLDR/LikelySubtagsTest/TestMissingInfoForScript


<< 3 TEST(S) FAILED >>
```

**Comment by macchiati** [comment]
The problem with the first commit is that (1) the mapping is not idempotent (filed XXX also) and (2) Hatr is known to not have a language (the script metadata was hiding that by using 'mis', but we don't want 'mis' showing up in likely subtags.

**Comment by macchiati** [comment]
The XXX is https://unicode-org.atlassian.net/browse/CLDR-14524

**Review by yumaoka — APPROVED** [review]
LGTM

**Comment by btangmu** [comment]
Please let me know when it's time for me to run CLDRModify again!

**Comment by macchiati** [comment]
I haven't heard from Steven on the following. So I'm doing the 2nd right
now (the first doesn't affect CLDR Modify), so once the 2nd is done you are
good to start CLDRModify
todo: CLDR-14512 Steven/Mark
todo: CLDR-14513 Steven/Mark
Mark

**Comment by macchiati** [comment]
I did both of those. #1 needed no changes, so closed the ticket.
I have https://github.com/unicode-org/cldr/pull/1055. If one of you can
review that'd be great, and you can merge right after.
Mark

**Pull request merged**
