### PR TITLE
CLDR-14395 add a session cookie

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14395

- [ ] This PR completes the ticket.

### CODE REVIEW

**Review by btangmu — APPROVED** [review]
the changes look good -- I'm surprised not to see changes to cldrGui.run or vurl, still worried the s= stuff will cause problems -- anyway I'll approve this and let's keep iterating

**Comment by btangmu** [comment]
Excellent PR number, by the way!

**Comment by srl295** [comment]
> the changes look good -- I'm surprised not to see changes to cldrGui.run or vurl, still worried the s= stuff will cause problems -- anyway I'll approve this and let's keep iterating

I wanted to get this in progress first

**Comment by srl295** [comment]
#1235 is the followon

**Pull request merged**
