### PR TITLE
CLDR-15826 Fix PersonName Check warnings and errors

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-15826

- [ ] This PR completes the ticket.

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAccessor.java

- Needed access to the Phase() in the CheckAccessor.

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java

- Name Order locales were being changed for exemplars, but those are just ASCII

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java

- Dropped the old (ugly) REQUIRED and REQUIRED_EMPTY. The info is improved, and moved to SampleType. So we can just test with sampleType.getOptionality(modifiedField);
- The logic in handleCheck is improved. We are about whether the MISSING values are in the locale either explicitly or by explicit inheritance, but don't show errors if we don't yet have a value added to the locale.
- We emit warnings in BUILD phase (so we can check in), but errors in Submission, etc.

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java

- We emit warnings in BUILD phase (so we can check in), but errors in Submission, etc.

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- Here is where we build the set of items that are required vs optional into the SampleType, along with a getter (getOptionality(…)) that we can use in unittests and Checks
- Rebuild the test for TestCheckPersonNames to use sampleType.getOptionality.

### CODE REVIEW

**Comment by macchiati** [comment]
I know everyone is off for the holiday, but if you happen to have some spare time before Monday's meeting, I'd appreciate a review.

**Review by btangmu — DISMISSED** [review]

**Comment by macchiati** [comment]
Only changes in rebase were adjusting import statements.

**Comment by btangmu** [comment]
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.56 s <<< FAILURE! - in org.unicode.cldr.unittest.web.TestShim
Error:  TestAll  Time elapsed: 4.559 s  <<< ERROR!
com.google.common.util.concurrent.UncheckedExecutionException: com.ibm.icu.util.ICUException: Couldn't make resolved CLDR file for en
	at org.unicode.cldr.unittest.web.TestShim.TestAll(TestShim.java:23)
Caused by: com.ibm.icu.util.ICUException: Couldn't make resolved CLDR file for en
	at org.unicode.cldr.unittest.web.TestShim.TestAll(TestShim.java:23)
Caused by: java.lang.NullPointerException
	at org.unicode.cldr.unittest.web.TestShim.TestAll(TestShim.java:23)

**Comment by macchiati** [comment]
That turned out to be a nasty order of static initialization, with some clunky file loading. Works locally, so we'll see what happens on the server.

**Comment by macchiati** [comment]
Had to squash - all tests now passing.

**Review by btangmu — APPROVED** [review]

**Pull request merged**
