### PR TITLE
CLDR-16122 v43 BRS -z… FINAL_TESTING

### PR DESCRIPTION
**Pull request by srl295**
CLDR-16122

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by pedberg-icu — APPROVED** [review]

**Comment by srl295** [comment]
moving to draft for now, will target brs/v43vxml

**Comment by srl295** [comment]
@btangmu retargetted this PR

**Review by btangmu — APPROVED** [review]

**Comment by btangmu** [comment]
@srl295 although I approved this as a draft PR, we don't actually want to merge it into brs/v43vxml until much later, if ever, right?

**Comment by srl295** [comment]
Right. It's ready when you need it

**Comment by srl295** [comment]
rebased this…

**Comment by srl295** [comment]
I expect this to pass tests, and it should then be merged.

**Comment by srl295** [comment]
@btangmu  actually we do want to merge it, once it passes.  Because it's a BRS item to keep FINAL_TESTING enabled at this phase.

**Comment by macchiati** [comment]
We should have a separate PR (on a branch from main) that just has the setting for final testing enabled, and the changes for the 7 errors:
```
fi [Finnish]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name-one◂	〈Sierra Leonean leone (1964—2022)〉	【】	〈Sierra Leonen leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/fi//208985c6135fb58e
fi [Finnish]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name-other◂	〈Sierra Leonean leones (1964—2022)〉	【】	〈Sierra Leonen leonea〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/fi//7d9503e5da5eb88
fi [Finnish]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name◂	〈Sierra Leonean Leone (1964—2022)〉	【】	〈Sierra Leonen leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/fi//770c9302f08cf129

nl [Dutch]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name-one◂	〈Sierra Leonean leone (1964—2022)〉	【】	〈Sierraleoonse leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/nl//208985c6135fb58e
nl [Dutch]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name-other◂	〈Sierra Leonean leones (1964—2022)〉	【】	〈Sierraleoonse leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/nl//7d9503e5da5eb88
nl [Dutch]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name◂	〈Sierra Leonean Leone (1964—2022)〉	【】	〈Sierraleoonse leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/nl//770c9302f08cf129
nl_BE [Flemish]	error	▸Miscellaneous|Person_Name_Formats|SampleName_Fields_for_Item:_nativeFull|surname◂	〈null〉	【】	〈Van den Berg〉	«=»	【】	⁅bad sample person name⁆	❮Error: This value must be empty (∅∅∅)❯	https://st.unicode.org/cldr-apps/v#/nl_BE//34fb7dd818856bdb
```

**Comment by srl295** [comment]
> This is weird. Main is up to date with VXML as of https://github.com/unicode-org/cldr/pull/2667/files. So we shouldn't be merging anything else into brs/v43vxml.
> 
> 

Something went wrong with this one. No matter, I'll open a new one.

**Comment by srl295** [comment]
> We should have a separate PR (on a branch from main) that just has the setting for final testing enabled, and the changes for the 7 errors:
> 

They are already merged. 


> ```
> 
> fi [Finnish]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name-one◂	〈Sierra Leonean leone (1964—2022)〉	【】	〈Sierra Leonen leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/fi//208985c6135fb58e
> 
> fi [Finnish]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name-other◂	〈Sierra Leonean leones (1964—2022)〉	【】	〈Sierra Leonen leonea〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/fi//7d9503e5da5eb88
> 
> fi [Finnish]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name◂	〈Sierra Leonean Leone (1964—2022)〉	【】	〈Sierra Leonen leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/fi//770c9302f08cf129
> 
> 
> 
> nl [Dutch]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name-one◂	〈Sierra Leonean leone (1964—2022)〉	【】	〈Sierraleoonse leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/nl//208985c6135fb58e
> 
> nl [Dutch]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name-other◂	〈Sierra Leonean leones (1964—2022)〉	【】	〈Sierraleoonse leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/nl//7d9503e5da5eb88
> 
> nl [Dutch]	error	▸Currencies|Western_Africa|Western_Africa:_Sierra_Leone|SLL-name◂	〈Sierra Leonean Leone (1964—2022)〉	【】	〈Sierraleoonse leone〉	«=»	【】	⁅display collision⁆	❮Error: Can't have same translation as [Western Africa: Sierra Leone: SLE-name]. Please change either this name or the other one. See <a target='doc' href='http://cldr.unicode.org/translation/short-names-and-keywords#TOC-Unique-Names'>Unique-Names</a>.❯	https://st.unicode.org/cldr-apps/v#/nl//770c9302f08cf129
> 
> nl_BE [Flemish]	error	▸Miscellaneous|Person_Name_Formats|SampleName_Fields_for_Item:_nativeFull|surname◂	〈null〉	【】	〈Van den Berg〉	«=»	【】	⁅bad sample person name⁆	❮Error: This value must be empty (∅∅∅)❯	https://st.unicode.org/cldr-apps/v#/nl_BE//34fb7dd818856bdb
> 
> ```
> 
> 
> 
> 
> 
>

**Comment by srl295** [comment]
> nl_BE [Flemish]	

I hadn't seen this one.

**Pull request closed without merging**
