### PR TITLE
CLDR-15646 Priority Items Summary, fix bug in last PR; add debug logging

### PR DESCRIPTION
**Pull request by btangmu**
-Was missing this. in this.canCreateSnapshots

-Debug logging conditional on SUMMARY_DEBUG

CLDR-15646

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
@macchiati @srl295 there seem to be some timing issues making behavior pseudo random, possibly depending on browser (Firefox vs Chrome), debugging tools on front and back end, etc. This morning, occasionally I seem to be able to repro problems similar to what Mark has reported.

On the front end, this code seems suspicious:
```
    if (latestArgs.loadingPolicy === LOAD_NOSTART) {
        window.setTimeout(fetchStatus.bind(this), NORMAL_RETRY);
    }
```
Possibly it should be:
```
    if (latestArgs.loadingPolicy !== LOAD_FORCESTOP) {
...
```

On the back end, this code seems suspicious:
```
status = "Waiting...";
progress.update("Waiting...");
OnlyOneVetter.acquire();
try {
    if (stop) {
        status = "Stopped on request.";
        statusCode = Status.STOPPED;
        return;
    }
    processCriticalWork(progress);
} finally {
    OnlyOneVetter.release();
}
status = "Finished.";
statusCode = Status.READY;
```
I'm occasionally seeing it seeming to get stuck on "Waiting..."

**Comment by btangmu** [comment]
I turned on DEBUG in VettingViewerQueue and the console shows:
[INFO] Creating task for Priority Items Summary
[INFO] Starting up vv task: Priority Items Summary
[INFO] Starting generation of Priority Items Summary
[INFO] Creating task for Priority Items Summary
[INFO] Starting up vv task: Priority Items Summary
[INFO] [ERROR   ] While VettingViewer processing Priority Items Summary
[INFO] java.lang.InterruptedException
[INFO] Creating task for Priority Items Summary
[INFO] Starting up vv task: Priority Items Summary

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
> @macchiati @srl295 there seem to be some timing issues making behavior pseudo random, possibly depending on browser (Firefox vs Chrome), debugging tools on front and back end, etc. This morning, occasionally I seem to be able to repro problems similar to what Mark has reported.
> 
> On the front end, this code seems suspicious:
> 
> ```
>     if (latestArgs.loadingPolicy === LOAD_NOSTART) {
>         window.setTimeout(fetchStatus.bind(this), NORMAL_RETRY);
>     }
> ```
> 
> Possibly it should be:
> 
> ```
>     if (latestArgs.loadingPolicy !== LOAD_FORCESTOP) {
> ...
> ```
> 
> On the back end, this code seems suspicious:
> 
> ```
> status = "Waiting...";
> progress.update("Waiting...");
> OnlyOneVetter.acquire();
> try {
>     if (stop) {
>         status = "Stopped on request.";
>         statusCode = Status.STOPPED;
>         return;
>     }
>     processCriticalWork(progress);
> } finally {
>     OnlyOneVetter.release();
> }
> status = "Finished.";
> statusCode = Status.READY;
> ```
> 
> I'm occasionally seeing it seeming to get stuck on "Waiting..."

I'd think 'finally' gets fired even if there was an exception. so it should only wait if someone still has the lock acquired.

**Comment by btangmu** [comment]
> I'd think 'finally' gets fired even if there was an exception. so it should only wait if someone still has the lock acquired.

I think the thread is killed after acquire, before release... I put in additional println as shown in the new ticket https://unicode-org.atlassian.net/browse/CLDR-15819 and the release never happens

**Comment by srl295** [comment]
> > I'd think 'finally' gets fired even if there was an exception. so it should only wait if someone still has the lock acquired.
> 
> I think the thread is killed after acquire, before release... I put in additional println as shown in the new ticket https://unicode-org.atlassian.net/browse/CLDR-15819 and the release never happens

Very strange.  I wonder why the thread was killed, not just interrupted. I'd think an InterruptedException first.

**Comment by btangmu** [comment]
> Very strange

Yes. We have Survey-Tool-specific code tangled up with long-running-task-management code; the latter should be a separate reusable class, preferably one that we don't have to write and maintain ourselves...

**Comment by srl295** [comment]
> > Very strange
> 
> Yes. We have Survey-Tool-specific code tangled up with long-running-task-management code; the latter should be a separate reusable class, preferably one that we don't have to write and maintain ourselves...

If you are referring to the threadpool, note that directly workign with threads is [forbidden within J2EE](https://www.martellosecurity.com/kb/mitre/cwe/383/) because all threads are managed by the web container.

**Comment by btangmu** [comment]
does VettingViewerQueue.java currently obey that rule?

**Comment by srl295** [comment]
> does VettingViewerQueue.java currently obey that rule?

Yes, although I think I see a bug:

```java
// VVQ.java 397ff

        // TODO: May be better to use SurveyThreadManager.getExecutorService().invoke() (rather than a raw thread) but would require
        // some restructuring
        t = entry.currentTask = new Task(entry, args.usersOrg);
        t.myThread = SurveyThreadManager.getThreadFactory().newThread(t);
        t.myThread.start();
        SurveyThreadManager.getThreadFactory().newThread(t);  // <<<<<<<<<<<<<<<<<<<<
```

newThread is called twice…

**Comment by srl295** [comment]
> yikes!

not clear this is the cause. but it's definitely wrong

**Pull request merged**
