### PR TITLE
CLDR-14607 Adding metaZoneSupplemental

### PR DESCRIPTION
**Pull request by sffc**
CLDR-14607

- [ ] This PR completes the ticket.

This XML structure would serve our needs.  See the ticket and the email to cldr-core2 for more information.

### CODE REVIEW

**Comment by macchiati** [comment]
To fit in with the other features, the data should be in https://github.com/unicode-org/cldr/blob/master/common/bcp47/timezone.xml, with that structure. 

eg name = bcp47 code, alias=metazone

We need comments in the file that the 4-letter forms are used for metazones, with one legacy exception:
            <type name="gaza" description="Gaza Strip, Palestinian Territories" alias="Asia/Gaza"/>

We will also need a spec change to describe this. Needn't be long.

**Comment by macchiati** [comment]
Note: there will likely be some work necessary on the tests as well, since the current assumption is that all items are timezones not metazones.

**Comment by srl295** [comment]
> To fit in with the other features, the data should be in https://github.com/unicode-org/cldr/blob/master/common/bcp47/timezone.xml, with that structure.
> 
> eg name = bcp47 code, alias=metazone
> 
> We need comments in the file that the 4-letter forms are used for metazones, with one legacy exception:
> 
> We will also need a spec change to describe this. Needn't be long.

I propose:

```xml
            <type name="auce" description="Metazone: Australia_Central" alias="Australia_Central"/>
```

We could have a cldrmodify type task that automatically sets the descriptions to the generic name from English, such as `description="Metazone: Central Australia Time"` or just `description="Central Australia Time"`.  A simplistic `description` should be fine for now.

**Comment by macchiati** [comment]
Yes simple description done for now.

Mark (📱)

**Comment by srl295** [comment]
@sffc ping?

**Comment by macchiati** [comment]
Put revised version into https://github.com/unicode-org/cldr/pull/1457

**Comment by sffc** [comment]
Archived in my fork as `archive/CLDR-14607-metazone`

**Pull request closed without merging**
