### PR TITLE
CLDR-13620 Add draft="contributed" to unitPreferenceData.

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13620
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by macchiati** [comment]
Will need dtd changes to pass tests. Copy one of the draft attribute lines
without true or false (and following annotation lines).

**Comment by sffc** [comment]
I edited the DTD.  Do you know off the top of your head why I would be getting the following test failure, in CLDR/TestPaths/TestNonLdml?

```
     [java]       Error: (TestPaths.java:429) Deprecated item in data: supplementalData:unitPreferenceData:draft 	;/home/travis/build/unicode-org/cldr/common/supplemental/units.xml
```

**Comment by macchiati** [comment]
will check it out
Mark

**Comment by macchiati** [comment]
BTW, in sourcetree how do I make a local branch for this PR?

**Comment by sffc** [comment]
> BTW, in sourcetree how do I make a local branch for this PR?

You have to add `git@github.com:sffc/cldr.git` as a remote (you can name the remote `sffc`), then you can Fetch and then check out the branch named `contributed`.  You should also be able to push to the branch.

**Comment by macchiati** [comment]
Found the problem. Can I just commit to your branch?

Mark

**Comment by macchiati** [comment]
that is, to "contributed"?

Mark

**Comment by sffc** [comment]
Of course, you can commit and push to my branch, thanks!

**Comment by macchiati** [comment]
Hmmm. I get:

git --no-optional-locks -c color.branch=false -c color.diff=false -c
color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c
credential.helper=sourcetree -c
lfs.customtransfer.bitbucket-media-api.path=/Applications/Sourcetree.app/Contents/Resources/git_local/git-lfs/git-lfs-bitbucket-media-api
push -v --tags --set-upstream Shane
refs/heads/contributed:refs/heads/contributed

Pushing to git@github.com:sffc/cldr.git

ERROR: Authentication error: Authentication required: You must have push
access to verify locks

error: failed to push some refs to 'git@github.com:sffc/cldr.git'

Completed with errors, see above


Mark

**Pull request merged**
