### PR TITLE
CLDR-16313 UI for Report Acceptability Votes

### PR DESCRIPTION
**Pull request by srl295**
- Vue component for VoteInfo
- Vue component for User (backed by REST api)
- REST api for user info

CLDR-16313

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
vote status:
PastedGraphic-1
expand to see votes
PastedGraphic-2
expand and hover to see user detail
PastedGraphic-3


@stenshamn  perhaps the email should be skipped if it's not same-org (or super admin)?

**Review by macchiati — CHANGES_REQUESTED** [review]
1. The Approval Status is part of the "I have not reviewed". While we don't have time for thorough UI, you can improve that by putting an <hr> after the I have not reviewed button.

2. For the voting, best to use basically the same format as the voting tables, cf https://st.unicode.org/cldr-apps/v#/fr/PersonNameFormats/4d3331350af797e9

That is, no hover, and a table format. This should also only be visible by account holders, like the other voting tables.

|| Response || Org || User ||
|| Acceptable || google || John Q. Smith ||
|| Unacceptable || apple || Sarah Z. Jones ||
...

**Comment by srl295** [comment]
> 1. The Approval Status is part of the "I have not reviewed". While we don't have time for thorough UI, you can improve that by putting an  after the I have not reviewed button.
> 2. For the voting, best to use basically the same format as the voting tables, cf https://st.unicode.org/cldr-apps/v#/fr/PersonNameFormats/4d3331350af797e9
> 
> That is, no hover, and a table format. This should also only be visible by account holders, like the other voting tables.
> 

OK, sounds good.

**Comment by srl295** [comment]
@macchiati PTAL.  It doesn't sort the votes _per value_ (some logic to start doing that) but just lists any votes this way.

image

**Comment by macchiati** [comment]
What does it look like, open and closed, when you have 1 acceptable and one unacceptable voter?

**Comment by srl295** [comment]
> What does it look like, open and closed, when you have 1 acceptable and one unacceptable voter?

image


image

**Comment by srl295** [comment]
fixed a bad commit msg

**Review by macchiati — APPROVED** [review]
Looks great

**Pull request merged**
