### PR TITLE
CLDR-11744 Change Indochina timezone name in zh

### PR DESCRIPTION
**Pull request by AEApple**
Update Indochina timezone name in zh & zh_Hant.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-11744
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by AEApple** [comment]
Is it possible to smash and merge the two commits or do I need to submit these separately? Unfortunately the GitHub web editor does not let me edit multiple files in one commit. I tried a workaround, but it didn't work unfortunately.

**Comment by pedberg-icu** [comment]
> Is it possible to smash and merge the two commits or do I need to submit these separately? Unfortunately the GitHub web editor does not let me edit multiple files in one commit. I tried a workaround, but it didn't work unfortunately.

Yes, it is. Unfortunately I only know how to do this from the command line, not from any web-based interface; Mark might be able to help with the web-based way. However there is another problem, whatever account you used (or whatever e-mail was associated with the github repo) does not seem to be included in the accounts covered by the Google CLA. You either need to double-check the account or get someone with the right admin privileges to add you to the CLA (I think Steven can do that for example).

**Comment by srl295** [comment]
> > Is it possible to smash and merge the two commits or do I need to submit these separately? Unfortunately the GitHub web editor does not let me edit multiple files in one commit. I tried a workaround, but it didn't work unfortunately.
> 
> Yes, it is. Unfortunately I only know how to do this from the command line, not from any web-based interface; Mark might be able to help with the web-based way. However there is another problem, whatever account you used (or whatever e-mail was associated with the github repo) does not seem to be included in the accounts covered by the Google CLA. You either need to double-check the account or get someone with the right admin privileges to add you to the CLA (I think Steven can do that for example).

where it says "single-commit — This PR has 2 commits; consider squashing" in the checks (by the red ❌ ) click Details, and there's a 'squash branch…' button. @sffc may have more details.

**Review by srl295 — APPROVED** [review]

**Comment by AEApple** [comment]
I actually have this GitHub account registered with Google according to the GoogleCLA, so I'm not sure why it isn't showing correctly.

**Review by macchiati — APPROVED** [review]

**Pull request merged**
