### PR TITLE
CLDR-15516 Unicode 15 collation data aug26

### PR DESCRIPTION
**Pull request by markusicu**
CLDR-15516

CLDR collation root & zh collation tailorings generated by the Unicode Tools, as of 2022-aug-26.
There are no changes to `common/transforms/Han-Latin.xml` this time.

- [ ] This PR completes the ticket.

FYI @echeran @josh-hadley

### CODE REVIEW

**Comment by markusicu** [comment]
FYI
- no manual changes
- I will probably not merge this until I have tried to integrate Unicode 15 into ICU again, in a few days

**Comment by macchiati** [comment]
Looks like a small number of changes:
https://github.com/unicode-org/cldr/pull/2315/files#diff-41145264b920ea9e99ff3c5cb8ebe83944752d0eceae3be79dd13743dc559606

**Comment by markusicu** [comment]
Right, not much changed in collation since the beta came out.
FractionalUCA.txt additionally shows the effects of some radical-stroke data bug fixes.

**Review by srl295 — APPROVED** [review]

**Review by macchiati — DISMISSED** [review]

**Comment by markusicu** [comment]
squashed, please re-approve; ICU also looks happy, see https://github.com/unicode-org/icu/pull/2169

**Review by macchiati — APPROVED** [review]

**Pull request merged**
