### PR TITLE
CLDR-15052 Fixed Iceland provinces for the Dutch language

### PR DESCRIPTION
**Pull request by mason-chase**
CLDR-15052  Fixed Iceland provinces for the Dutch language.

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
@mason-chase thanks! would you be able to open a ticket at https://unicode-org.atlassian.net/projects/CLDR/
 and then update this PR to make your commit message / PR start with that number?  "CLDR-0000 Correction in Dutch…" thanks

**Comment by mason-chase** [comment]
Hi

The issue has been created as per your instruction: https://unicode-org.atlassian.net/browse/CLDR-15052

Cheers
Mason

**Comment by srl295** [comment]
> Hi
> 
> The issue has been created as per your instruction: https://unicode-org.atlassian.net/browse/CLDR-15052
> 
> Cheers
> Mason

@macchiati is investigating

**Comment by mason-chase** [comment]
@srl295 anything else I am missing?

**Comment by srl295** [comment]
> @srl295 anything else I am missing?

The first line of the commit message should be the same as the pr title

**Comment by mason-chase** [comment]
How do you make CLDR-XXXX link properly within the commit message? https://unicode-org.atlassian.net/browse/CLDR-15052

**Comment by srl295** [comment]
> How do you make CLDR-XXXX link properly within the commit message? https://unicode-org.atlassian.net/browse/CLDR-15052

You can just write:  CLDR-15052 for most text.  the commit title doesn't always auto link.
But you did it exactly right.  Our process does have some specific requirements… But the purpose is so that we can automatically connect commits to tickets later on.

You're done, just awaiting review.

**Comment by mason-chase** [comment]
Hi @srl295 
What should do about this PR?

Regards

**Comment by srl295** [comment]
@macchiati ?

**Comment by macchiati** [comment]
We're planning to deprecate the subdivision names in v42 (https://cldr.unicode.org/index/downloads/cldr-41), so closing this PR. Sorry that you went to the extra work for this.

**Pull request closed without merging**
