### PR TITLE
CLDR-15597 Create Draft TR35

### PR DESCRIPTION
**Pull request by AEApple**
CLDR-15597

Create Draft TR35

- [X] This PR completes the ticket.

### CODE REVIEW

**Comment by macchiati** [comment]
Looks good. We should talk about having the version number be:
42 (draft)

**Comment by AEApple** [comment]
Sure, do you want me to update the version number to be `42 (draft)` in all the files?

I updated the status paragraph per Rick's feedback.

**Review by srl295 — DISMISSED** [review]

**Comment by srl295** [comment]
needs squash <https://us-central1-dev-infra-273822.cloudfunctions.net/unicode-github-bot/info/unicode-org/cldr/1959> otherwise lgtm

**Review by srl295 — APPROVED** [review]

**Comment by macchiati** [comment]
That's safer, because there is no indication otherwise on all but the first
part, and even on the first part people's eyes tend to skip over. I think
we should also bold it

**Comment by AEApple** [comment]
Okay, I will update it then and then re-squash and re-trigger everyone for review.

We can keep as a sample in the BRS for future updates.

**Comment by AEApple** [comment]
@macchiati - PTAL at the updated tr35-collation.md file and let me know if that is what you were thinking.

**Review by rickmcgowan — DISMISSED** [review]

**Review by macchiati — DISMISSED** [review]

**Review by macchiati — APPROVED** [review]

**Pull request merged**
