### PR TITLE
CLDR-13620 Apply new CLDR 37 unit aliases throughout CLDR

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13620
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by sffc** [comment]
I did a global search/replace.  Most of the hits were in main/common and seed/common.  There were a few hits outside those directories that I touched up manually.

**Comment by macchiati** [comment]
This will have some downstream costs. The survey tool stores votes by path; if we change all of these paths, then all of the votes will become invalid. So in order to do this, we'd have to also fix all of the stored paths in the survey tool. 

We need to run this by the committee to make sure people agree to doing this, and it will have be be done before we start testing for submission start. We can send an email this weekend, but people might not read it and respond by Monday.

**Comment by macchiati** [comment]
It would be better to separate out the permillion case into a separate PR, so that we can be sure to get that one through.

**Comment by sffc** [comment]
The downstream cost of not doing it will affect ICU; since convertUnit is based on the new IDs, we would need logic to do the "reverse mapping" back to the deprecated versions in order to look up formatting data.

The permillion case is in a separate PR.  It's not in this PR.

**Comment by macchiati** [comment]
It's "downstream" for the survey tool server; I wasn't talking about ICU.

Mark

**Comment by sffc** [comment]
Right; this PR has downstream costs, both positive (ICU) and negative (Survey Tool).

**Comment by sffc** [comment]
I merged #361 and #362 into this PR, and squashed down to one commit.  This PR is therefore applying all of the following aliases.  I verified that the old identifiers only occur in units.xml (`<unitAlias/>`), validity/unit.xml (deprecated), and in relevant test files.

```
<unitAlias type="inch-hg" replacement="inch-ofhg" reason="deprecated"/>
<unitAlias type="liter-per-100kilometers" replacement="liter-per-100-kilometer" reason="deprecated"/>
<unitAlias type="meter-per-second-squared" replacement="meter-per-square-second" reason="deprecated"/>
<unitAlias type="millimeter-of-mercury" replacement="millimeter-ofhg" reason="deprecated"/>
<unitAlias type="part-per-million" replacement="permillion" reason="deprecated"/>
<unitAlias type="pound-foot" replacement="pound-force-foot" reason="deprecated"/>
<unitAlias type="pound-per-square-inch" replacement="pound-force-per-square-inch" reason="deprecated"/>
```

**Pull request merged**
