### PR TITLE
CLDR-13705 remove redundant currency symbols (will be derived)

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13705
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by pedberg-icu** [comment]
OK but... Where is the code to derive them, and why are symbols like Peso treated differently?

**Comment by macchiati** [comment]
Andrew and Kristi did the triage. Based on whether the symbol is used for a
single ISO currency code.

**Comment by Kristi27** [comment]
Mark, I think you removed a lot more than what I had identified in the spreadsheet, which was only 13 of 41.  I do not think you can derive all these from existing. Have you checked in addition to what I provided? 
From my e-mail, even if they are in CLDR, I excluded if: 

1. There are some currency symbols that we only supported for the particular locale, so we should leave them in the symbols as is. E.g. Azerbaijan Manat.
2. Where there are multiple use of the symbol, I think we should keep them in Symbols as is. (e.g. Won and Colon

**Comment by macchiati** [comment]
Hi Mark,
I just added a comment in your PR.
It seems that you’ve removed more than what I identified.
Here’s the e 13 of 41 that I had identified as existing:

Code
Symbol
English names/tts
Keywords/Annotations
ST Page/Heading<https://unicode.org/emoji/charts-13.0/emoji-ordering.html>
~Category
Already in Currency data
Names in CLDR currecy data
U+0E3F
฿
thai baht
baht | THB
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_SEAsia/77b4f6f5c1211991
U+20AA
₪
sheqel
shekel | ILS
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_WAsia/38b5e909b61be944
Israeli New Shekel
U+20BA
₺
turkish lira
lira | TRY
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_WAsia/36f05a9e26abbeef
Turkish Lira
U+20AB
₫
Vietnamese dong
dong | VND
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_SEAsia/4844a0e00233234b
Vietnamese Dong
U+20A6
₦
Nigerian naira
naira | NGN
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_WAfrica/600a0f34fd05bec4
U+20AE
₮
Mongolian tugrik
tugrik | togrog | tögrög | MNT
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_EAsia/143549029f5437cd
Mongolian Tugrik
U+09F3
৳
Bangladeshi taka
taka | BDT
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_SAsia/3166c1c8d7b80920
Bangladeshi Taka
U+20B4
₴
Ukrainian hryvnia
hryvnia | UAH
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_SEEurope/4bff180f61f6c958
Ukrainian Hryvnia
U+20B8
₸
Kazakhstani tenge
tenge | KZT
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_CAsia/261075ce2ce7e09e
Kazakhstani Tenge
U+20B2
₲
Paraguayan guarani
guarani | guaraní | PYG
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_SAmerica/1a5cff2ed6d770ae
Paraguayan Guarani
U+17DB
៛
Cambodian riel
riel | KHR
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_SEAsia/9cee912ac02a249
Cambodian Riel
U+20AD
₭
Lao kip
kip | LAK
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_SEAsia/26c7182cd52dd3f4
Laotian Kip
U+20BE
₾
Georgian lari
lari | GEL
currency symbols
https://st.unicode.org/cldr-apps/v#/en/C_WAsia/174ad9e3cec5252a
Georgian Lari


From: Mark Davis ☕️ <mark@macchiato.com>
Sent: Tuesday, May 26, 2020 9:28 PM
To: unicode-org/cldr <reply@reply.github.com>
Cc: unicode-org/cldr <cldr@noreply.github.com>; Author <author@noreply.github.com>; Andrew Glass <Andrew.Glass@microsoft.com>; Kristi Lee (CELA) <kristil@microsoft.com>
Subject: [EXTERNAL] Re: [unicode-org/cldr] CLDR-13705 remove redundant currency symbols (will be derived) (#483)

Andrew and Kristi did the triage. Based on whether the symbol is used for a single ISO currency code.



On Tue, May 26, 2020, 20:44 pedberg-icu <notifications@github.com<mailto:notifications@github.com>> wrote:

OK but... Where is the code to derive them, and why are symbols like Peso treated differently?

**Comment by macchiati** [comment]
I did a filter on your values:

U+0E3F | ฿ | thai baht | baht \| THB |   | currency symbols | 0.03% | Name derivable from existing data
-- | -- | -- | -- | -- | -- | -- | --
U+20AA | ₪ | sheqel | shekel \| ILS |   | currency symbols | 0.03% | Name derivable from existing data
U+20BA | ₺ | turkish lira | lira \| TRY |   | currency symbols |   | Name derivable from existing data
U+20AB | ₫ | Vietnamese dong | dong \| VND |   | currency symbols | 0.03% | Name derivable from existing data
U+20A9 | ₩ | won | KRW \| KPW |   | currency symbols | 0.01% | Name derivable from existing data
U+20A1 | ₡ | colon | CRC \| SVC |   | currency symbols |   | Name derivable from existing data
U+20A6 | ₦ | Nigerian naira | naira \| NGN |   | currency symbols |   | Name derivable from existing data
U+20AE | ₮ | Mongolian tugrik | tugrik \| togrog \| tögrög \| MNT |   | currency symbols |   | Name derivable from existing data
U+09F3 | ৳ | Bangladeshi taka | taka \| BDT |   | currency symbols |   | Name derivable from existing data
U+20B4 | ₴ | Ukrainian hryvnia | hryvnia \| UAH |   | currency symbols |   | Name derivable from existing data
U+20B8 | ₸ | Kazakhstani tenge | tenge \| KZT |   | currency symbols |   | Name derivable from existing data
U+20B2 | ₲ | Paraguayan guarani | guarani \| guaraní \| PYG |   | currency symbols |   | Name derivable from existing data
U+20B5 | ₵ | Ghanaian cedi | cedi \| GHS |   | currency symbols |   | Name derivable from existing data
U+17DB | ៛ | Cambodian riel | riel \| KHR |   | currency symbols |   | Name derivable from existing data
U+20AD | ₭ | Lao kip | kip \| LAK |   | currency symbols |   | Name derivable from existing data
U+058F | ֏ | Armenian dram | dram \| AMD |   | currency symbols |   | Name derivable from existing data
U+20BE | ₾ | Georgian lari | lari \| GEL |   | currency symbols |   | Name derivable from existing data
U+20BC | ₼ | Azerbaijani manat | manat \| AZN |   | currency symbols |   | Name derivable from existing data
U+060B | ؋ | Afghan afghani | afghani \| AFN |   | currency symbols |   | Name derivable from existing data

Then built a regex to remove them. [฿₪₺₫₱₩₡₦₮৳₴₸₲₵៛₭֏₥₾₼₿؋]

Looks like that didn't work properly; thanks for the review.

**Comment by Kristi27** [comment]
Here's what was not on my list compare to the list in your comment.
1. Won (how would you distinguish between KRW and KPW?)
2. colon (same issue CRC | SVC)
3. Ghanaian cedi 
4. Armenian dram 
5. Azerbaijani manat (Not in all language. Only in Azerbaijan)
6. Afghan afghani 
These fell under the 2 reasons why I did not include them.  I don't believe we have data we can use in all languages.

**Comment by macchiati** [comment]
1. ₩ you are right, will restore! (I pulled the data from columns in the spreadsheet marked "Name derivable from existing data", and it was marked there.)

2. For the others, I took different action. All of the following are just used for a single currency. ₡ used to be used in 2 countries, but that was almost 2 decades ago. So instead of restoring them, I made sure the symbols were in main/root.xml, and verified the coverage.

main/root.xml 
Already had CRC ₡
Added narrow symbols for these:
GHS - ₵ (longer symbol in use: GH₵, I suspect because ₵ would be read as "cent")
AMD - ֏
AZN - ₼
AFN - ؋

coverageLevel.xml
The coverage is set by %currency80 for level=moderate. It contains all of these already. And I verified that, they are present already in the data for the CLDR focus locales (and more)

...
fi.xml (5 matches)
6,063: <currency type="AFN"> 
6,081: <currency type="AMD"> 
6,174: <currency type="AZN"> 
6,483: <currency type="CRC"> 
6,688: <currency type="GHS"> 
fil.xml (5 matches)
6,850: <currency type="AFN"> 
6,862: <currency type="AMD"> 
6,901: <currency type="AZN"> 
7,060: <currency type="CRC"> 
7,184: <currency type="GHS"> 
fo.xml (5 matches)
4,677: <currency type="AFN"> 
4,689: <currency type="AMD"> 
4,728: <currency type="AZN"> 
4,887: <currency type="CRC"> 
5,001: <currency type="GHS"> 
...

**Comment by macchiati** [comment]
Ok, I merged for now, just so we're ready for shakedown. But we can bring this up in the TC and tune it as necessary.

**Comment by pedberg-icu** [comment]
> I think your actions on others make sense. But they will expose them in all locales, which typically we've discussed in the TC. Will flag to Peter too.

Thanks Kristi. These latest changes (including root narrow currency symbol additions) make sense to me.

**Pull request merged**
