### PR TITLE
CLDR-17274 XCG translations

### PR DESCRIPTION
**Pull request by AEApple**
CLDR-17274

XCG translations for Curaçao and Sint Maarten's new currency

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by AEApple** [comment]
I added all the translations, but please let me know if I'm missing anything in a file that I may not have considered. Thanks!

**Comment by srl295** [comment]
> I added all the translations, but please let me know if I'm missing anything in a file that I may not have considered. Thanks!

there's a whole process for updating codes, https://cldr.unicode.org/development/updating-codes/update-currency-codes and in this case the validity data needs to be updated also.

**Comment by macchiati** [comment]
@pedberg-icu can you take a look? (I made changes, so someone else should review)

**Review by pedberg-icu — APPROVED** [review]

**Comment by pedberg-icu** [comment]
> @pedberg-icu can you take a look? (I made changes, so someone else should review)

@macchiati @AEApple Approved, looks good.

**Comment by macchiati** [comment]
Annemarie, I merged but didn't delete the branch, in case you wanted to retain it.

**Comment by srl295** [comment]
N.B. the currency change is in 2025, not 2024 as this ticket changed. https://github.com/unicode-org/cldr/pull/3471/files#diff-5ea2936f709d9dc83508c70c9a589a5bdaadf9392a0ca96d9b56507621f4090b

**Pull request merged**
