### PR TITLE
CLDR-15598 Update Google coverage in Locales.txt

### PR DESCRIPTION
**Pull request by meikehubert**
Commented out nqo in Google
Added in Google and Cldr at basic: bho, bgc, raj

CLDR-_____

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by macchiati** [comment]
Meike, this fails because it can't locale bcg.xml (probably doesn't exist yet). 

Note: when you go to https://github.com/unicode-org/cldr/pull/1976/files and search for "Check failure", you'll find an abbreviated error message for the problems.

You should modify this to comment out bcg for now, then make a new PR that includes the bcg locale and this change later.

**Comment by srl295** [comment]
> Meike, this fails because it can't locale bcg.xml (probably doesn't exist yet).
> 
> Note: when you go to https://github.com/unicode-org/cldr/pull/1976/files and search for "Check failure", you'll find an abbreviated error message for the problems.
> 
> You should modify this to comment out bcg for now, then make a new PR that includes the bcg locale and this change later.

@macchiati 
it's in TestPathHeader.TestCompleteness

>             toTest = StandardCodes.make().getLocaleCoverageLocales(Organization.cldr);

So…… basically, `bcg` becomes a "CLDR Locale" because of the entry. I wonder if `getLocaleCoverageLocales` should actually _exclude_ nonexistent locales to avoid this. What do you think?

**Review by srl295 — DISMISSED** [review]
LGTM but needs to pass

**Comment by macchiati** [comment]
We want the test to remain. No point in adding a locale until it exists,
and the test prevents errors.

**Review by stenshamn — DISMISSED** [review]

**Comment by pedberg-icu** [comment]
> I think we actually need to add the core data before we can add the new locales in the locale.txt file.

Yes

**Comment by srl295** [comment]
@meikehubert  I rebased this PR

**Review by AEApple — APPROVED** [review]

**Review by srl295 — APPROVED** [review]

**Pull request merged**
