### PR TITLE
CLDR-14312 handle canonicalization of subdivision aliases

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14312
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by FrankYFTang** [comment]
Mark- which version of this change will make into UTS35? is this a part of changes going to public release soon ? or will it be part of the next (Fall) release? I just wonder should I attempt to put the necessary ICU change (as tracked by https://unicode-org.atlassian.net/browse/ICU-21550 ) into 69.1 or should we wait till 70.1

**Review by FrankYFTang — APPROVED** [review]
LGTM

**Comment by macchiati** [comment]
I think it is too late for 69.1, but we should definitely target 70.1

Mark

**Comment by FrankYFTang** [comment]
So, Mark 
en-u-rg-fi01 should be canonicalized into en-u-rg-axzzzz not en-AX-u-rg-axzzzz ?

**Comment by FrankYFTang** [comment]
so... Mark- I try to address ICU by first put down the test case, here is some tests I pick, does this mean sense to you?
```
--- a/icu4c/source/test/intltest/loctest.cpp
+++ b/icu4c/source/test/intltest/loctest.cpp
@@ -4938,6 +4938,21 @@ void LocaleTest::TestCanonicalize(void)
         { "und-FR-u-sd-frg", "und-FR-u-sd-frges"},
         { "und-LU-u-sd-lud", "und-LU-u-sd-lucl"},
 
+        // ICU-21550
+        { "und-u-rg-fi01", "und-u-rg-axzzzz"},
+        { "und-u-rg-frcp", "und-u-rg-cpzzzz"},
+        { "und-u-rg-frpm", "und-u-rg-pmzzzz"},
+        { "und-u-rg-usvi", "und-u-rg-vizzzz"},
+        { "und-u-rg-cn91", "und-u-rg-hkzzzz"},
+        { "und-u-rg-nlaw", "und-u-rg-awzzzz"},
+
+        { "und-NO-u-sd-frre", "und-NO-u-sd-rezzzz"},
+        { "und-CN-u-sd-nlcw", "und-CN-u-sd-cwzzzz"},
+        { "und-CZ-u-sd-usgu", "und-CZ-u-sd-guzzzz"},
+        { "und-FR-u-sd-shta", "und-FR-u-sd-tazzzz"},
+        { "und-FR-u-sd-cn71", "und-FR-u-sd-twzzzz"},
```

**Pull request merged**
