### PR TITLE
CLDR-17935 site: add crawler sitemap

### PR DESCRIPTION
**Pull request by srl295**
CLDR-17935

- add sitemap.xml for crawlers

This is unrelated to site organization or navigation. It's so that the crawlers can index the site properly.

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — CHANGES_REQUESTED** [review]
Needs some work; let's discuss Tuesday

**Comment by srl295** [comment]
> Needs some work; let's discuss Tuesday

I took out the human-readable `sitemap.md` - a higher priority may be having sitemap.xml in so that when the new site is live, that it is crawlable, because crawlers may or may not be able to navigate the popup menu.

https://094f5448.cldr.pages.dev/sitemap.xml

So, at this point the PR has no visible change, but the sitemap (for crawlers) might be worth getting in as or soon after going live.

**Review by conradarcturus — APPROVED** [review]
Let the robots in. Looks solid.

**Comment by srl295** [comment]
@macchiati any objection?

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
Great… The spiders should pick this up automatically, but I'll update them manually just in case

**Pull request merged**
