### PR TITLE
CLDR-16531 v44 BRS: GenerateDerivedAnnotations

### PR DESCRIPTION
**Pull request by srl295**
- errors in locales

CLDR-16531

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

TODO still
- [ ] CLDRModify
- [ ] Transform
- [ ] CLDRModify again

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
That means that the code was unable to create annotations for those characters. 

I think we don't need this by alpha, we can file as a ticket, and can have as a known issue in the release note and fix sometime before beta. @AEApple @pedberg-icu (Anyone know Ned's github ID?)

**In more detail.** This is a new kind of structure for emoji, so we need to modify the generation code and the spec for it. 

With a zwj sequence containing the arrows, the corresponding label are added to the name for the base character.

Example: 🏃‍♀‍➡

Get the characterLabelPatterns

		<characterLabelPattern type="facing-left">{0} vers la gauche</characterLabelPattern>
		<characterLabelPattern type="facing-right">{0} vers la droite</characterLabelPattern>

Get the annotations for the part before the ZWJ+arrow

		<annotation cp="🏃‍♀">course à pied | femme | femme qui court | jogging | marathon</annotation>
		<annotation cp="🏃‍♀" type="tts">femme qui court</annotation>

And combine with a : pattern (like the gender variants)

		<annotation cp="🏃‍♀‍➡">course à pied | femme | femme qui court | jogging | marathon | vers la droite</annotation>
		<annotation cp="🏃‍♀‍➡" type="tts">femme qui court: vers la droite</annotation>

**Comment by macchiati** [comment]
That is, I think we should go ahead and commit the others, and follow up with a different PR.

**Comment by srl295** [comment]
@macchiati  doing cldrmodify -fQ and then it's ready for review and merge

**Review by macchiati — APPROVED** [review]
Just make sure to leave the ticket open for a subsequent PR

**Comment by macchiati** [comment]
You can assign the ticket to me to finish up.

**Comment by srl295** [comment]
> You can assign the ticket to me to finish up.

It's just my catch all for v44 codes. I can make a subtask for you though.

**Pull request merged**
