### PR TITLE
CLDR-14199 Add new locale file shn.xml to seed/main

### PR DESCRIPTION
**Pull request by i18ncraig**
CLDR-14199 Add new Myanmar locale file for Shan (ISO shn) to seed/main.

##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14199
- [X] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by srl295** [comment]
commit message needs to also be:
> `CLDR-14199 Add new locale file shn.xml to seed/main`

**Review by srl295 — COMMENTED** [review]
- generally RSLGTM however:
- commit message issue
- test failures:
   1. default content needs to be set
   2. may need an empty shn_?? locale
   3. XML validation failure

**Comment by srl295** [comment]
fails validation:

```shell
$ java -jar tools/cldr-code/target/cldr-code.jar validate ./seed/main/shn.xml
>> org.unicode.cldr.util.XMLValidator
Note: CLDR_DIR was unset but you seem to be in a CLDR directory. Setting -DCLDR_DIR=.
# 1 file(s) to check
/Users/srl295/src/cldr2/seed/main/shn.xml:9304:8: ERROR: Element null is not valid because The content of element type "ldml" must match "(identity,(alias|(fallback*,localeDisplayNames?,layout?,contextTransforms?,characters?,delimiters?,measurement?,dates?,numbers?,units?,listPatterns?,collations?,posix?,characterLabels?,segmentations?,rbnf?,typographicNames?,annotations?,metadata?,references?,special*)))".
# 1 file(s) OK
```

**Comment by srl295** [comment]
I can't really review the file effectively due to UI sluggishness, but a few things:

- `<localeDisplayNames>` ends too early. Then, there are additional <language … > entries that all need ot be within localeDisplayNames.
- there are  `<script type=…` elements that should be inside `<scripts/>` which should be inside `<localeDisplayNames/>`


I'm not sure what the source of this data is, but it might be better to start with a smaller file, make sure it passes validation, then keep adding data to it.

**Comment by srl295** [comment]
you can download the .jar file needed here (or later versions): http://unicode.org/Public/cldr/38.1/ -you can download and use cldr-code.jar for validation

**Review by macchiati — CHANGES_REQUESTED** [review]
the items need draft="provisional"

**Comment by srl295** [comment]
@i18ncraig ?

**Comment by i18ncraig** [comment]
I had Git problems on my machine. About the time I got these fixed, I though it was past the deadline to address this ticket. Is there still time for the repair of shn.xml?

**Comment by SZTSIIT** [comment]
@srl295 Hi Steven, I just found this link to this page now. Would you like able add blank xml for Shan language ? That XML file is from us (Shan Institute of Information Technology(SIIT)). I was just checking the status on Jira. :D

**Comment by srl295** [comment]
@I18ncraig can you update it ?

**Comment by i18ncraig** [comment]
I cannot. Peter E and I tried to get me unblocked. No joy. Someone else
needs to check this in, please. Note there was a problem with the file
(unmatched parens or the like). Run through the Java checker first.

**Comment by srl295** [comment]
Superseded by #2159

**Pull request closed without merging**
