### PR TITLE
CLDR-14061 Copy from VXML for version 38

### PR DESCRIPTION
**Pull request by btangmu**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14061
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
There was a lot of strangeness in the production of VXML today, as partially described in email to cldr-core2.

This PR uses the contents of vetdata-2020-08-05T19-56-49-323Z. A zipped copy of that is here on the production server:

/home/cldradmin/vetdata-2020-08-05T19-56-49-323Z.tar.gz

I repeated the process on localhost and produced vetdata-2020-08-05T23-40-20-893Z, which is identical with vetdata-2020-08-05T19-56-49-323Z. The following was displayed in the browser:

```
Verification notice, file(s) present in vxml but not in baseline
common/annotations/mi.xml
common/annotations/rm.xml
seed/annotations/und.xml
seed/annotations/doi.xml
common/annotations/mai.xml
common/annotations/ti.xml
seed/annotations/oc.xml
common/annotations/wo.xml
common/annotations/tg.xml
common/annotations/tt.xml
common/annotations/ckb.xml
seed/annotations/und_ZZ.xml
common/annotations/mni.xml
common/annotations/su.xml
common/annotations/ha.xml
common/annotations/sat.xml
common/annotations/ig.xml
seed/annotations/sa.xml

Verification failure, file(s) present in baseline but not in vxml
seed/main/.DS_Store
common/annotations/.DS_Store
common/main/.DS_Store
```

The "failures" for ".DS_Store" are only due to a peculiarity of macOS. The verification code should be revised to ignore such hidden files.

I also repeated the process on the production server and produced vetdata-2020-08-05T23-29-54-648Z, which seemed to be created very much faster, and mysteriously has a few differences:

```
diff -r vetdata-2020-08-05T23-40-20-893Z/vxml/common/annotations/en.xml vetdata-2020-08-05T23-29-54-648Z/vxml/common/annotations/en.xml
47,50d46
< 		<!-- causes tool breakage
< 			 <annotation cp="">whitespace</annotation>
< 			 <annotation cp="" type="tts">space</annotation>
< 		-->
795c791
< 		<annotation cp="😶‍🌫">absentminded | face in the fog | face in clouds | head in clouds</annotation> <!-- 1F636 200D 1F32B FE0F: face in clouds -->
---
> 		<annotation cp="😶‍🌫">absentminded | face in the fog | face in clouds | head in clouds</annotation>
837c833
< 		<annotation cp="😵‍💫">dizzy | hypnotized | spiral | trouble | whoa</annotation> <!-- 1F635 200D 1F4AB -->
---
> 		<annotation cp="😵‍💫">dizzy | hypnotized | spiral | trouble | whoa</annotation>
863c859
< 		<annotation cp="😮‍💨">exhale | gasp | groan | relief | whisper | whistle</annotation> <!-- 1F62E 200D 1F4A8 -->
---
> 		<annotation cp="😮‍💨">exhale | gasp | groan | relief | whisper | whistle</annotation>
985c981
< 		<annotation cp="❤‍🔥">burn | heart | love | lust | sacred heart</annotation> <!-- 2764 200D 1F525 -->
---
> 		<annotation cp="❤‍🔥">burn | heart | love | lust | sacred heart</annotation>
987c983
< 		<annotation cp="❤‍🩹">healthier | improving | mending | recovering | recuperating | well</annotation> <!-- 2764 200D 1FA79 -->
---
> 		<annotation cp="❤‍🩹">healthier | improving | mending | recovering | recuperating | well</annotation>
1365,1366c1361
< 		<!-- (more) Generated lines from Emoji Data v13, using GenerateCldrData.java -->
< 		<annotation cp="🤵‍♂">man | man in tuxedo | tuxedo</annotation> <!-- 1F935 200D 2642 -->
---
> 		<annotation cp="🤵‍♂">man | man in tuxedo | tuxedo</annotation>
1368c1363
< 		<annotation cp="🤵‍♀">tuxedo | woman | woman in tuxedo</annotation> <!-- 1F935 200D 2640 -->
---
> 		<annotation cp="🤵‍♀">tuxedo | woman | woman in tuxedo</annotation>
1372c1367
< 		<annotation cp="👰‍♂">man | man with veil | veil</annotation> <!-- 1F470 200D 2642 -->
---
> 		<annotation cp="👰‍♂">man | man with veil | veil</annotation>
1374c1369
< 		<annotation cp="👰‍♀">veil | woman | woman with veil</annotation> <!-- 1F470 200D 2640 -->
---
> 		<annotation cp="👰‍♀">veil | woman | woman with veil</annotation>
1380c1375
< 		<annotation cp="👩‍🍼">baby | feeding | nursing | woman</annotation> <!-- 1F469 200D 1F37C -->
---
> 		<annotation cp="👩‍🍼">baby | feeding | nursing | woman</annotation>
1382c1377
< 		<annotation cp="👨‍🍼">baby | feeding | man | nursing</annotation> <!-- 1F468 200D 1F37C -->
---
> 		<annotation cp="👨‍🍼">baby | feeding | man | nursing</annotation>
1384c1379
< 		<annotation cp="🧑‍🍼">baby | feeding | nursing | person</annotation> <!-- 1F9D1 200D 1F37C -->
---
> 		<annotation cp="🧑‍🍼">baby | feeding | nursing | person</annotation>
1392c1387
< 		<annotation cp="🧑‍🎄">Claus, christmas | mx claus</annotation> <!-- 1F9D1 200D 1F384 -->
---
> 		<annotation cp="🧑‍🎄">Claus, christmas | mx claus</annotation>
1682c1677
< 		<annotation cp="🐈‍⬛">black | cat | unlucky</annotation> <!-- 1F408 200D 2B1B -->
---
> 		<annotation cp="🐈‍⬛">black | cat | unlucky</annotation>
1764c1759
< 		<annotation cp="🐻‍❄">arctic | bear | polar bear | white</annotation> <!-- 1F43B 200D 2744 -->
---
> 		<annotation cp="🐻‍❄">arctic | bear | polar bear | white</annotation>
diff -r vetdata-2020-08-05T23-40-20-893Z/vxml/common/annotations/root.xml vetdata-2020-08-05T23-29-54-648Z/vxml/common/annotations/root.xml
48,51d47
< 		<!-- causes tool breakage
< 			 <annotation cp="">E13.1-109</annotation>
< 			 <annotation cp="" type="tts">E13.1-109</annotation>
< 		-->
796c792
< 		<annotation cp="😶‍🌫">E13.1-007</annotation> <!-- 1F636 200D 1F32B FE0F: face in clouds -->
---
> 		<annotation cp="😶‍🌫">E13.1-007</annotation>
838c834
< 		<annotation cp="😵‍💫">E13.1-002</annotation> <!-- 1F635 200D 1F4AB: face with spiral eyes -->
---
> 		<annotation cp="😵‍💫">E13.1-002</annotation>
864c860
< 		<annotation cp="😮‍💨">E13.1-001</annotation> <!-- 1F62E 200D 1F4A8: face exhaling -->
---
> 		<annotation cp="😮‍💨">E13.1-001</annotation>
986c982
< 		<annotation cp="❤‍🔥">E13.1-003</annotation> <!-- 2764 200D 1F525: heart on fire -->
---
> 		<annotation cp="❤‍🔥">E13.1-003</annotation>
988c984
< 		<annotation cp="❤‍🩹">E13.1-004</annotation> <!-- 2764 200D 1FA79: mending heart -->
---
> 		<annotation cp="❤‍🩹">E13.1-004</annotation>
1366,1367c1362
< 		<!-- (more) Generated lines from Emoji Data v13, using GenerateCldrData.java -->
< 		<annotation cp="🤵‍♂">E13-077</annotation> <!-- 1F935 200D 2642: man in tuxedo -->
---
> 		<annotation cp="🤵‍♂">E13-077</annotation>
1369c1364
< 		<annotation cp="🤵‍♀">E13-078</annotation> <!-- 1F935 200D 2640: woman in tuxedo -->
---
> 		<annotation cp="🤵‍♀">E13-078</annotation>
1373c1368
< 		<annotation cp="👰‍♂">E13-080</annotation> <!-- 1F470 200D 2642: man with veil -->
---
> 		<annotation cp="👰‍♂">E13-080</annotation>
1375c1370
< 		<annotation cp="👰‍♀">E13-079</annotation> <!-- 1F470 200D 2640: woman with veil -->
---
> 		<annotation cp="👰‍♀">E13-079</annotation>
1381c1376
< 		<annotation cp="👩‍🍼">E13-081</annotation> <!-- 1F469 200D 1F37C: woman feeding baby -->
---
> 		<annotation cp="👩‍🍼">E13-081</annotation>
1383c1378
< 		<annotation cp="👨‍🍼">E13-082</annotation> <!-- 1F468 200D 1F37C: man feeding baby -->
---
> 		<annotation cp="👨‍🍼">E13-082</annotation>
1385c1380
< 		<annotation cp="🧑‍🍼">E13-083</annotation> <!-- 1F9D1 200D 1F37C: person feeding baby -->
---
> 		<annotation cp="🧑‍🍼">E13-083</annotation>
1393c1388
< 		<annotation cp="🧑‍🎄">E13-084</annotation> <!-- 1F9D1 200D 1F384: mx claus -->
---
> 		<annotation cp="🧑‍🎄">E13-084</annotation>
1683c1678
< 		<annotation cp="🐈‍⬛">E13-085</annotation> <!-- 1F408 200D 2B1B: black cat -->
---
> 		<annotation cp="🐈‍⬛">E13-085</annotation>
1765c1760
< 		<annotation cp="🐻‍❄">E13-086</annotation> <!-- 1F43B 200D 2744: polar bear -->
---
> 		<annotation cp="🐻‍❄">E13-086</annotation>
diff -r vetdata-2020-08-05T23-40-20-893Z/vxml/seed/main/und.xml vetdata-2020-08-05T23-29-54-648Z/vxml/seed/main/und.xml
26,28d25
< 		<!-- Sandbox locale.  DO NOT MODIFY.
< 			 This file is listed as 'scratch' in SpecialLocales.txt.  If your tool modified this file, it is in error.
< 		-->
diff -r vetdata-2020-08-05T23-40-20-893Z/vxml/seed/main/und_ZZ.xml vetdata-2020-08-05T23-29-54-648Z/vxml/seed/main/und_ZZ.xml
17,19d16
< 		<!-- Sandbox locale. DO NOT MODIFY.
< 			 This file is listed as 'scratch' in SpecialLocales.txt.  If your tool modified this file, it is in error.
< 		-->
```

**Comment by macchiati** [comment]
> Verification notice, file(s) present in vxml but not in baseline
I don't think this is a material issue. These files are new in the
directory, but that is just because some people added annotation values and
those are split off into files in the separate directory.

The diffs for root.xml and en.xml are only comments, so they are not
important. Ideally the vxml generation should skip those, since they should
never be changed by the ST.

Mark

**Comment by btangmu** [comment]
>The diffs for root.xml and en.xml are only comments, so they are not important. Ideally the vxml generation should skip those, since they should never be changed by the ST. Mark

Then would it have been better to exclude them from the PR? There appear to be a lot of changes in common/annotations/en.xml, for example, in the PR. Are these all changes in comments, or sort-order, or ...?

**Comment by macchiati** [comment]
I'll take a look and see if we want to revert them

**Comment by srl295** [comment]
und.xml should not have been modified.

**Pull request merged**
