### PR TITLE
CLDR-17947 site: css: update sizes of h1, h2, h3, h4, h5, h6

### PR DESCRIPTION
**Pull request by srl295**
CLDR-17947

image

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — CHANGES_REQUESTED** [review]

**Review by macchiati — APPROVED** [review]
Looks ok now

**Comment by AEApple** [comment]
I have mixed feelings about h4 being italicized.

**Comment by macchiati** [comment]
I do too. Italicizing but being at the same size makes h6 seem *more* important than h5. I approved because I think we almost never use h6, so I think we could merge this (once conflicts are resolved @srl295 )

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
Errs are from old tsv

**Comment by macchiati** [comment]
The changes appear to not yet be active. Eg, an h4 on
https://cldr.unicode.org/ is 20pt, italic

**Pull request merged**
