### PR TITLE
CLDR-14519 keyboard info element

### PR DESCRIPTION
**Pull request by miloush**
- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14519
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by miloush** [comment]
@macchiati @xadxura please review

**Review by macchiati — APPROVED** [review]
Looks good, but you'll have to rebase and resolve.

**Comment by miloush** [comment]
@macchiati done

**Comment by miloush** [comment]
@macchiati ready now, sorry about that!

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
- [ ] this should have gone into maint-39

**Pull request merged**
