### PR TITLE
CLDR-17590 Update coverage levels for Microsoft

### PR DESCRIPTION
**Pull request by AEApple**
CLDR-17590

Update coverage levels for Microsoft

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
LGTM though ticket isn't accepted

**Comment by AEApple** [comment]
Fixed, there's no path to go from 'Done' back to 'Accepted'

**Comment by macchiati** [comment]
Let me know when you've merged, and I'll update the v46 charts

**Comment by AEApple** [comment]
SG! I was going to wait for Manuel to review the PR before merging. If we don't hear back by 2pm, let's just go ahead and merge anyway and fix later if there are any issues. WDYT?

**Comment by macchiati** [comment]
SGTM

**Review by macchiati — APPROVED** [review]

**Comment by manuelco-cldr** [comment]
I’m reviewing now, give me 10 mins and I’ll reply back. Thanks

**Comment by manuelco-cldr** [comment]
The changes we discussed looks good. However, I still see a few discrepancies with what I’m tracking. We also have:

*	Quechua (qu) at modern
*	Norwegian Nynorsk (nn) at modern
*	Tajik (tg) at modern
*	Tigrinya (ti) at modern

 

These are not reflected in the locales.txt

 

Thanks

Manuel

 

From: ***@***.*** ***@***.***> 
Sent: Wednesday, June 12, 2024 1:52 PM
To: 'unicode-org/cldr' ***@***.***>; 'unicode-org/cldr' ***@***.***>
Cc: 'Review requested' ***@***.***>
Subject: RE: [unicode-org/cldr] CLDR-17590 Update coverage levels for Microsoft (PR #3801)

 

I’m reviewing now, give me 10 mins and I’ll reply back. Thanks

**Review by manuelco-cldr — CHANGES_REQUESTED** [review]
These changes are good. However, I still see a few discrepancies with what I’m tracking. We should have:
•	Quechua (qu) at modern
•	Norwegian Nynorsk (nn) at modern
•	Tajik (tg) at modern
•	Tigrinya (ti) at modern

**Comment by AEApple** [comment]
Okay, please review now, I updated based on your feedback.

**Review by manuelco-cldr — DISMISSED** [review]
Thanks for the additional changes, it looks good.

**Review by manuelco-cldr — DISMISSED** [review]

**Comment by srl295** [comment]
Tajik (tg) is causing the test failure.  I filed https://github.com/unicode-org/cldr/pull/3803 to make the test clearer.

Basically, Tajik uses chars that aren't in our Cyrillic to Latin converter.

I'm not sure what to say, maybe demote Tajik to be less than modern until the transliterator is fixed? Maybe need a new ticket for the translit?

**Comment by manuelco-cldr** [comment]
I’m ok to downgrade or revert the changes for Tajik

**Review by macchiati — APPROVED** [review]

**Review by macchiati — APPROVED** [review]

**Pull request merged**
