### PR TITLE
CLDR-17075 clean up language containment

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17075

This includes a new tool for examining the differences among languageGroup.xml files, plus changes in the data file to address problems.

For the diffs in the data, see https://unicode-org.atlassian.net/browse/CLDR-17075?focusedCommentId=171465

The diffs are manual for now, but filed a ticket for fixing the generation tool 

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Here is a copy of the diffs:
<google-sheets-html-origin><style type="text/css"></style>

* OLD = v43 |   |  
-- | -- | --
OLD Multiple parents | Bharia ⁅bha⁆ | Dravidian (Other) ⁅dra⁆ 𝐯𝐬 Indic (Other) ⁅inc⁆
OLD Multiple parents | Iban ⁅iba⁆ | Austronesian (Other) ⁅map⁆ 𝐯𝐬 Western Malayo-Polynesian languages ⁅pqw⁆
OLD Multiple parents | Ma'di ⁅mhi⁆ | Central Sudanic languages ⁅csu⁆ 𝐯𝐬 Eastern Sudanic languages ⁅sdv⁆
OLD Multiple parents | Polari ⁅pld⁆ | Indic (Other) ⁅inc⁆ 𝐯𝐬 Romance (Other) ⁅roa⁆
OLD Multiple parents | Caló ⁅rmq⁆ | Indic (Other) ⁅inc⁆ 𝐯𝐬 Romance (Other) ⁅roa⁆
OLD Multiple parents | Sango ⁅sg⁆ | Atlantic-Congo languages ⁅alv⁆ 𝐯𝐬 Northern Ngbandi ⁅ngb⁆
OLD Multiple parents | Shelta ⁅sth⁆ | Celtic (Other) ⁅cel⁆ 𝐯𝐬 West Germanic languages ⁅gmw⁆
OLD Multiple parents | Yangben ⁅yav⁆ | Atlantic-Congo languages ⁅alv⁆ 𝐯𝐬 Bantu (Other) ⁅bnt⁆
OLD Missing | ∉ CLDR_ORG | Punjabi ⁅pa⁆, Urdu ⁅ur⁆, Korean ⁅ko⁆, Kaingang ⁅kgp⁆, Quechua ⁅qu⁆
OLD Missing | ∉ CLDR_Other | Zhuang ⁅za⁆, Kuvi ⁅kxv⁆, Muscogee ⁅mus⁆, Mapuche ⁅arn⁆, Saraiki ⁅skr⁆, Papiamento ⁅pap⁆, Chickasaw ⁅cic⁆, Choctaw ⁅cho⁆
* NEW = PR |   |  
Δ Adding (NEW-OLD) | 14: | Mapuche ⁅arn⁆, Choctaw ⁅cho⁆, Chickasaw ⁅cic⁆, Kaingang ⁅kgp⁆, Korean ⁅ko⁆, Kuvi ⁅kxv⁆, Muscogee ⁅mus⁆, Punjabi ⁅pa⁆, Papiamento ⁅pap⁆, null ⁅pu⁆, Quechua ⁅qu⁆, Saraiki ⁅skr⁆, Urdu ⁅ur⁆, Zhuang ⁅za⁆
NEW Added | Mapuche ⁅arn⁆ | ➡︎ Ω
NEW Added | Choctaw ⁅cho⁆ | ➡︎ Ω
NEW Added | Chickasaw ⁅cic⁆ | ➡︎ Ω
NEW Added | Kaingang ⁅kgp⁆ | ➡︎ Ω
NEW Added | Korean ⁅ko⁆ | ➡︎ Ω
NEW Added | Kuvi ⁅kxv⁆ | ➡︎ Dravidian (Other) ⁅dra⁆ ➡︎ Ω
NEW Added | Muscogee ⁅mus⁆ | ➡︎ Ω
NEW Added | Punjabi ⁅pa⁆ | ➡︎ Indic (Other) ⁅inc⁆ ➡︎ Indo-Iranian languages ⁅iir⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω
NEW Added | Papiamento ⁅pap⁆ | ➡︎ Creoles and pidgins, Portuguese-based (Other) ⁅cpp⁆ ➡︎ Romance (Other) ⁅roa⁆ ➡︎ Italic languages ⁅itc⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω
NEW Added | null ⁅pu⁆ | ➡︎ Indic (Other) ⁅inc⁆ ➡︎ Indo-Iranian languages ⁅iir⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω
NEW Added | Quechua ⁅qu⁆ | ➡︎ Ω
NEW Added | Saraiki ⁅skr⁆ | ➡︎ Indic (Other) ⁅inc⁆ ➡︎ Indo-Iranian languages ⁅iir⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω
NEW Added | Urdu ⁅ur⁆ | ➡︎ Indic (Other) ⁅inc⁆ ➡︎ Indo-Iranian languages ⁅iir⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω
NEW Added | Zhuang ⁅za⁆ | ➡︎ Tai (Other) ⁅tai⁆ ➡︎ Ω
Δ Moving (OLD to NEW) | 3: | Ma'di ⁅mhi⁆, Caló ⁅rmq⁆, Shelta ⁅sth⁆
OLD Removed | Ma'di ⁅mhi⁆ | ➡︎ Eastern Sudanic languages ⁅sdv⁆ ➡︎ Nilo-Saharan (Other) ⁅ssa⁆ ➡︎ Ω
NEW Moved to | Ma'di ⁅mhi⁆ | ➡︎ Central Sudanic languages ⁅csu⁆ ➡︎ Nilo-Saharan (Other) ⁅ssa⁆ ➡︎ Ω
OLD Removed | Caló ⁅rmq⁆ | ➡︎ Romance (Other) ⁅roa⁆ ➡︎ Italic languages ⁅itc⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω
NEW Moved to | Caló ⁅rmq⁆ | ➡︎ Indic (Other) ⁅inc⁆ ➡︎ Indo-Iranian languages ⁅iir⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω
OLD Removed | Shelta ⁅sth⁆ | ➡︎ West Germanic languages ⁅gmw⁆ ➡︎ Germanic (Other) ⁅gem⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω
NEW Moved to | Shelta ⁅sth⁆ | ➡︎ Celtic (Other) ⁅cel⁆ ➡︎ Indo-European (Other) ⁅ine⁆ ➡︎ Ω

**Review by pedberg-icu — APPROVED** [review]

**Comment by pedberg-icu** [comment]
I am going to go ahead and merge so we have this for CLDR-ICU integration

**Comment by srl295** [comment]
@macchiati did you end up rerunning the tool to fetch from wikidata? My PR #3249 added loop avoidance code

**Comment by macchiati** [comment]
I looked at the changes, but there are deeper changes necessary

**Pull request merged**
