### PR TITLE
CLDR-13485 Fix inconsistent use of MU by always using Greek character.

### PR DESCRIPTION
**Pull request by macchiati**
NOTE: also modifies CldrModify to skip files that have not changed except for copyright.

##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13485
- [ ] Updated PR title and link in previous line to include Issue number

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by btangmu** [comment]
As far as the data is concerned, should we try to fix the Currie problem first? I'm working on that: https://unicode-org.atlassian.net/browse/CLDR-14428

**Comment by macchiati** [comment]
If you can finish quickly...

**Comment by btangmu** [comment]
> If you can finish quickly...

OK -- note that this PR would move Australia/Currie between America/Santa_Isabel and Pacific/Honolulu, which is completely wrong, while in master it's correctly between Broken_Hill and Melbourne -- so I aim to preserve the correct position with CLDR-14428

**Comment by macchiati** [comment]
The end result should be the right position. However, we don't want to
block any tickets for this, because there is no semantic difference in the
XML files based on those two positions. So in the worst case scenario, we
can fix the position of Australia/Currie *after the data freeze*.

Mark

**Comment by btangmu** [comment]
Now that https://github.com/unicode-org/cldr/pull/970 is merged maybe CLDRModify should be run again to update the data in this PR before merging it

**Comment by srl295** [comment]
> Now that https://github.com/unicode-org/cldr/pull/970 is merged maybe CLDRModify should be run again to update the data in this PR before merging it

It would be helpful to rerun

**Review by srl295 — APPROVED** [review]
LGTM and RSLGTM on data

**Comment by srl295** [comment]
@macchiati looks like this also does CLDR-11394

**Review by srl295 — DISMISSED** [review]

**Review by srl295 — APPROVED** [review]

**Review by btangmu — APPROVED** [review]
Mark, probably best if this is merged before the DAIP whitespace one?

**Pull request merged**
