### PR TITLE
CLDR-14194 describe compound unit localization

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14194
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by macchiati** [comment]
Here is a first cut at the compound name name construction. As before, I think this is easier to review if it is accepted so that the html can be read at github.io rather than trying to make sense of raw HTML.

**Comment by macchiati** [comment]
If you are going to look at the raw HTML, I recommend ⚙️, split, hide whitespace differences.
I'd especially appreciate comments from people who've looked at the compound unit name formatting, like @hugovdm

**Comment by sffc** [comment]
Cool; we will work on implementing this for ICU 69.

**Review by srl295 — APPROVED** [review]
lgtm

**Review by hugovdm — COMMENTED** [review]
[/me hereby ticks this off on /my closed "review requests" list - pardon noise on old threads]

**Pull request merged**
