### PR TITLE
CLDR-14555 fix SQL warnings

### PR DESCRIPTION
**Pull request by srl295**
- restructure MailSender code, cleanup, delete dead code
- rollback() if no mail action. Otherwise resources are left to be cleaned up
- turn off DEBUG mode in DBUtils

### CODE REVIEW

**Review by btangmu — APPROVED** [review]
was it all about MailSender?

**Comment by srl295** [comment]
> was it all about MailSender?

I thought it might be something else, but it turned out to be only mailsender.

**Comment by btangmu** [comment]
> > was it all about MailSender?
> 
> I thought it might be something else, but it turned out to be only mailsender.

Great! I'll go ahead and merge this. BTW what's our new protocol -- if this PR fixed the ticket, is one of us supposed to close the ticket?

**Comment by srl295** [comment]
I’m going to update the template so there’s a checkbox. Yea , this fixes
the ticket.

**Pull request merged**
