### PR TITLE
CLDR-11585 Maven: Add tests, simplify pom setup

### PR DESCRIPTION
**Pull request by srl295**
CLDR-11585

after this, then https://sites.google.com/site/cldr/development/maven instructions should work to use maven (from the command line, at least).

-----

Rescoping this one to also include adding (via a shim) all tests (but not consolecheck).

### CODE REVIEW

**Comment by srl295** [comment]
the `githubicu` URL was defined at the wrong level.

**Comment by srl295** [comment]
without this, users will have to add something like this to ~/.m2/settings.xml:

```xml
      <repositories>
        <repository>
          <id>githubicu</id>
          <name>GitHub unicode-org/icu Apache Maven Packages</name>
          <url>https://maven.pkg.github.com/unicode-org/icu</url>
        </repository>
      </repositories>
```

**Comment by srl295** [comment]
I'll do a more complete test integration, this simply sublaunches the entire CLDR test suite as a single junit test.
It's also not configurable.

But, while 'ant' is still in the picture, i wanted to keep it simple.

**Comment by srl295** [comment]
Oops. Need to exclude TestShim from ant!

**Comment by srl295** [comment]
> Oops. Need to exclude TestShim from ant!

fixed

**Review by macchiati — APPROVED** [review]

**Pull request merged**
