### PR TITLE
CLDR-14184 further updates to statistics page

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14184
- turn x axis label to reduce crowding
- improve spacing along y axis
- improve wording in legend

update to #719

### CODE REVIEW

**Comment by macchiati** [comment]
Can you put a snapshot of what results with these changes? Otherwise the
turnaround is too slow.

Mark

**Comment by srl295** [comment]
> Can you put a snapshot of what results with these changes? Otherwise the turnaround is too slow.

stat_byday

stat_loc

**Comment by srl295** [comment]
@macchiati with commit 65edcab32d it's like this: 
image

**Comment by srl295** [comment]
the CI failure of ansible_lint is fixed in #729

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
It is still confusingly misaligned: eg unclear whether first bar belongs to af or aa. But I guess we can't fix that.

**Comment by srl295** [comment]
> It is still confusingly misaligned: eg unclear whether first bar belongs to af or aa. But I guess we can't fix that.

`aa` has ~0 votes. the first bar with any votes in it is `af`

**Comment by srl295** [comment]
ansible-lint status failure will be fixed in #729

**Comment by srl295** [comment]
@macchiati when smoketest finishes updating to  56a784aa5dc15bed3133297cdf886322eb04cfba  we can push to production.

**Comment by macchiati** [comment]
You can't tell that from the graph at all.

Mark

**Comment by srl295** [comment]
let's get our v38 stats from here, and then move to a new charting framework.

**Pull request merged**
