### PR TITLE
CLDR-16089 Remove periods from ordinal number formatters in languages that don't have this convention

### PR DESCRIPTION
**Pull request by grhoten**
CLDR-16089

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by allashashkina** [comment]
We should wait for Polish. Most likely, it will also needed to be removed. Waiting for a confirmation.

**Comment by grhoten** [comment]
Polish confirmed that "1250. raz" is an acceptable way to represent ordinals in digit form.

**Review by pedberg-icu — APPROVED** [review]
Thanks!

**Comment by btangmu** [comment]
@pedberg-icu is this supposed to be included in push to production today?

**Pull request merged**
