### PR TITLE
CLDR-14615 Modernize fix glitches: hide Statistics in gear menu, etc

### PR DESCRIPTION
**Pull request by btangmu**
-Remove unused return value for cldrInfo.show and its callers

-Remove unused import of cldrForum by cldrSurvey

-Fix Upload XML link in gear menu

-Hide Statistics in gear menu; no modern-compatible implementation yet

-Move refreshSingleRow from cldrSurvey to cldrTable, refactor with subroutines

-Add padding to Login button for Create and Login

-Remove some obsolete jsp (about/browse/statistics), remove links from index.jsp

-Format cldrCreateLogin.js

-Comments

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14615
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
more jsp deletion, great!

**Comment by btangmu** [comment]
@srl295 thanks for the review -- I just discovered a missing import, so I'll make another commit to this PR and ask for re-review shortly

**Review by srl295 — DISMISSED** [review]
lgtm but needs squash

**Comment by btangmu** [comment]
> lgtm but needs squash

Squashing, thanks!

**Review by srl295 — APPROVED** [review]
rslgtm on squash

**Pull request merged**
