### PR TITLE
CLDR-16135 Clean up examples for PersonNames

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-16135

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- Make the labels be italic
- Add section for foreign name & script

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
- Adjust tests

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by macchiati** [comment]
The examples now look like the following

_🟩 Native name and 🟩 script:_
Zendaya
Irene Adler
Mary Sue Watson
Bertie Wooster
_🟧 Foreign name, 🟩 native script:_
Sinbad
Käthe Müller
Zäzilia Stöber
Neele von Brühl
_🟧 Foreign name and 🟧 script:_
Єва Шевченко
太郎 山田

**Comment by btangmu** [comment]
it's getting this error:
`Error:    TestExampleGenerator.testPersonNamesGwen:47 Expected '>Person, Fred<' in the morass of <div class='cldr_example'><i>🟩 Native name and 🟩 script:</i></div><div class='cldr_example'><span class='cldr_substituted'>Zendaya</span></div><div class='cldr_example'><span class='cldr_substituted'>Person</span>, <span class='cldr_substituted'>Fred</span></div><div class='cldr_example'><span class='cldr_substituted'>Watson</span>, <span class='cldr_substituted'>Mary Sue</span></div><div class='cldr_example'><span class='cldr_substituted'>Wooster</span>, <span class='cldr_substituted'>Bertram Wilberforce</span></div><div class='cldr_example'><i>🟧 Foreign name, 🟩 native script:</i></div><div class='cldr_example'><span class='cldr_substituted'>Sinbad</span></div><div class='cldr_example'><span class='cldr_substituted'>Müller</span>, <span class='cldr_substituted'>Käthe</span></div><div class='cldr_example'><span class='cldr_substituted'>Stöber</span>, <span class='cldr_substituted'>Zäzilia</span></div><div class='cldr_example'><span class='cldr_substituted'>von Brühl</span>, <span class='cldr_substituted'>Ada Cornelia</span></div><div class='cldr_example'><i>🟧 Foreign name and 🟧 script:</i></div><div class='cldr_example'><span class='cldr_substituted'>Шевченко</span> <span class='cldr_substituted'>Єва</span> <span class='cldr_substituted'>Марія</span></div><div class='cldr_example'><span class='cldr_substituted'>山田トーマス太郎</span></div> ==> expected: <true> but was: <false>`

**Comment by macchiati** [comment]
Have to resolve conflicts with others

**Comment by macchiati** [comment]
Ready for review

**Review by btangmu — APPROVED** [review]

**Pull request merged**
