### PR TITLE
CLDR-10102 Seed latin

### PR DESCRIPTION
**Pull request by doublex**
CLDR-10102

Classical Roman numbers could only go as far as a million. Here we have had to use Neo-Latin term for billion. Minuta and secunda are Neo-Latin, too. Classical Latin could not measure more precisely than in hours. There is also no word for quarter in the sense used here, so we have used a neologism.

### CODE REVIEW

**Comment by doublex** [comment]
I don't understand this error since all children of `calendar` should match `months?,monthNames?,...`.

````
     [java]       Error: (TestBasic.java:149) error: The content of element type "calendar" must match "(alias|(months?,monthNames?,monthAbbr?,monthPatterns?,days?,dayNames?,dayAbbr?,quarters?,week?,am*,pm*,dayPeriods?,eras?,cyclicNameSets?,dateFormats?,timeFormats?,dateTimeFormats?,fields*,special*))".;	 SystemID: file:///home/runner/work/cldr/cldr/seed/main/la.xml;	 PublicID: null;	 LineNumber: 674;	 ColumnNumber: 15
     [java]       Error: (TestBasic.java:149) 	Can't read /home/runner/work/cldr/cldr/seed/main/la.xml	class org.xml.sax.SAXParseException	The content of element type "calendar" must match "(alias|(months?,monthNames?,monthAbbr?,monthPatterns?,days?,dayNames?,dayAbbr?,quarters?,week?,am*,pm*,dayPeriods?,eras?,cyclicNameSets?,dateFormats?,timeFormats?,dateTimeFormats?,fields*,special*))".
````

**Comment by srl295** [comment]
> I don't understand this error since all children of `calendar` should match `months?,monthNames?,...`.
> 
> ```
>      [java]       Error: (TestBasic.java:149) error: The content of element type "calendar" must match "(alias|(months?,monthNames?,monthAbbr?,monthPatterns?,days?,dayNames?,dayAbbr?,quarters?,week?,am*,pm*,dayPeriods?,eras?,cyclicNameSets?,dateFormats?,timeFormats?,dateTimeFormats?,fields*,special*))".;	 SystemID: file:///home/runner/work/cldr/cldr/seed/main/la.xml;	 PublicID: null;	 LineNumber: 674;	 ColumnNumber: 15
>      [java]       Error: (TestBasic.java:149) 	Can't read /home/runner/work/cldr/cldr/seed/main/la.xml	class org.xml.sax.SAXParseException	The content of element type "calendar" must match "(alias|(months?,monthNames?,monthAbbr?,monthPatterns?,days?,dayNames?,dayAbbr?,quarters?,week?,am*,pm*,dayPeriods?,eras?,cyclicNameSets?,dateFormats?,timeFormats?,dateTimeFormats?,fields*,special*))".
> ```

check the order of the children of `<calendar>`. 

Usually seed data is more minimal, and initial content is submitted via the Survey Tool

**Comment by doublex** [comment]
Thanks a lot.
This error message is not very verbose:
````
     [java]     TestLikelyAndDefaultConsistency {
     [java]       Error: (TestInheritance.java:306) Missing default content for: la  (no suggestion- no data)
     [java]     } (0.036s) FAILED (1 failure(s))
````

**Comment by srl295** [comment]
> Thanks a lot.
> This error message is not very verbose:
> 
> ```
>      [java]     TestLikelyAndDefaultConsistency {
>      [java]       Error: (TestInheritance.java:306) Missing default content for: la  (no suggestion- no data)
>      [java]     } (0.036s) FAILED (1 failure(s))
> ```

probably need to add `la_VA` to the defaultContent supplemental metadata.  You can file a separate ticket on the unclear message…

**Comment by doublex** [comment]
Should I modify `common/supplemental/supplementalMetadata.xml`?
I didn't expect that updating `seed/...` depends on  `common/...`.

**Comment by Liggliluff** [comment]
> `<pattern>M/d/y G</pattern>`
Does Latin really is the MDY short pattern? It doesn't match their long DMY pattern.

The abbrevated forms for large numbers are K/M/B/T. This does not match the long forms, and abbreviating the long forms might yield better results: M/Mn/Md/MMd, or mil/Mn/Md/mil Md

**Comment by doublex** [comment]
No, it does not fit MDY. The Roman calendar was different (kalends, nones, and ides).

Do you prefer `M/Mn/Md/MMd` or `mil/Mn/Md/mil Md`? (there will be some neologism though)

**Comment by Liggliluff** [comment]
@doublex I can't help with whichever is better. I have no experience in Latin, and only compare languages to see oddities. Considering Italian not using a thousand marker, maybe Latin should not use one either. So personally I like: 0 / 0 Mn / 0 Md / 0 mil Md

**Comment by srl295** [comment]
@doublex 

```
2020-08-21T20:12:08.5894597Z      [java]       Error: (TestInheritance.java:306) Missing default content for: la  (no suggestion- no data)
```

so,

1.  try adding `la_VA` to `<defaultContent>` in the `supplementalData.xml` file. that oughtta fix the above error.
2. please squash down to one commit whose first line is `CLDR-10102 … ` see our new guide https://github.com/unicode-org/cldr/blob/master/CONTRIBUTING.md
3. the ticket needs acceptance. let me see what i can do.

**Comment by doublex** [comment]
@srl295 
Thanks a lot. 

`supplementalData.xml` resides in `common/` - but this patch adds latin to `seed/` (that `seed/` depends on an update in  `common` is strange)

Do you want to:
a) Add latin to `seed/` and change `supplementalData.xml` in `common/`
b) Add latin to `common/` and change `supplementalData.xml`

I thought that squashing is done during merging?

**Comment by srl295** [comment]
> @srl295 
> 
> Thanks a lot. 
> 
> 
> 
> `supplementalData.xml` resides in `common/` - but this patch adds latin to `seed/` (that `seed/` depends on an update in  `common` is strange)
> 
> 
> 
> Do you want to:
> 
> a) Add latin to `seed/` and change `supplementalData.xml` in `common/`
> 
> b) Add latin to `common/` and change `supplementalData.xml`
> 
> 

(A). That the data is in seed doesn't invalidate the supplemental data. 


We're going to do away with the seed/ as a separate directory anyway. It's just a status. 




> 
> I thought that squashing is done during merging?


No. The "merge" is a single rebase. Please squash ahead of time.

**Comment by macchiati** [comment]
This data needs to be added as provisional.

Mark

**Comment by srl295** [comment]
thanks @doublex @Liggliluff

**Comment by pedberg-icu** [comment]
This had a problem with the placement of the draft attribute in standard date/time formats. I have fixed that as part of https://github.com/unicode-org/cldr/pull/692 since it was blocking my presubmission tests.

**Comment by doublex** [comment]
@pedberg-icu 
Sorry for the inconvenience

**Comment by JohnRDOrazio** [comment]
thank you all for taking interest in adding Latin to the proposed locales, I have started looking into this since I have been developing applications in PHP where Latin is one of the languages that needs to be supported by the application. However, since Linux systems haven't had support for Latin until now, neither `gettext` or any similar localization functions (`IntlDateFormatter`) work for Latin. So these definitions, along with a [proposed definition at glibc](https://sourceware.org/bugzilla/show_bug.cgi?id=24366) and [another at ubuntu](https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1955428?comments=all), will be quite useful to this end.

Considering however that Latin is associated with the Vatican as a geographical area, I would say that for most practical purposes, the definitions should primarily reflect ecclesiastical latin, and where alternate forms are supported, could use ancient / classical latin forms as the alternative. I have requested a consultation with the "Pontificia Academia Latinitatis" and with the "Pontificium Institutum Altioris Latinitatis" to get some input on this. As soon as I have some more information, I'll perhaps open a new ticket.

**Comment by doublex** [comment]
@JohnRDOrazio 
We also use it in an ecclesiastical environment. 
The problem: How to translate "seconds", "China" or "Javanese"?
You will end up with Neo-Latin.

**Comment by JohnRDOrazio** [comment]
@doublex of course neologisms are needed, I wasn't referring so much to neologisms, rather the days of the week for example are, in ecclesiastical latin, referred to as "Dominica, Feria II, Feria III, Feria IV... Sabbatum", whereas "dies Lunae, dies Martis, dies Mercurii etc." are used in classical latin.

The Pontificia Academia Latinitatis of course also coins a number of neologisms, think of the Papal encyclicals that talk about modern things that didn't exist before, of course there is a need to coin terms to express new ideas or objects that have no references in classical latin. In these regards, ecclesiastical latin is somewhat of a "living language", because new terms are coined continuously.

**Comment by doublex** [comment]
The are there (flagged as `variant`):
https://github.com/unicode-org/cldr/blob/main/seed/main/la.xml#L522

Fr. Reginald Foster would have liked that very much.

**Comment by JohnRDOrazio** [comment]
Actually they aren't there, only "Dominica" is flagged as variant. There is no "Feria II", "Feria III". For example, in the Roman Missal, "Ash Wednesday" is referred to as "Feria IV Cinerum". Considering that usage on an operating system should reflect practical applications first and foremost, I believe "Feria II", "Feria III" etc. should be defined. Then I suppose you could have "dies Lunae", "dies Martis" as a variant for historical reference.

**Comment by doublex** [comment]
You are right. 
The latin breviary (1970) and the missale (1962) calls Tuesday `Feria II`, Wednesday `Feria III`, ...

Only `Dies Domini` and `Dies Sabbati` are there:
https://github.com/unicode-org/cldr/blob/main/seed/main/la.xml#L529

Would be great if the Pontificia Academia Latinitatis could add them.

**Pull request merged**
