### PR TITLE
CLDR-16137 revert: Replace prefix and suffix

### PR DESCRIPTION
**Pull request by srl295**
This reverts commit 4608db311f785a139980e5e5914294214d202191 from #2553

CLDR-16137

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
the problem is that #2553 was not rebased when #2551 was merged.
If it had been rebased on main, the pR for #2553 would have failed.

This simply reverts #2554 until @macchiati  can fix it

**Comment by srl295** [comment]
something that should be mentioned is that our long build times discourage actively requesting a rebuild.

**Comment by macchiati** [comment]
I can't fix today. 2553 if properly rebased should work.

Can someone try that out?

**Comment by srl295** [comment]
There isn’t a merge conflict.

Tried the rebase (2553 on top of 2551) and it fails.

-s

**Comment by srl295** [comment]
I filed CLDR-16149 to make the error message less cryptic.  Tried to debug the issue and wasn't able to figure the problem out.

**Review by btangmu — APPROVED** [review]

**Pull request merged**
