### PR TITLE
CLDR-17856 nan and hak in Taiwan

### PR DESCRIPTION
**Pull request by DavidLRowe**
CLDR-17856

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
The data changes for language population per region need to be made in the supplemental XML file

**Review by macchiati — CHANGES_REQUESTED** [review]
The changes need to be made in the supplemental XML file.

**Comment by srl295** [comment]
> The changes need to be made in the supplemental XML file.

they are made in country_language_population.tsv first, and then `ShowLanguages` is run to update the xml.

**Comment by srl295** [comment]
probably wait until #3952 is merged before this goes in - running ConvertLanguageData to include the xml update.

**Review by srl295 — APPROVED** [review]
@macchiati how about we change the spreadsheet, and i'll regenerate the xml as part of my BRS?

**Comment by macchiati** [comment]
> @macchiati how about we change the spreadsheet, and i'll regenerate the xml as part of my BRS?

You mean, change the tsv? Ok if so.

**Comment by srl295** [comment]
> > @macchiati how about we change the spreadsheet, and i'll regenerate the xml as part of my BRS?
> 
> You mean, change the tsv? Ok if so.

Yes, merge this PR, and then the XML will be regenerated as part of BRS.

**Comment by DavidLRowe** [comment]
@macchiati It seems you need to modify your request for changes.

**Pull request merged**
