### PR TITLE
CLDR-13139 Upgrade Tomcat; preliminary fixes

### PR DESCRIPTION
**Pull request by btangmu**
-In cldr-apps-playbook.yml, fix cldr-trunk ownership: become_user: surveytool

-In org.eclipse.core.resources.prefs, add encoding//src/main/resources=UTF-8

-In org.eclipse.wst.common.component, rename to cldr-code-39.0-SNAPSHOT.jar

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13139
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
some overlap with https://github.com/unicode-org/cldr/pull/851

**Review by srl295 — APPROVED** [review]
All lgtm but needs rebase. Also the readme ?

**Comment by btangmu** [comment]
> All lgtm but needs rebase. Also the readme ?

Right about the rebase, I'll fix that...

I have changes to the readme in another branch along with more extensive changes, see draft PR: https://github.com/unicode-org/cldr/pull/854

**Comment by btangmu** [comment]
Let's just skip this and go straight to tomcat 9 with https://github.com/unicode-org/cldr/pull/856

**Pull request closed without merging**
