### PR TITLE
CLDR-14798 first day of week is Monday in PRC

### PR DESCRIPTION
**Pull request by iamCristYe**
CLDR-14798
- [x] This PR completes the ticket.

See also
CLDR-13690
CLDR-13648
CLDR-11510

### CODE REVIEW

**Comment by alick** [comment]
Do we know why the build & check status are stuck? The PR lgtm.

**Comment by iamCristYe** [comment]
@srl295 @pedberg-icu Is anyone going to review this?

**Comment by srl295** [comment]
@iamCristYe as you know there was a response on the ticket a couple of days ago. I don't see a response to your response yet.

**Comment by iamCristYe** [comment]
@srl295 I don't see any recent response... Not sure what you're talking about.

**Comment by stenshamn** [comment]
This is moot by way of https://github.com/unicode-org/cldr/pull/2208

**Comment by iamCristYe** [comment]
So no reviews, no updates for months and then an identical PR merged... I don't get it 😅

**Comment by iamCristYe** [comment]
> > So no reviews, no updates for months and then an identical PR merged... I don't get it 😅
> 
> So, thanks for contributing to CLDR to be sure. But, note that [CLDR-11510](https://unicode-org.atlassian.net/browse/CLDR-11510) was filed in 2018 and was already under investigation—that's where the discussion was happening. [CLDR-14798](https://unicode-org.atlassian.net/browse/CLDR-14798) was marked as a duplicate. It wasn't a matter of reviewing this PR as much as of reviewing and verifying the information.
> 
> Does that help?

I see. Then maybe next time, duplicate JIRA issues and GitHub PR against them should be closed promptly.

**Comment by srl295** [comment]
My mistake. I read 2021 as 2022.

**Pull request closed without merging**
