### PR TITLE
CLDR-16246 update PR template to allow multi commits by default

### PR DESCRIPTION
**Pull request by srl295**
CLDR-16246

Many PRs are landed which fail the 'single commit check'.  It would be better to quell this error so that we can see when there are real errors.

Examples: 
#2616 #2575 #2578 #2562

- [x] This PR completes the ticket.

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Review by btangmu — APPROVED** [review]
OK, though I still prefer to squash "manually" to see the results before merging

**Comment by srl295** [comment]
> OK, though I still prefer to squash "manually" to see the results before merging

it doesn't prevent that.

**Comment by srl295** [comment]
@btangmu  in fact you can still remove the ALLOW line from a PR if you prefer,this just changes the default

**Comment by btangmu** [comment]
that's good to know!

**Pull request merged**
