### PR TITLE
CLDR-17830 Update release page

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17830

First cut for spec beta

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Hi, I fleshed out the spec section, and added some items from the TC meeting.

**Comment by macchiati** [comment]
I'd like to go ahead and merge this, and we can have follow-up PRs to tune. Can someone approve?

**Comment by macchiati** [comment]
@srl295 @btangmu The 'build' for the release page is failing, with cryptic warnings & an error:
```
Warning: Failed to download action 'https://internal-api.service.iad.github.net/repos/actions/setup-java/tarball/b36c23c0d998641eff861008f374ee103c25ac73'. Error: Name or service not known (internal-api.service.iad.github.net:443)
Warning: Back off 19.088 seconds before retry.
Warning: Failed to download action 'https://internal-api.service.iad.github.net/repos/actions/setup-java/tarball/b[36](https://github.com/unicode-org/cldr/actions/runs/11039467098/job/30665084462?pr=4074#step:1:40)c23c0d998641eff861008f374ee103c25ac73'. Error: Name or service not known (internal-api.service.iad.github.net:443)
Warning: Back off 13.[37](https://github.com/unicode-org/cldr/actions/runs/11039467098/job/30665084462?pr=4074#step:1:41)7 seconds before retry.
Error: Name or service not known (internal-api.service.iad.github.net:443)
```

**Comment by srl295** [comment]
> I'd like to go ahead and merge this, and we can have follow-up PRs to tune. Can someone approve?

looking

**Comment by srl295** [comment]
> @srl295 @btangmu The 'build' for the release page is failing, with cryptic warnings & an error:
> 
> ```
> Warning: Failed to download action 'https://internal-api.service.iad.github.net/repos/actions/setup-java/tarball/b36c23c0d998641eff861008f374ee103c25ac73'. Error: Name or service not known (internal-api.service.iad.github.net:443)
> Warning: Back off 19.088 seconds before retry.
> Warning: Failed to download action 'https://internal-api.service.iad.github.net/repos/actions/setup-java/tarball/b[36](https://github.com/unicode-org/cldr/actions/runs/11039467098/job/30665084462?pr=4074#step:1:40)c23c0d998641eff861008f374ee103c25ac73'. Error: Name or service not known (internal-api.service.iad.github.net:443)
> Warning: Back off 13.[37](https://github.com/unicode-org/cldr/actions/runs/11039467098/job/30665084462?pr=4074#step:1:41)7 seconds before retry.
> Error: Name or service not known (internal-api.service.iad.github.net:443)
> ```

sounds like a network issue though https://www.githubstatus.com/ clean

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
> sounds like a network issue though https://www.githubstatus.com/ clean

restarted the build

**Comment by srl295** [comment]
@macchiati seems to have gotten past whatever it was

**Comment by macchiati** [comment]
Thanks!

**Pull request merged**
