### PR TITLE
CLDR-16633 kbd: use NMTOKEN for ids

### PR DESCRIPTION
**Pull request by srl295**
CLDR-16633

- [X] This PR completes the ticket.

thanks @eggrobin 

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by srl295** [comment]
@macchiati  @eggrobin  comments?  OK for this release?

**Review by macchiati — DISMISSED** [review]
I think we need to discuss this. NMToken is very broad, and includes a huge amount of garbage. Would be much better to restrict to Unicode identifiers (UAX 31)

**Comment by srl295** [comment]
@macchiati please discuss, see comments in the ticket.  I was also proposing that for *CLDR* repository data, we could verify that keyboards only use UAX31.  This adds a burden on implementations and ties it to a specific Unicode version.

The proposal, as noted in discussion on the ticket, is to expand from ASCII to NMTOKEN for this release, with a note in the spec to revisit next time.

**Comment by miloush** [comment]
@macchiati just to note NMTOKEN was a compromise between making it more restricted but also more open. This is just a dictionary with a string key to be looked up. What is the concern of including arbitrary (or in this case NMTOKEN) characters in the key?

**Comment by srl295** [comment]
I will add a test here that verifies that all keyboards actually conform to UAX 31

**Comment by mcdurdin** [comment]
@eggrobin thank you for the detail on NMTOKEN -- really helpful background!

**Comment by srl295** [comment]
@macchiati ping?

**Comment by srl295** [comment]
keeping the old keyboard.dtd file plays havoc with git merges

**Pull request merged**
