### PR TITLE
CLDR-14540 Modernize Vetting Participation

### PR DESCRIPTION
**Pull request by btangmu**
-Revise cldrVettingParticipation.js so it works

-SurveyVettingParticipation.java delete dead code, make some items final/private, reformat

-Add cache-busting extension for bundle and css in SurveyTool.java

-Comments

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14540
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
There's still a problem with the css -- the boxes for the per-user info -- to be handled in a subsquent pr...

**Comment by btangmu** [comment]
I've just started getting "[ERROR   ] CWWKF0001E: A feature definition could not be found for concurrent-1.0"

then SurveyMain.init runs, but SurveyMain.doStartup never runs

not related to this ticket, maybe related to https://github.com/unicode-org/cldr/pull/1066

anyway I'm closing this PR to avoid confusion until development environment is working

**Comment by srl295** [comment]
> I've just started getting "[ERROR ] CWWKF0001E: A feature definition could not be found for concurrent-1.0"
> 
> then SurveyMain.init runs, but SurveyMain.doStartup never runs
> 
> not related to this ticket, maybe related to #1066

Can you re-run the `liberty:deploy` step that cleared up the localConnector issue?  That should probably be rerun when pulling.

> anyway I'm closing this PR to avoid confusion until development environment is working

OK…

**Comment by btangmu** [comment]
"re-run the liberty:deploy step" -- ok, I'm working on that -- right now my Eclipse is completely broken, I'm re-installing...

**Comment by btangmu** [comment]
@srl295 btw is eclipse currently working for you?

**Comment by srl295** [comment]
> @srl295 btw is eclipse currently working for you?

yes.

> completely broken, I'm re-installing

What was broken? Was it just that doStartup never runs?  liberty:deploy should fix that. Or something else?

**Comment by btangmu** [comment]
slack?

**Pull request closed without merging**
