### PR TITLE
CLDR-16348 Add Gregorian fallback eras in Japanese calendar

### PR DESCRIPTION
**Pull request by sffc**
CLDR-16348

- [ ] This PR completes the ticket.

I wanted to open a PR for this small subpart of CLDR-16185 to get early feedback.

ALLOW_MANY_COMMITS=true

CC @Manishearth @FrankYFTang @yumaoka

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by srl295** [comment]
@sffc sorry. i don't see this listed in https://unicode-org.atlassian.net/browse/CLDR-16185 and in any event, it seems like it's as you say only a very small part.

I would suggest that you open a subtask of CLDR-16185 (you can go ahead and accept a subtask without extra permission) for the 'small part', including justification, and target this PR there.

**Review by Manishearth — APPROVED** [review]

**Review by macchiati — CHANGES_REQUESTED** [review]
This is not what the committee agreed to.

**Comment by sffc** [comment]
> I would suggest that you open a subtask (hit 'create subtask' in jira) of [CLDR-16185](https://unicode-org.atlassian.net/browse/CLDR-16185) (you can go ahead and accept a subtask without extra permission) for the 'small part', including justification, and target this PR there.

Done. The subtask is New, not Accepted. Should I accept it?

> This is not what the committee agreed to.

Updated according to the discussion last week.

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
Note: the tests might hiccup on the negative numbers, and need fixing. 
We will also need a ticket on the ICU side to adjust the CLDR data conversion to skip these (or maybe this would be done as a part of the integration work, @pedberg-icu ?)

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
I folded this in with #2665.

**Pull request closed without merging**
