### PR TITLE
CLDR-11050 json: add annotations

### PR DESCRIPTION
**Pull request by srl295**
CLDR-11050

- new packages cldr-annotations-full and cldr-annotations-derived-full

example:

```json
      "😀": {
        "default": [
          "jidħaq ħafna",
          "wiċċ",
          "wiċċ jidħak ħafna"
        ],
        "tts": [
          "wiċċ jidħak ħafna"
        ]
      },
```

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by srl295** [comment]
Ugh.  Breaks on annotations for `'` etc.

**Comment by macchiati** [comment]
Ah, ugly. Will have to escape those for JSON.

Mark

**Comment by srl295** [comment]
> Ah, ugly. Will have to escape those for JSON.

worse, will have to escape anything that chokes xpath ( `'[]@/"` )

**Comment by srl295** [comment]
```json
      "U+27": {
        "default": [
          "apostrophe",
          "quote",
          "single quote",
          "typewriter apostrophe"
        ],
        "tts": [
          "typewriter apostrophe"
        ]
      },
```

**Comment by srl295** [comment]
```json
      "'": {
        "default": [
          "apostrophe",
          "quote",
          "single quote",
          "typewriter apostrophe"
        ],
        "tts": [
          "typewriter apostrophe"
        ]
      },
      "\\": {
        "default": [
          "backslash",
          "reverse solidus",
          "whack"
        ],
        "tts": [
          "backslash"
        ]
      },
```

Funny thing,. ,there's no annotation for `"` (U+0022) - it would have made an interesting test case!

**Comment by srl295** [comment]
I end up escaping the xpath temporarily to `//ldml/annotations/annotation[@cp="U+5B"][@type="tts"]` and then unescaping as the JSON is written, but only for the `annotations` and `annotationsDerived` runtypes.

**Comment by srl295** [comment]
sorry, need to test another couple of cases

**Comment by srl295** [comment]
had broken on certain draft items in some locales

**Comment by srl295** [comment]
[cldr-annotations-beta3-draft.zip](https://github.com/unicode-org/cldr/files/5419292/cldr-annotations-beta3-draft.zip)
data snapshot enclosed for review

**Review by macchiati — APPROVED** [review]

**Pull request merged**
