### PR TITLE
CLDR-15785 Pin the progress at 99 percent if EMP greater than 0

### PR DESCRIPTION
**Pull request by btangmu**
-Revise percent to 99 as specified in the ticket

-Revise both Priority Items Summary (java) and Locale Completion meter (js)

-This is not a logical long-term solution

CLDR-15785

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
Screenshot, running locally, having introduced an error intentionally:
image

**Review by srl295 — APPROVED** [review]

**Review by petariordanoo72 — APPROVED** [review]

**Comment by btangmu** [comment]
@macchiati the ticket isn't accepted yet -- as I asked in email, is it OK to accept it? I'll wait for your approval...

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
Yes, you can accept.

**Comment by btangmu** [comment]
> Yes, you can accept.

OK, it's merged. Maybe after vetting is closed, when it won't rock the boat too much, the code should be changed to show 0% rather than 99%... and the code should be cleaned up and clarified.

**Pull request merged**
