### PR TITLE
CLDR-14581 Change plural rule format from 2e6 to 2c6

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14581
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by macchiati** [comment]
Made the file change, but didn't run the tests locally, so will find out soon. It might need the ICU change from Elango merged before it will run.

**Comment by macchiati** [comment]
Yup, fails in com.ibm.icu.text.PluralRules$FixedDecimal.parseDecimalSampleRangeNumString(PluralRules.java:862)

**Comment by macchiati** [comment]
Hmmm. I guess this pulls in the right ICU version, so we are ok.

**Review by echeran — APPROVED** [review]
Peter gave the go-ahead and merged the ICU change dependency in [ICU PR 1624](https://github.com/unicode-org/icu/pull/1624), and this rule change LGTM.

**Comment by pedberg-icu** [comment]
> Peter gave the go-ahead and merged the ICU change dependency in [ICU PR 1624](https://github.com/unicode-org/icu/pull/1624), and this rule change LGTM.

BUT: I have not copied the ICU with that change back to CLDR yet. I am working on a PR for that but it has some test failures.

**Comment by pedberg-icu** [comment]
> > Peter gave the go-ahead and merged the ICU change dependency in [ICU PR 1624](https://github.com/unicode-org/icu/pull/1624), and this rule change LGTM.
> 
> BUT: I have not copied the ICU with that change back to CLDR yet. I am working on a PR for that but it has some test failures.

OK, [PR-1102](https://github.com/unicode-org/cldr/pull/1102) updates the ICU4J libraries in CLDR to include Elango's fix [ICU-PR-1624](https://github.com/unicode-org/icu/pull/1624) to make compact notation 'c' behave like 'e' in FixedDecimal.

**Review by pedberg-icu — APPROVED** [review]

**Pull request merged**
