### PR TITLE
CLDR-13771 workaround ansible-lint failing

### PR DESCRIPTION
**Pull request by srl295**
CLDR-13771
- see https://github.com/ansible-collections/community.kubernetes/issues/135#issuecomment-661189940
- workaround by not setting a version

### CODE REVIEW

**Comment by srl295** [comment]
- also, lint all playbooks
- also, use a specific hash of the ansible action, since it's not otherwise versioned.

**Comment by srl295** [comment]
^ seems to work.  This ansible lint job passed, where others have been failing for the past few hours.

FYI @btangmu @macchiati in case you see 'ansible lint' failures, this fixes it.

**Comment by srl295** [comment]
failure was:

```
+ override_python_packages
+ [[ -n ansible==2.9
ansible-lint==4.2.0
 ]]
+ pip install ansible==2.9 ansible-lint==4.2.0
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible==2.9
  Downloading ansible-2.9.0.tar.gz (14.1 MB)
Collecting ansible-lint==4.2.0
  Downloading ansible_lint-4.2.0-py2.py3-none-any.whl (57 kB)
```

**Review by echeran — APPROVED** [review]
LGTM.  Seems straightforward enough, and this is a good change -- just using a snapshot of the action that effectively fixes in place the version of Ansible being used.  FWIW, it looks like they pushed [tags for the GH action](https://github.com/ansible/ansible-lint-action/tags).

**Comment by srl295** [comment]
> LGTM. Seems straightforward enough, and this is a good change -- just using a snapshot of the action that effectively fixes in place the version of Ansible being used. FWIW, it looks like they pushed [tags for the GH action](https://github.com/ansible/ansible-lint-action/tags).

yes, but 83 commits since that tag https://github.com/ansible/ansible-lint-action/compare/v4.1.0...master

**Review by btangmu — APPROVED** [review]
Ideally there might be a comment here clarifying the magic number, linking to https://github.com/ansible/ansible-lint-action/tree/6c8c14186662e43effbe39a678950896a46799ad

Maybe add that later, if this isn't replaced soon

**Pull request merged**
