### PR TITLE
CLDR-15318 Add alt value for TR territory name

### PR DESCRIPTION
**Pull request by AEApple**
CLDR-15318

Add alt value for TR territory name

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by AEApple** [comment]
I added an alt value similar to other territories. Please let me know if there is anything further I need to do. Thanks!

**Comment by macchiati** [comment]
Taking the liberty of merging now.

**Comment by srl295** [comment]
ok - took the liberty of deleting the branch

**Comment by macchiati** [comment]
Yes, we need to consider the magic 'remove merged branches' switch.

**Pull request merged**
