### PR TITLE
CLDR-14093 CLDR 38 BRS A11

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14093

continuation of PR #662 by @btangmu 

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — DISMISSED** [review]

**Comment by srl295** [comment]
These warnings remain. However, if these suggestions were taken, then TestValidity fails.
```
   TestLstrConsistency       current=<languageAlias type="drh" replacement="mn" reason="deprecated"/> <!-- Darkhat ⇒ Mongolian -->
     lstr=<languageAlias type="drh" replacement="khk" reason="deprecated"/> <!-- Darkhat ⇒ Halh Mongolian -->
     current=<languageAlias type="drw" replacement="fa_af" reason="deprecated"/> <!-- Darwazi ⇒ Dari -->
     lstr=<languageAlias type="drw" replacement="prs" reason="deprecated"/> <!-- Darwazi ⇒ Dari -->
     current=<languageAlias type="tnf" replacement="fa_af" reason="deprecated"/> <!-- Tangshewi ⇒ Dari -->
     lstr=<languageAlias type="tnf" replacement="prs" reason="deprecated"/> <!-- Tangshewi ⇒ Dari -->
  (0.351s) ALERT (1 warning(s))
   TestUnits (0.014s) ALERT (65 warning(s))
 } (0.421s) ALERT (66 warning(s))
TestSupplementalInfo/TestAliases
```

**Comment by macchiati** [comment]
I looked at the conflicts, and I think we want to keep both sets of lines.

**Comment by srl295** [comment]
@macchiati kept both, rebased, pushed.

**Comment by srl295** [comment]
@macchiati I still have some tasks on A11, working on those now

**Comment by macchiati** [comment]
sounds good. will watch for completion.
Mark

**Comment by srl295** [comment]
@macchiati all steps done (not too bad!), just waiting on tests. 

I'm keeping it 2 commits to preserve/credit @btangmu 's stopping point.

**Pull request merged**
