### PR TITLE
CLDR-15126 Bogus xpath warning when press Previous or Next button

### PR DESCRIPTION
**Pull request by btangmu**
-In cldrSurvey.chgPage set id to null to prevent warning when that id is not found on new page

CLDR-15126

- [x] This PR completes the ticket.

### CODE REVIEW

**Review by srl295 — APPROVED** [review]

**Comment by macchiati** [comment]
A question: is the ID not found because of the coverage level? Or is some
underlying problem really there (eg mapping from ID to page is failing)?
Mark

**Comment by btangmu** [comment]
@macchiati you asked "is the ID not found because of the coverage level? Or is some
underlying problem really there (eg mapping from ID to page is failing)?"

In the context of Previous/Next buttons, the ID -- identifying a row (xpath) -- is not found because we've switched sections and that row isn't in the new section, it was in the old section

**Comment by macchiati** [comment]
got it, thanks!
Mark

**Comment by srl295** [comment]
I added a ’steven recommend’ column

**Pull request merged**
