### PR TITLE
CLDR-17126 Update CLDR segment tailorings to reflect ICU 74 word break changes

### PR DESCRIPTION
**Pull request by pedberg-icu**
CLDR-17126

- [x] This PR completes the ticket.

Update CLDR segmentation tailorings to reflect word break tailorings updates in ICU 74 (CLDR 44 did not make any tailoring updates that need to be synced to ICU).

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
Can we get a link to a ticket with the ICU side changes and rationale? (probably should go in this ticket)

**Comment by pedberg-icu** [comment]
> Can we get a link to a ticket with the ICU side changes and rationale? (probably should go in this ticket)

The relevant ICU tickets are:
- First [ICU-22112](https://unicode-org.atlassian.net/browse/ICU-22112) word break updates for @,colon; colon tailorings for fi,sv
- Then [ICU-22360](https://unicode-org.atlassian.net/browse/ICU-22360) revert portions of ICU-22112 which included @ in ALetter for wordbreak, update tests

I will add this to the ticket as well.

**Review by markusicu — APPROVED** [review]
rslgtm

@eggrobin

**Comment by eggrobin** [comment]
Scripsit @markusicu
> @eggrobin

Should we upstream these root tailorings to UAX29? (In which case a PAG issue needs to be filed; at a glance we would probably do that by changing the Word_Break property of the characters involved, though I would need to look at the context more closely to summarize it for a recommendation.)

**Comment by markusicu** [comment]
> Should we upstream these root tailorings to UAX29? (In which case a PAG issue needs to be filed; at a glance we would probably do that by changing the Word_Break property of the characters involved, though I would need to look at the context more closely to summarize it for a recommendation.)

--> https://github.com/unicode-org/properties/issues/187

**Pull request merged**
