### PR TITLE
CLDR-17235 Organize conformance references

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17235

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
This is a work in progress; will flesh out more tonight. If you do have some time, please look it over. My goal is an improvement on what is there, recognizing that it is not the final picture.

(I have some ideas for how to improve the organization, etc., but that would extend past what we can do this release.)

**Comment by macchiati** [comment]
Also needs copy editing for typos, stray punctuation, etc.

**Comment by pedberg-icu** [comment]
I think this is a great improvement. I have not noticed typos etc but will take another look later tonight.

**Comment by macchiati** [comment]
Thanks!

**Comment by macchiati** [comment]
Can someone rubber stamp this, so that the core of the content is there? I can follow up with another PR for typos, wording, etc?

**Review by pedberg-icu — APPROVED** [review]

**Comment by pedberg-icu** [comment]
> Can someone rubber stamp this, so that the core of the content is there? I can follow up with another PR for typos, wording, etc?

@macchiati I approved this, looks good!

**Pull request merged**
