### PR TITLE
CLDR-17461 Forum posts in vetting view, change icon style

### PR DESCRIPTION
**Pull request by btangmu**
-Add margins and orange/green padding around 👁️‍🗨️/💬 icons, to make them easier to notice and distinguish

CLDR-17461

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by btangmu** [comment]
image

**Review by macchiati — APPROVED** [review]
These would definitely increase the visibility. I think the open forum posts are more interesting and need more highlight, so we might play a bit with the colors, but that can happen in a later PR.

**Review by srl295 — APPROVED** [review]
Also I noticed that the open/closed forum posts symbols show up even when not logged in.  Not sure that's intentional, i can add a comment to the ticket if you want

**Comment by btangmu** [comment]
> even when not logged in

@srl295 there are comments about that in the ticket. I'm awaiting a decision whether the icons need to be hidden depending on user status (logged in? permission to view forum for the given locale?)

**Pull request merged**
