### PR TITLE
CLDR-13025 Adding rewriting rules to fix the list disjunction rules for Spanish

### PR DESCRIPTION
**Pull request by younies**
Language.

##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13025
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by sffc** [comment]
Can you give a pointer to the latest design doc?  Did you get it approved by CLDR TC?

Check that indentation is consistent with the rest of the section you are editing.

**Comment by younies** [comment]
I got the approval from Mark Davis to change those rules.

**Comment by macchiati** [comment]
This is not yet ready for review, so preliminary at this point.

{phone}

**Comment by macchiati** [comment]
This is too preliminary; need design doc worked out.

**Pull request closed without merging**
