### PR TITLE
CLDR-15071 add origin attribute for likely subtags from SIL

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-15071

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Feel free to merge if the tests and review pass

**Review by srl295 — APPROVED** [review]

**Comment by macchiati** [comment]
@srl295 I'm getting an error in the json test, at https://github.com/unicode-org/cldr/actions/runs/4117800043/jobs/7109547694#step:16:165

From the code it looked like the obvious answer is to add "origin" to line 251 of LdmlConvertRules/
 
    public static final ImmutableSet<String> IGNORABLE_NONDISTINGUISHING_ATTR_SET = ImmutableSet.of("draft", "references", "origin");

But that didn't help. (Note: we should probably be suppressing @METADATA from the DTD from being emitted.)

**Comment by srl295** [comment]
> @srl295 I'm getting an error in the json test, at https://github.com/unicode-org/cldr/actions/runs/4117800043/jobs/7109547694#step:16:165
> 
> 

I can't look right now but I will soon 

> 
> From the code it looked like the obvious answer is to add "origin" to line 251 of LdmlConvertRules/
> 
>  
> 
>     public static final ImmutableSet<String> IGNORABLE_NONDISTINGUISHING_ATTR_SET = ImmutableSet.of("draft", "references", "origin");
> 
> 
> 
> But that didn't help. (Note: we should probably be suppressing @METADATA from the DTD from being emitted.)

There's a ticket for deriving all from annotations and removing the special json static tables.

**Comment by macchiati** [comment]
I made another change to the test, and it works locally. So trying it out
on the server.

**Review by pedberg-icu — APPROVED** [review]

**Comment by srl295** [comment]
Later change looks good too

**Pull request merged**
