### PR TITLE
CLDR-6396 Combine seed and common (#2491)

### PR DESCRIPTION
**Pull request by btangmu**
-Move all files from seed to common

-Add README.md in seed and its subdirectories

-Fix failing units tests; new StandardCodes.isLocaleAtLeastBasic, per related ticket CLDR-16117

-Fix a confusing warning message

-For now, seed/rbnf/nci.xml remains in seed; it is in rbnf but has no seed locale! Someone should create a stub for it at least

CLDR-6396

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
this is to merge from the feature branch CLDR-6396-combine-seed-common into main

**Comment by btangmu** [comment]
@srl295 I'm not sure what to do about "Commit 8748ec2 is for CLDR-16117, but the PR is for CLDR-6396" -- if we squash, will that go away? Alternatively we could just make a new pr for merging the feature branch back into main...

**Comment by srl295** [comment]
Just let it squash and keep it in the commit message

**Comment by btangmu** [comment]
> Just let it squash and keep it in the commit message

I'm not sure what you mean? Manually squash, or let it automatically squash?

Normally if I see the red x "single-commit -- This PR has 7 commits; consider squashing", I squash it to one commit "manually" (in the github gui) and I update the commit message manually as part of that squashing procedure. I'm not sure though whether by "just let it squash" you mean to let github produce its own commit message?

Anyway I've made it ready for review. You're more than welcome to merge it yourself if you have a particular way in mind :-)

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
> > Just let it squash and keep it in the commit message
> 
> I'm not sure what you mean? Manually squash, or let it automatically squash?
> 
> Normally if I see the red x "single-commit -- This PR has 7 commits; consider squashing", I squash it to one commit "manually" (in the github gui) and I update the commit message manually as part of that squashing procedure. I'm not sure though whether by "just let it squash" you mean to let github produce its own commit message?

I mean squash it by whatever process you want.  

> Anyway I've made it ready for review. You're more than welcome to merge it yourself if you have a particular way in mind :-)

No. Other than mentioning [CLDR-16117](https://unicode-org.atlassian.net/browse/CLDR-16117) somewhere as it is related.

**Review by srl295 — APPROVED** [review]
Rubber stamp lgtm since it was just a squash

**Pull request merged**
