### PR TITLE
CLDR-17265 Document special script codes

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17265

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by srl295** [comment]
It's a good improvement to document this, but just to note that CLDR-15611 discussed supplemental data and not just docs.

build failure will be fixed by rebasing once #3595  merges

**Comment by macchiati** [comment]
Notes: 
@markusicu @pedberg-icu we can tweak this section further in subsequent PRs. 
@srl295 This is just base documentation of the meanings.. We don't have yet a conclusion on CLDR-15611 regarding supplemental data.

**Comment by roozbehp** [comment]
I think this list is missing "Aran" (Arabic Nastaliq).

**Comment by macchiati** [comment]
It's there. Look at the rich text version

**Comment by srl295** [comment]
> It's there. Look at the rich text version
>> I think this list is missing "Aran" (Arabic Nastaliq)

Specifically,

https://github.com/unicode-org/cldr/blob/b1c3e67d09211b8344842f70d39ccd92d8735eff/docs/ldml/tr35.md?plain=1#L724

**Pull request merged**
