### PR TITLE
CLDR-13596 BRS Task A03 - Change to -z FINAL_TESTING

### PR DESCRIPTION
**Pull request by JCEmmons**
[CLDR-13596]

Switch over to -z FINAL_TESTING for data checks

[CLDR-13596]: https://unicode-org.atlassian.net/browse/CLDR-13596

### CODE REVIEW

**Comment by pedberg-icu** [comment]
This of course results in a bunch of new errors. Should we fix them as part of this PR or just merge this as is and then distribute and fix the errors separately?

**Comment by srl295** [comment]
Probably should fix aspart of this PR (again a good candidate for multiple PRs)

**Comment by macchiati** [comment]
I put some recommendations in
https://docs.google.com/spreadsheets/d/101kMT3N4q1eEPS3ujd7zfbsMr50Q0v7k8DEIR4SLPG0/edit#gid=0

There are 66 errors; the usual kinds of problems. I think all can be fixed
by deletion, so straightforward if somewhat tedious.

I agree on fixing them before committing.

I'm booked with my BRS and a couple of data bugs, but if others can help
get this done (I assume the PR allows others to modify...) it will keep
from delaying the release.

Mark

**Comment by JCEmmons** [comment]
I'm working on these this evening.  Will finish in the AM...

**Comment by macchiati** [comment]
Thanks John!

Mark

**Pull request merged**
