### PR TITLE
CLDR-15101 Support for Ethiopic-Ethiopic (Gurage) Transliteration

### PR DESCRIPTION
**Pull request by dyacob**
CLDR-15101

- [ ] This PR completes the ticket.

### CODE REVIEW

**Review by btangmu — APPROVED** [review]
LGTM! Plus one for having an extensive test (8,532 lines) -- I'm not sure if we have any limits or guidelines on test size.

Some characters such as 1E7E8 𞟨 ETHIOPIC SYLLABLE GURAGE HHWA don't have fonts on my computer; their usage looks consistent though.

**Comment by btangmu** [comment]
@macchiati the test is 227, 999 bytes (8,532 lines), making it the largest in its folder -- for this and future similar PRs, is there any limit or guideline for test size? I've added you as a reviewer, though I've already given my approval

**Comment by dyacob** [comment]
FWIW, the long list of test words comes from the "sgw" file in the [Unilex](https://github.com/unicode-org/unilex/) repo (with single letter entries removed): https://github.com/unicode-org/unilex/blob/master/data/frequency/sgw.txt

**Comment by btangmu** [comment]
@macchiati and @dyacob I went ahead and merged this -- we can revisit later with a new PR if we decide to reduce the test file size. Thanks!

**Pull request merged**
