### PR TITLE
CLDR-17582 Tweak the emoji collation/English

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17582

- This incorporates the change from the ESR for the collation order of certain marine animals
- It also makes a fix to Mx Claus (from 'claus'), an oversight in a previous PR
- And it adds back Vulcan as a keyword for 'vulcan salute', which was deemed safe.

Cf.
- https://github.com/unicode-org/unicodetools/pull/844
- https://github.com/unicode-org/unicodetools/issues/753
- https://github.com/unicode-org/cldr/blob/main/docs/dev/generate-emoji-paths.md

Updated instructions in separate PR: https://github.com/unicode-org/cldr/pull/3788

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by nedley** [comment]
LGTM

Two suggestions for "Mx Claus": you can mark this PR as resolving CLDR-17701, and preemptively fix the capitalization in your copy of emoji-test.txt, since it will get the fix the next time it is regenerated by unicodetools.

**Comment by macchiati** [comment]
PS. This is draft until I get the emoji-ordering-rules.txt file from Ned.

**Comment by macchiati** [comment]
Good suggestions

**Comment by macchiati** [comment]
Ping — I'd like to get this in the next push and the changes are small.

**Review by btangmu — APPROVED** [review]
Disclaimer: I'm not familiar with the new emoji like 🪏 or the principles for ordering the sea creatures

**Comment by macchiati** [comment]
No problem, Tom. Those come to us from the emoji WG

**Pull request merged**
