### PR TITLE
CLDR-11910 new compound units;

### PR DESCRIPTION
**Pull request by macchiati**
[CLDR-11910]

Add 'times' compound unit, to root and ST examples

[CLDR-11910]: https://unicode-org.atlassian.net/browse/CLDR-11910

### CODE REVIEW

**Comment by macchiati** [comment]
Sorry, wrong title. Trying to figure out how to revert pull request.

**Comment by srl295** [comment]
@macchiati you have two commits, one for 'CLDR-1234' and one for 'CLDR-11910'.

**Comment by macchiati** [comment]
That I know. The key is how to fix that.

Mark

**Comment by srl295** [comment]
please close this in favor of #16

**Comment by macchiati** [comment]
done
Mark

**Pull request closed without merging**
