### PR TITLE
🚧 CLDR-16947 TestUniqueness passes when re-enabled

### PR DESCRIPTION
**Pull request by srl295**
CLDR-16947

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

The test passes, but is it valuable? It did not find any collisions that weren't found by CheckDisplayCollisions.

If it does something valuable, I think it should be moved into a console check

### CODE REVIEW

**Comment by srl295** [comment]
@macchiati thoughts? My evaluation is complete, passing the ticket back to you. (You can pass it back to me if you tell me what the recommendation is!)

**Comment by macchiati** [comment]
I agree. The main reason I wanted this ticket was to verify that there wasn't anything that snuck through. So we should be good to just close this ticket.

**Comment by srl295** [comment]
> I agree. The main reason I wanted this ticket was to verify that there wasn't anything that snuck through. So we should be good to just close this ticket.

That will leave the test disabled as a log known issue.  Let's call this option "A"

Option "B" would be to delete the test, since it seems to duplicate the collision tests

Option "C" would be to reinstate the test, without the warning (which is what this PR does, though I'm not proposing this). 

I was proposing B, which were you proposing? "A" seems suboptimal if we close the ticket also.

**Comment by macchiati** [comment]
Ah, yes. I meant option B.

**Review by macchiati — CHANGES_REQUESTED** [review]
Agreed on option B, remove the test in favor of CheckDisplayCollisions

**Pull request closed without merging**
