### PR TITLE
CLDR-13382 CONTRIBUTING.md: mdlint, review comments

### PR DESCRIPTION
**Pull request by srl295**
CLDR-13382
Update to #657 with some more comments from @macchiati 

- add a 'lint' step for markdown (informative only, doesn't stop the build, yet)

### CODE REVIEW

**Comment by srl295** [comment]
I'm going to make this ready for review because it's ready for further TC input.

**Comment by srl295** [comment]
> Hooray! The files in the branch are the same across the force-push. 😃
> 
> ~ Your Friendly Jira-GitHub PR Checker Bot

Squashed into one, let's discuss in TC

**Comment by srl295** [comment]
@macchiati Didn't get to discuss this today. But, no other comments heard. Should we merge as is?

**Comment by macchiati** [comment]
> @macchiati Didn't get to discuss this today. But, no other comments heard. Should we merge as is?

Yes, even if we want to tweak further, this is better than what we have.

**Pull request merged**
