### PR TITLE
CLDR-15366 BRS v41: likelySubtags update #0

### PR DESCRIPTION
**Pull request by srl295**
- update test to be clearer (related to CLDR-15391)
- add 'less disruptive' likely subtag changes

CLDR-15366

- [ ] This PR completes the ticket.

### CODE REVIEW

**Review by pedberg-icu — APPROVED** [review]

**Comment by pedberg-icu** [comment]
This is targeted at main, can it be re-targeted at maint/maint/41?

**Comment by srl295** [comment]
Yes will work on that tomorrow ?

**Review by Potfarmr22 — APPROVED** [review]

**Review by Potfarmr22 — APPROVED** [review]
Looks good

**Comment by Potfarmr22** [comment]
Can some one authorize it

**Review by Potfarmr22 — APPROVED** [review]
Looks good

**Comment by srl295** [comment]
> This is targeted at main, can it be re-targeted at maint/maint/41?

done

**Review by pedberg-icu — APPROVED** [review]

**Pull request merged**
