### PR TITLE
CLDR-16030 v40: backport proposed latest update and other fixes

### PR DESCRIPTION
**Pull request by srl295**
CLDR-16030

Includes:

-----

CLDR-16028 doc: update Latest Proposed Update link (#2370)

(cherry picked from commit 8d5fcd8a4cdf3abbcf09d82b4b2a7be6a27a69ce)

CLDR-15104 docs: use gh-pages branch and tr-archiver (#1572)

- build into the 'gh-pages' branch instead of using Github Pages default build
- use the tr-archiver for the spec

(cherry picked from commit fa660d9f1585ff21068b4f5de9f07de4c608b943)

CLDR-15205 spec: add an anchor (anchor.js) (#1827)

- Use package anchor-js to add links to h2 and below

(cherry picked from commit 3b5d276db853bb559d1b9f2ff993f11c9c94ac16)

CLDR-15105 spec: update ToC (#1835)

(cherry picked from commit 6c7bdab0dfc9315746d70d5dd673f809da104b07)

CLDR-15206 spec: section numbers outside of anchors, table caption (#1866)

- Update all anchors starting with section numbers (1.2.3.4) so the number is outside of the anchor.

- CLDR-14611: Update all h6 (######) to have the text 'Table: ' outside of the anchor.

- Regenerate ToC

- Update archiver to move h6-followed-by-table into a <caption> inside the table, iff the h6 starts with 'Table:'

- demoted a few non-caption h6

(cherry picked from commit 97e2ac333939b62ba6f08f05086d859deef38425)

CLDR-16029 v41: backport tr-archive improvements

CLDR-15088 specs: fix mixed content, improve build (#1881)

(cherry picked from commit db15bae6b0ba6be54b50072c220e77a2dc14047f)

CLDR-15539 tr:(deps): Bump jsdom in /tools/scripts/tr-archive (#1906)

Bumps [jsdom](https://github.com/jsdom/jsdom) from 16.5.2 to 19.0.0.
- [Release notes](https://github.com/jsdom/jsdom/releases)
- [Changelog](https://github.com/jsdom/jsdom/blob/master/Changelog.md)
- [Commits](https://github.com/jsdom/jsdom/compare/16.5.2...19.0.0)

---
updated-dependencies:
- dependency-name: jsdom dependency-type: direct:production update-type: version-update:semver-major ...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 96383a3ca3603c91990c0474feda9666d80bbf5c)

CLDR-15539 tr:(deps): Bump highlight.js in /tools/scripts/tr-archive (#1903)

Bumps [highlight.js](https://github.com/highlightjs/highlight.js) from 10.7.2 to 11.5.1.
- [Release notes](https://github.com/highlightjs/highlight.js/releases)
- [Changelog](https://github.com/highlightjs/highlight.js/blob/11.5.1/CHANGES.md)
- [Commits](https://github.com/highlightjs/highlight.js/compare/10.7.2...11.5.1)

---
updated-dependencies:
- dependency-name: highlight.js dependency-type: direct:production update-type: version-update:semver-major ...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 5e8707538ea06403d7638127d538c0e8bc8c361b)

CLDR-15539 tr:(deps): Bump jsdom in /tools/scripts/tr-archive (#2150)

Bumps [jsdom](https://github.com/jsdom/jsdom) from 19.0.0 to 20.0.0.
- [Release notes](https://github.com/jsdom/jsdom/releases)
- [Changelog](https://github.com/jsdom/jsdom/blob/master/Changelog.md)
- [Commits](https://github.com/jsdom/jsdom/compare/19.0.0...20.0.0)

---
updated-dependencies:
- dependency-name: jsdom dependency-type: direct:production update-type: version-update:semver-major ...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 5a60dad2ee21be7b23a62906128e03fedb6e0171)

CLDR-15104 docs: use gh-pages branch and tr-archiver (#1572)

- build into the 'gh-pages' branch instead of using Github Pages default build
- use the tr-archiver for the spec

(cherry picked from commit fa660d9f1585ff21068b4f5de9f07de4c608b943)

CLDR-15460 build: restructure workflows (#1868)

(cherry picked from commit 85a651d96c77cc0e3e977105dedf84d0902b2ab3)

CLDR-15464 spec: fix gh-pages (#1888)

(cherry picked from commit 2048ea49a1c4b639cb85063071666570e626ee22)

CLDR-15539 gh:(deps): Bump actions/checkout from 2 to 3 (#1904)

Bumps [actions/checkout](https://github.com/actions/checkout) from 2 to 3.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v2...v3)

---
updated-dependencies:
- dependency-name: actions/checkout dependency-type: direct:production update-type: version-update:semver-major ...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 1d7c85356c5dfa3d6e7f710f24eeb1463f2967dc)

CLDR-15539 gh:(deps): Bump actions/cache from 2 to 3 (#1898)

Bumps [actions/cache](https://github.com/actions/cache) from 2 to 3.
- [Release notes](https://github.com/actions/cache/releases)
- [Changelog](https://github.com/actions/cache/blob/main/RELEASES.md)
- [Commits](https://github.com/actions/cache/compare/v2...v3)

---
updated-dependencies:
- dependency-name: actions/cache dependency-type: direct:production update-type: version-update:semver-major ...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 7ae90fc16e6cdad24bc9bb43b9980784f5a95ab1)

CLDR-15539 gh:(deps): Bump actions/setup-node from 2 to 3 (#1965)

Bumps [actions/setup-node](https://github.com/actions/setup-node) from 2 to 3.
- [Release notes](https://github.com/actions/setup-node/releases)
- [Commits](https://github.com/actions/setup-node/compare/v2...v3)

---
updated-dependencies:
- dependency-name: actions/setup-node dependency-type: direct:production update-type: version-update:semver-major ...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 45263965df60a2b786bc617023d25d2a8e3f70d9)

CLDR-15464 build: post maint branches and releases to smoketest (#2355)

(cherry picked from commit c38a4c6f9a3117c621123258d6dfd9c0583214c9) (cherry picked from commit 5cca4309c35f25975af04a03dccfd35de537d7a4)

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
I don't think fixing ansible is important on this maint branch.

**Comment by btangmu** [comment]
the pr message has "CLDR-_____" in place of "CLDR-16030"

**Comment by srl295** [comment]
It has 16030 earlier.

**Comment by btangmu** [comment]
"ImportError: cannot import name 'render_group' from 'rich.console' (/usr/local/lib/python3.8/site-packages/rich/console.py)" -- what could that mean? temporary glitch?

**Comment by srl295** [comment]
> "ImportError: cannot import name 'render_group' from 'rich.console' (/usr/local/lib/python3.8/site-packages/rich/console.py)" -- what could that mean? temporary glitch?

glitch in the ansible lint . Unrelated to current work, i'd like to merge and just ignore it in this old branch

**Review by btangmu — APPROVED** [review]

**Pull request merged**
