### PR TITLE
CLDR-14804 update Locales.txt per discussion

### PR DESCRIPTION
**Pull request by srl295**
- fix casing of some orgs
- (re-)add * to SIL, wikimedia
- fix corrupted chars in comments
- re-instate obvious participation locales
- add '*' to Apple, IBM, Microsoft, Google

CLDR-14804

- [X] This PR completes the ticket.

### CODE REVIEW

**Comment by srl295** [comment]
Does not add * to (Google, Apple. Microsoft, IBM) per CLDR-14832 but that could be piggybacked here.

**Comment by DavidLRowe** [comment]
@srl295 In line
```
SIL	;	kk	;	moderate	;
```
I believe "kk" should be "kkj". In the past SIL has contributed to kkj (Kako, Latn, CM). This was part of the same effort that collected data for jgo, mgo and nnh (three other Cameroonian languages). To my knowledge, SIL has never contributed to kk (Kazakh, Cyrl, KZ). 

Can this be corrected as part of this ticket? or does it need a separate ticket?

**Comment by nemobis** [comment]
+1, thank you. I've also commented at https://unicode-org.atlassian.net/browse/CLDR-14597?focusedCommentId=161551

**Comment by srl295** [comment]
> @srl295 In line
> 
> ```
> SIL	;	kk	;	moderate	;
> ```
> 
> I believe "kk" should be "kkj". In the past SIL has contributed to kkj (Kako, Latn, CM). This was part of the same effort that collected data for jgo, mgo and nnh (three other Cameroonian languages). To my knowledge, SIL has never contributed to kk (Kazakh, Cyrl, KZ).
> 
> Can this be corrected as part of this ticket? or does it need a separate ticket?

@DavidLRowe it certainly can be corrected here, I think the focus of _this_ ticket should be unblocking organizations.  As SIL gets an `*` SIL is not restricted after this PR.   If the _only_ change that needs to be made is kk to kkj, then that's ok, otherwise I would suggest a separate PR to update any coverage levels and locales you would like to note.

**Comment by srl295** [comment]
fixed tests. apparently some code did not expect `*`

**Comment by macchiati** [comment]
Yes, the * needs to be added to those orgs. If not on their PR then in a
follow-up.

Mark (📱)

**Comment by srl295** [comment]
> Yes, the * needs to be added to those orgs. If not on their PR then in a follow-up. Mark (📱)
> […](#)

It's done in this PR

**Review by macchiati — APPROVED** [review]

**Pull request merged**
