### PR TITLE
CLDR-17601 Fix Asia/Kuala_Lumpur metazone start/end boundaries.

### PR DESCRIPTION
**Pull request by Yqwed**
https://unicode-org.atlassian.net/browse/CLDR-17601

CLDR-17601 align metazone from/to dates with IANA data.

- [X] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by btangmu** [comment]
I added a comment in the ticket, not sure whether this PR should target the main branch (as it currently does) or the maintenance branch maint-45...

**Comment by AEApple** [comment]
> I added a comment in the ticket, not sure whether this PR should target the main branch (as it currently does) or the maintenance branch maint-45...

I thought we had agreed to 45 dot release?

**Comment by Yqwed** [comment]
Sorry, I've spent too much time working in trunk-based development. 
I changed `base` and now there are 79 commits to be made. I will create a new PR later.

**Review by pedberg-icu — APPROVED** [review]

**Comment by AEApple** [comment]
> Sorry, I've spent too much time working in trunk-based development. I changed `base` and now there are 79 commits to be made. I will create a new PR later.

Sounds like we've agreed to make the dot fixes in main and cherrypick to the maint branch.

**Pull request merged**
