### PR TITLE
CLDR-14385 XML Upload in gear menu

### PR DESCRIPTION
**Pull request by btangmu**
-Fix the UploadXML link in List Users

-Still not modernized, but works as non-SPA with .jsp

-Also hide some List Users menu items from users that lack permissions

CLDR-14385

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
I added comments in the ticket about fixing the link, which is accomplished by this PR.

This PR also hides some menu items in List Users from users without permission. Note: the back end already prohibited the items, so this change isn't urgent, but will help avoid confusion.

**Comment by btangmu** [comment]
js unit test is failing. I'll fix that...

**Comment by btangmu** [comment]
> js unit test is failing. I'll fix that...

Fixed. Needed to allow for session id being null during js unit test. Also, removed the "a=/cldr-apps/survey" part of the url when in List Users; it wasn't in the old version and it isn't needed (though for unknown reasons it's in the main menu version and seems to do no harm there).

**Review by srl295 — APPROVED** [review]
lgtm, i would mention the other ticket (about hiding items) in this PR if you can

**Comment by btangmu** [comment]
> lgtm, i would mention the other ticket (about hiding items) in this PR if you can

Do you mean https://unicode-org.atlassian.net/browse/CLDR-14791 ?

**Pull request merged**
