### PR TITLE
CLDR-16629 Account for macroregions in likely subtags

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-16629

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Can one of you approve this?

**Review by pedberg-icu — APPROVED** [review]
Changes look good, but the ticket is for 43.1 and the commit was on the main branch (CLDR decision was to make 43.1 changes first on the maint branch). I guess I will cherry-pick to maint branch (after I am back from vacation).

**Comment by macchiati** [comment]
thanks

**Comment by FrankYFTang** [comment]
sorry I didn't review the PR in time during my vacation. I do not think the change is correct. See my comment in https://github.com/unicode-org/cldr/pull/2975#issuecomment-1574117585

**Pull request merged**
