### PR TITLE
CLDR-14696 Merge branch 'maint/maint-39' into master (via branch on fork)

### PR DESCRIPTION
**Pull request by pedberg-icu**
CLDR-14696

- [x] This PR completes the ticket.

This merges the current CLDR maint/maint-39 branch into master, using the "Hard Way" procedure at
http://site.icu-project.org/repository/gitdev#TOC-Merging-from-Maint-to-Main-BRS-Task-

// Allow commits with mixed issue tags
DISABLE_JIRA_ISSUE_MATCH=true

// Allow multiple commits in the same PR
ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — APPROVED** [review]
LGTM

**Comment by srl295** [comment]
RSLGTM. 

Verified with this command, which matches the contents of this PR: 

`$ git log --reverse --oneline upstream/master..upstream/maint/maint-39`
178edd0198 CLDR-12003 updating translation (#1083)
6d8d9fec96 CLDR-14569 Improve Windows mappings for UTC (#1086)
08aa111d3c CLDR-14572 remove fr names for short en_GB/US; fix TestMissingStatus to use non-↑↑↑ value (#1099)
b9e00003ca CLDR-14461 update ICU4J libs to version of 2021-03-09 with fix for compact dec e,c; update readme (#1102)
02a697d627 (tag: release-39-beta) CLDR-14581 Change plural rule format from 2e6 to 2c6 (#1100)
024ef64a1a CLDR-14461 bump ICU4J level to the 69RC (#1121)
d5780c2ae9 CLDR-14319 remove duplicate example (#1135)
c926d5302b CLDR-14312 handle canonicalization of subdivision aliases (#1132)
3cc8a99aa1 CLDR-14330 only uppercase characters inside unicode_language_id (#1129)
45ec76b39a CLDR-14377 Clarify use of the implicit "true" (#1128)
b374c34a74 CLDR-14272 document grammatical attributes (#1136)
880846905d CLDR-14579 document changes in DTDs (#1126)
740bdfcde7 CLDR-14410 Fix wording in Unit_Identifier_Normalization (#1127)
045412422a CLDR-14320 clarify ordering of keys in extensions (#1131)
19d48cebf8 CLDR-14329 Clearly disallow duplicate variants (#1130)
c4f244f542 CLDR-14253 various unit spec improvements (#1133)
fa00b2c95b CLDR-13221 format for currency symbol at decimal point (#1137)
a4fac4e1cc CLDR-14446 Formatting updates for Markdown migration: General (#1146)
1c6b8d8f7c CLDR-14445 Minor improvements from review of first markdown version of Dates (#1145)
c8a7893f6a CLDR-14490 Refine Locale Display Name Algorithm to handle names for aliased subtags (#1148)
46ee974e8a CLDR-14244 document @alt inheritance (#1134)
98415f2595 (srl295/maint/maint-39) CLDR-14221 Add section on using delimiter data for linebreak tailoring (#1149)
523ba8d30f CLDR-14209 Add notes on considerations for territory and currency display names (#1155)
cca661b411 CLDR-14619 LDML BRS (#1147)
764fa75895 CLDR-14447 Fixing typos in MD (#1138) (#1143)
15112d595b CLDR-14619 updates to modifications section (#1162)
56f3a574ef (tag: release-39-beta2) CLDR-14253 Spec improvements: compound unit pattern algorithms (#1160)
0b674ddf77 CLDR-14461 BRS 39, update readme for final, other misc date updates (#1169)
ae70f97c48 CLDR-14619 fix html typos (#1172)
651afecf9c (tag: release-39) CLDR-14416 fix headers, dates, and status blurb for revision 63, cldr v39 (#1191)
65485cfc70 (upstream/maint/maint-39, maint/maint-39) CLDR-14649 archiver for tr35 .md files (#1190)

(Note: my comment will cause a mention in each of the PRs, which is probably a good idea)

**Review by srl295 — APPROVED** [review]
RSLGTM

**Comment by srl295** [comment]
@pedberg-icu I'm going to go ahead and land this if i get confirmation on email

**Comment by pedberg-icu** [comment]
> @pedberg-icu I'm going to go ahead and land this if i get confirmation on email

Yes, please go ahead and merge using the MERGE COMMIT procedure, thanks! (Also confirmed via e-mail)

**Comment by srl295** [comment]
I temporarily checked this button, https://github.com/unicode-org/cldr/settings <https://github.com/unicode-org/cldr/settings>



… did the merge, and then unchecked it.
-s

**Comment by srl295** [comment]
> I temporarily checked this button, https://github.com/unicode-org/cldr/settings <https://github.com/unicode-org/cldr/settings> … did the merge, and then unchecked it. -s

@pedberg-icu when I did the merge with the button above, I neglected to modify the commit message which is why it remains:

```
Merge pull request #1218 from pedberg-icu/CLDR-14696-merge-maint-39
```

Should have edited it to begin with CLDR-14696 even though it is a merge commit.

**Pull request merged**
