### PR TITLE
CLDR-14212 publish to maven on release

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14212

publish ( using version `0.0.0-SNAPSHOT-`_hash_ where _hash_ is the git hash ) all released versions to maven

### CODE REVIEW

**Comment by srl295** [comment]
This is to support UnicodeTools and other consumers of CLDR via maven.

So this works this way:
- create a release (could be an official `release-38` or an unofficial, prerelease `snapshot-2020-11-27` (the exact tag name is not used currently).
- this creates maven artifacts under https://github.com/orgs/unicode-org/packages?repo_name=cldr  such as:

```xml
<dependency>
  <groupId>org.unicode.cldr</groupId>
  <artifactId>cldr-code</artifactId>
  <version>0.0.0-SNAPSHOT-51d91227f4</version>
</dependency>
```

- as noted, the tag name is not used, but the act of creating a release (or prerelease) causes the artifact with the specific hash to be uploaded to github maven.

**Comment by btangmu** [comment]
> So this works this way:
> 
>     * create a release (could be an official `release-38` or an unofficial, prerelease `snapshot-2020-11-27` (the exact tag name is not used currently).

How does one actually create a release? Just by pressing a button in the Actions tab, or are other steps needed?

**Review by btangmu — APPROVED** [review]

**Comment by srl295** [comment]
> > So this works this way:
> > ```
> > * create a release (could be an official `release-38` or an unofficial, prerelease `snapshot-2020-11-27` (the exact tag name is not used currently).
> > ```
> 
> How does one actually create a release? Just by pressing a button in the Actions tab, or are other steps needed?

under 'releases' then 'new':  https://github.com/unicode-org/cldr/releases/new

**Comment by srl295** [comment]
> > > So this works this way:
> > > ```
> > > * create a release (could be an official `release-38` or an unofficial, prerelease `snapshot-2020-11-27` (the exact tag name is not used currently).
> > > ```
> > 
> > 
> > How does one actually create a release? Just by pressing a button in the Actions tab, or are other steps needed?
> 
> under 'releases' then 'new': https://github.com/unicode-org/cldr/releases/new

all releases create a tag, not all tags are releases.  I would add that the release may be a 'prerelease' which would be correct for a release that isn't a real production release (38, 38.1, 39… )

**Comment by srl295** [comment]
@hagbard you might be interested in this from the tooling perspective.

**Comment by btangmu** [comment]
> > under 'releases' then 'new': https://github.com/unicode-org/cldr/releases/new

I see! And "Releases" is part of the right sidebar at https://github.com/unicode-org/cldr
Thanks!

**Pull request merged**
