### PR TITLE
CLDR-14854 Update CLDR with latest Myanmar converters from github Google Myanmar Tools

### PR DESCRIPTION
**Pull request by sven-oly**
CLDR-14854

- [x] This PR completes the ticket.

### CODE REVIEW

**Review by sffc — DISMISSED** [review]
LGTM but wait for approval from Alolita (see email)

**Comment by sven-oly** [comment]
I see a build failure with cldr-mvn. However, I do not understand what is actually failing nor why this CL is causing the problem. Any ideas?

**Comment by sffc** [comment]
According to the logs on GitHub Actions, the error is

```
    TestUnicodeToZawgyi111107
Error:  (TestTransforms.java:681)  Error: : u2 to z2: expected "တကယ္ဆို အႃငွိုးေတြမဲ့ေသာလမ္းေသာလမ္းမွာ တိႈျပန္ဆံုၾကတဲ့အခါ ", got "တကယ္ဆို အၿငႇိဳးေတြမဲ့ေသာလမ္းေသာလမ္းမွာ တိႈျပန္ဆံုၾကတဲ့အခါ "

Error:  (TestTransforms.java:686)  Error: : u3 to z3: expected "ျပန္လမ္းမဲ့ကၽြန္းအပိုင္း၄", got "ျပန္လမ္းမဲ့ကြၽန္းအပိုင္း၄"

```

Maybe you need to update the test expectation?

**Comment by sffc** [comment]
Ping @sven-oly @alolita

**Comment by sven-oly** [comment]
I've just updated the tests, hoping that the tests will now pass.

**Review by sffc — APPROVED** [review]

**Pull request merged**
