### PR TITLE
CLDR-11789: Add Kazakh (Arabic) locale

### PR DESCRIPTION
**Pull request by MuratKaribai**
Hello, is it possible to add a Kazakh language locale (Arabic script) to CLDR?

Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-11789
- [ ] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by srl295** [comment]
You need to open the PR with your own data. This is invalid.

**Comment by MuratKaribai** [comment]
> You need to open the PR with your own data. This is invalid.

https://github.com/unicode-org/cldr/pull/542

**Comment by macchiati** [comment]
This is a broken PR; changing 300 files in peculiar ways.

**Comment by MuratKaribai** [comment]
> This is a broken PR; changing 300 files in peculiar ways.
Can you send me a guide on how to do PR correctly so that there are no 300 unnecessary files

**Comment by macchiati** [comment]
Please follow http://cldr.unicode.org/index/bug-reports#New_Locales

**Pull request closed without merging**
