### PR TITLE
CLDR-17141 kbd: keep transform=no but document it

### PR DESCRIPTION
**Pull request by srl295**
CLDR-17141

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by mcdurdin** [comment]
I'd prefer to drop transform=no and simplify the mental model for keyboard authors. transform=no may _seem_ simpler, but the caveats mean they have to have some grasp of transforms anyway, and then it just becomes an additional layer to remember.

**Comment by srl295** [comment]
@Jahorton fyi

**Comment by srl295** [comment]
@miloush  thoughts here? @mcdurdin requesting to drop (meaning i can just remove this PR).   

I agree that the complexity and limitations of `transform=no` make it very limited use, especially this:

> the caveats mean they have to have some grasp of transforms anyway

As "syntactic sugar" it may not add a lot. Probably better to work on documentation, and tooling (including debugging and test environments, test cases, etc) for transforms.

**Comment by srl295** [comment]
@miloush Are you OK if we close this one (that is, drop `transform=no`) and merge #3330 ?

**Review by miloush — APPROVED** [review]

**Comment by miloush** [comment]
Oh sorry I meant yes, feel free to drop.

**Comment by srl295** [comment]
@miloush sorry, i merged the wrong PR 😆

**Pull request merged**
