### PR TITLE
CLDR-16086 Headers are hidden in new web site color scheme

### PR DESCRIPTION
**Pull request by btangmu**
-Fix in bytype-index.css

CLDR-16086

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
This duplicates the mysteriously stuck https://github.com/unicode-org/cldr/pull/2452

**Review by macchiati — APPROVED** [review]

**Review by pedberg-icu — COMMENTED** [review]
LGTM, same changes as the stuck PR>

**Comment by pedberg-icu** [comment]
Oh, this targeted main. Was supposed to target maint/maint-42.

**Comment by btangmu** [comment]
> Oh, this targeted main. Was supposed to target maint/maint-42.

sorry I didn't notice that detail -- I'm out of office for tonight but could repeat with that change tomorrow if that's soon enough

**Pull request merged**
