### PR TITLE
CLDR-15291 check in additional fixes

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-15291

- [ ] This PR completes the ticket.

### CODE REVIEW

**Review by AEApple — CHANGES_REQUESTED** [review]
Do we not need the Yoruba fixes?

**Comment by AEApple** [comment]
> 

Confirmed that we should not make the Yoruba changes since the proposed changes are not clear enough.

**Review by AEApple — DISMISSED** [review]

**Comment by macchiati** [comment]
Not sure how that happened, but the actual changes are fine. I'll just squash, but will need a rereview.

**Review by AEApple — APPROVED** [review]

**Comment by AEApple** [comment]
> Not sure how that happened, but the actual changes are fine. I'll just squash, but will need a rereview.

Yes, there was only the 1 file with the expected change.

**Pull request merged**
