### PR TITLE
CLDR-14057 Survey tool CLDR_PHASE=FINAL_TESTING allows vetters to vote; preliminary

### PR DESCRIPTION
**Pull request by btangmu**
-Clean up formatting of SurveyMain.Phase

-Delete some dead code

-Change some items from public to private

-Comments

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14057
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
This PR is just preliminary clean-up. So far I'm unable to repro the alleged bug...

**Review by macchiati — COMMENTED** [review]
I couldn't figure out which line(s) actually fix the bug.

**Comment by srl295** [comment]
> This PR is just preliminary clean-up. So far I'm unable to repro the alleged bug...

Might be better not to repeat the bug title then; just say cleanup of ...

**Comment by btangmu** [comment]
I've renamed this PR "preliminary clean-up related to CLDR_PHASE=FINAL_TESTING"

**Comment by btangmu** [comment]
See https://github.com/unicode-org/cldr/pull/866

**Pull request closed without merging**
