### PR TITLE
CLDR-16577 SBRS v44  merge maint/maint/43 branch back to main

### PR DESCRIPTION
**Pull request by pedberg-icu**
CLDR-16577

- [x] This PR completes the ticket.

ALLOW_MANY_COMMITS=true
DISABLE_JIRA_ISSUE_MATCH=true

**_Note: This needs to be merged using a MERGE COMMIT (requires temporarily enabling this in project setting), not the normal SQUASH AND MERGE._**

Note (mainly for Steven): For three of the files that showed as merge conflicts, all of the changes that had been made on the `maint/maint-43` branch were just cherry-picks of some of the changes in these files on the `main` branch. So for these three I just used the version from the `main` branch:
```
tools/cldr-apps/js/package-lock.json
tools/cldr-apps/js/package.json
tools/cldr-apps/js/webpack.config.js
```

### CODE REVIEW

**Review by srl295 — DISMISSED** [review]

**Comment by srl295** [comment]
thanks…

**Comment by pedberg-icu** [comment]
@srl295 I am getting a "commit message fails validation" for the final commit bb9bdb3, I cannot figure out why

**Comment by srl295** [comment]
Space in the title ? Bad commit message: “ CLDR-16577 merge maint/maint-43 changes to main”

**Comment by pedberg-icu** [comment]
> Space in the title ? Bad commit message: “ [CLDR-16577](https://unicode-org.atlassian.net/browse/CLDR-16577) merge maint/maint-43 changes to main”

Thanks much! I missed that, though I was looking for extraneous chars.

**Review by macchiati — APPROVED** [review]

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
> > Space in the title ? Bad commit message: “ [CLDR-16577](https://unicode-org.atlassian.net/browse/CLDR-16577) merge maint/maint-43 changes to main”
> 
> Thanks much! I missed that, though I was looking for extraneous chars.

I have a ticket to improve the err message, it should tell you what the problem is for this common case

**Pull request merged**
