### PR TITLE
CLDR-14561 Casing for Occitan

### PR DESCRIPTION
**Pull request by ensag-dev**
Just to have the proper casing for Occitan

### CODE REVIEW

**Comment by pedberg-icu** [comment]
Please fix the commit message to begin with "CLDR-14561 ", thanks.

**Comment by ensag-dev** [comment]
> 
> 
> Please fix the commit message to begin with "[CLDR-14561](https://unicode-org.atlassian.net/browse/CLDR-14561) ", thanks.

Hello @pedberg-icu I hope it's okay now.

**Comment by petar8903** [comment]
> Just to have the proper casing for Occitan

5€ bonus for winlive247 profile: petross

**Comment by petar8903** [comment]
Tenks

**Review by pedberg-icu — APPROVED** [review]
Looks good and thanks for fixing the commit message!

**Pull request merged**
