### PR TITLE
CLDR-15706 Add Hinglish variant

### PR DESCRIPTION
**Pull request by AEApple**
CLDR-15706 Add Hinglish variant

- Add Hinglish variant
- Make visible in to all languages

- [x] This PR completes the ticket.

### CODE REVIEW

**Comment by btangmu** [comment]
Test description:
```
    public void TestCoverageCompleteness() {
        /**
         * Check that English paths are, except for known cases, at least modern coverage.
         * We filter out the things we know about and have determined are OK to be in comprehensive.
         * If we add a path that doesn't get its coverage set, this test should complain about it.
         */
```

**Comment by btangmu** [comment]
I went to https://st.unicode.org/cldr-apps/v#lookup///
and entered //ldml/localeDisplayNames/languages/language[@type="hi_Latn"]
and it says "❌ Not Found"

**Comment by btangmu** [comment]
@AEApple in TestCoverageLevel.java right below this line
```
        for (String path : english.fullIterable()) {
```

if this were inserted

```
            if (path.equals("//ldml/localeDisplayNames/languages/language[@type=\"hi_Latn\"]") ||
                    path.equals("//ldml/localeDisplayNames/languages/language[@type="\hi_Latn\"][@alt=\"variant\"]")) {
                continue;
            }
```

then I think the test would be skipped for those two paths

I'm not familiar with this part of the code though, and I'm not it's the best workaround -- at least for a draft pr there's no harm in trying it

**Comment by AEApple** [comment]
Okay, thank you!

Do you know if I need to include the standard name for hi-Latn in order to add an alt? I had added it since I didn't see any languages with composed names which have alts currently.

**Review by macchiati — APPROVED** [review]

**Pull request merged**
