### PR TITLE
CLDR-13091 Identify fields changed between 35.0 and trunk

### PR DESCRIPTION
**Pull request by macchiati**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13091
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by btangmu** [comment]
Does getArchiveDirectory access the same "35" directory (/home/surveytool/tomcat/cldr/35) as getOldFile? If so, there may be a conflict with the plan: _remove “last release data” from server, so will fail instead of giving wrong answer_.

**Comment by macchiati** [comment]
No, that is completely separate. (The archive files are local to our
machines; there is a Sites page that says how to set it up, downloading the
zip files.)

Mark

**Comment by btangmu** [comment]
> No, that is completely separate. (The archive files are local to our machines; there is a Sites page that says how to set it up, downloading the zip files.) Mark

In that case, it might be worth comparing the archive for 35 with /home/surveytool/tomcat/cldr/35 to make sure they're identical. I believe /home/surveytool/tomcat/cldr/35 is what ST has been using to determine last-release when importing old votes.

**Comment by btangmu** [comment]
I downloaded the folder /home/surveytool/tomcat/cldr/35 with rsync, and compared it with the unzipped contents of http://unicode.org/Public/cldr/35/cldr-common-35.0.zip. They're identical other than Revision numbers (as in <version number="$Revision: 14800 $"/>), readme/license files, and the seed folder which isn't in the zip.

I also compared with cldr-common-35.1.zip and there are differences. So the production server has version 35, NOT 35.1, in its "35" folder. (There is no "35.1" folder on production.) Maybe that explains some problems.
http://unicode.org/Public/cldr/35/cldr-common-35.0.zip

**Comment by macchiati** [comment]
You'd earlier found that the server had 35.0, so your compare is verifying
that. It would have been better had the server had 35.1. But at this point
it is moot, since we are no longer going to use the "lastRelease" data on
the server at all; then the problem goes away completely.

Mark

**Comment by btangmu** [comment]
> You'd earlier found that the server had 35.0, so your compare is verifying that. It would have been better had the server had 35.1. But at this point it is moot, since we are no longer going to use the "lastRelease" data on the server at all; then the problem goes away completely. Mark

Right. I just wanted to be sure the production server really had the files from 35.0 in its "35" folder. This confirms your list of changed paths should be correct.

**Comment by macchiati** [comment]
Got it. we're all on the same page.

{phone}

**Pull request merged**
