### PR TITLE
CLDR-15503 Update TR35 for CLDR 41

### PR DESCRIPTION
**Pull request by rickmcgowan**
CLDR-15503

- [ ] This PR completes the ticket.

### CODE REVIEW

**Review by macchiati — CHANGES_REQUESTED** [review]
The first line of tr35 still says "Proposed". 

NOTE: You can hide lines with  in case you want the alternate Status values right in the document. Up to you, and not necessary to change for v41.

**Comment by srl295** [comment]
@rickmcgowan I renamed the PR but i can't fix the commit message from here.  The commit message's first line needs to read, exactly:  `CLDR-15503 Update TR35 for CLDR 41`

(it has lowercase cldr and an extra hyphen before Update)

**Comment by srl295** [comment]
@rickmcgowan if you use the 'squash branch' feature at https://us-central1-dev-infra-273822.cloudfunctions.net/unicode-github-bot/info/unicode-org/cldr/1861 i think it will fix the commit message for you

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
> [](https://github.com/srl295)@[srl295](https://github.com/srl295) srl295 locked and limited conversation to collaborators [5 days ago](https://github.com/unicode-org/cldr/pull/1861#event-6338992986) 

Huh?

**Review by pedberg-icu — APPROVED** [review]

**Review by macchiati — APPROVED** [review]

**Pull request merged**
