### PR TITLE
CLDR-13283 English name of "zafs" should be "Free State"

### PR DESCRIPTION
**Pull request by tayre**
The South African province [Free State](https://en.wikipedia.org/wiki/Free_State_(province)), is listed in `common/subdivisions/en.xml` as `Free` instead of `Free State`. 

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13283
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Comment by srl295** [comment]
@tayre please file a bug at https://unicode-org.atlassian.net under the CLDR project — you can reference this PR.

**Comment by tayre** [comment]
It looks like this was fixed [here](https://github.com/unicode-org/cldr/pull/375/files#diff-abb388a23e7b0df3f56b53430573e019R5574) as part of https://github.com/unicode-org/cldr/pull/375/.

**Comment by macchiati** [comment]
Yes, so we'll be closing this.

Mark

**Comment by srl295** [comment]
OK, closing.

**Pull request closed without merging**
