### PR TITLE
CLDR-14801 v40 BRS §A40: DTD for Unicode 14.0.0

### PR DESCRIPTION
**Pull request by srl295**
CLDR-14801 

- [ ] This PR completes the ticket.

### CODE REVIEW

**Comment by markusicu** [comment]
Interesting, I wasn't aware of this unicodeVersion. Why does CLDR have it?

The Unicode update comes in stages: script metadata, likely subtags, collation root data, Chinese transliteration, ICU with Unicode.next properties, further updates towards final data. Of course, all should feed into the same CLDR release. When should this unicodeVersion be updated? Does it matter?

Should there be a unit test that checks that this Unicode version number is the same as some other, e.g., the one from ICU?

**Comment by srl295** [comment]
> Interesting, I wasn't aware of this unicodeVersion. Why does CLDR have it?

The spec says:

>> _The `unicodeVersion` attribute defines the version of the Unicode standard that is used to interpret data. Specifically, some data elements such as exemplar characters are expressed in terms of UnicodeSets. Since UnicodeSets can be expressed in terms of Unicode properties, their meaning depend on the Unicode version from which property values are derived._

So I think the point is for consumers to check their own Unicode Version to make sure that `[:Arab:]` or whatever has the correct meaning.

> The Unicode update comes in stages: script metadata, likely subtags, collation root data, Chinese transliteration, ICU with Unicode.next properties, further updates towards final data. Of course, all should feed into the same CLDR release.

Right… 

> When should this unicodeVersion be updated? Does it matter?

Per process, it happens now :) 

> Should there be a unit test that checks that this Unicode version number is the same as some other, e.g., the one from ICU?

Imagine that. Yes, there probably should be a test, I'll file an issue for this. => https://unicode-org.atlassian.net/browse/CLDR-15004

**Comment by srl295** [comment]
@markusicu please approve the PR if i got it right :)

**Review by markusicu — APPROVED** [review]
lgtm

**Review by macchiati — APPROVED** [review]

**Pull request merged**
