### PR TITLE
CLDR-13607 Move "New CLDR Developer" documentation into the git repository

### PR DESCRIPTION
**Pull request by hugovdm**
Status: stalled. f2f suggested Sites-to-Markdown migration can wait until the ICU project is finishe with theirs.

##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13607
- [X] Updated PR title and link in previous line to include Issue number

I'm not sure how to file a new CLDR ticket yet, I'm getting this error: "The Jira server could not be contacted. This may be a temporary glitch or the server may be down." - I don't want to go work for Atlassian to improve their Site Reliability Engineering.

### CODE REVIEW

**Comment by hugovdm** [comment]
Mark: please also confirm that the documentation from cldr.unicode.org is appropriately licensed for inclusion in the git repository, given that it's governed by the CLA?

**Comment by srl295** [comment]
generally a good idea, I'd probably go with Markdown rather than HTML so that it's browsable directly from github.

**Comment by macchiati** [comment]
Need to research tools to map to Markdown. We can paste the Sites page into
Word or Docs, if we have a tool that goes from there to Markdown. Or is
there another tool we can use?

Mark

**Comment by hugovdm** [comment]
Does anyone know how to render Markdown in the way that github does, without having to push to github first (to view it on github)?

The reasons I got from others for preferring HTML is that Markdown is inevitably limited, and mixing Markdown and HTML gets really messy. I'd rather not end up trying to improve Markdown as part of my CLDR work. We already have Internationalisation people working on improving ECMAScript and HTML, so there'd at least be people to pass feature requests on to.

**Comment by hugovdm** [comment]
The other thing I should figure out, which might unblock this Pull Request but I don't think should be part of this, is how to set up https://pages.github.com/ to view branches in my own git repository.

**Comment by srl295** [comment]
> Does anyone know how to render Markdown in the way that github does, without having to push to github first (to view it on github)?

I use VSCode's renderer as I type (side by side preview), I think there are other editors with similar.

you can use `npx marked -o README.html README.md`( https://github.com/markedjs/marked )

> The reasons I got from others for preferring HTML is that Markdown is inevitably limited, and mixing Markdown and HTML gets really messy. I'd rather not end up trying to improve Markdown as part of my CLDR work. We already have Internationalisation people working on improving ECMAScript and HTML, so there'd at least be people to pass feature requests on to.

@thaths is spearheading ICU's userguide-to-markdown move, https://github.com/unicode-org/icu/pull/919 - Markdown is limited (even GFM), but for this sort of docs it should work.

> Mark: please also confirm that the documentation from cldr.unicode.org is appropriately licensed for inclusion in the git repository, given that it's governed by the CLA?

cldr.unicode.org has the same license.

> The other thing I should figure out, which might unblock this Pull Request but I don't think should be part of this, is how to set up https://pages.github.com/ to view branches in my own git repository.

check the settings on your repository.  

But this shows why Markdown might be  preferred for the cultural reasons you mentioned, it's more readable (as text) right from your favorite editor, without needing a browser or preview, unlike HTML.

**Comment by sffc** [comment]
My favorite editor-agnostic way to preview markdown:

```
$ pip3 install grip
$ export PATH=~/.local/bin:$PATH
$ grip foo.md
```

**Comment by hugovdm** [comment]
I've changed this pull request from HTML to Markdown.

I think a gradual page-by-page migration is perhaps going to be too messy. Maybe we need to do at least the whole cldr.unicode.org/development/... tree at the same time?

**Comment by sffc** [comment]
> I think a gradual page-by-page migration is perhaps going to be too messy. Maybe we need to do at least the whole cldr.unicode.org/development/... tree at the same time?

@thaths is the one to talk to about that.

**Comment by hugovdm** [comment]
I see the ICU Documentation migration effort (userguide-migration branch) started on Aug 21, 2019. Having a migration like this sit around so long makes it even more painful to update the docs.

I think:
- we should try to do a fairly focused sprint if/when we migrate CLDR docs,
- I should perhaps get involved in the ICU migration effort first and see how that works. Gain experience.

**Comment by hugovdm** [comment]
Closing - I think it should be a broader, more concerted effort to do a coherent batch of docs (if not all) in parallel.

**Comment by srl295** [comment]
> I see the ICU Documentation migration effort (userguide-migration branch) started on Aug 21, 2019. Having a migration like this sit around so long makes it even more painful to update the docs.

For what it's worth, updating the docs is already so painful, that this effort is actually an improvement.  I just merged a PR to that migration effort branch.  :+1: to helping with the ICU docs first.

**Comment by sffc** [comment]
I disagree with closing this PR, because an incremental improvement is better than no improvement.

**Comment by srl295** [comment]
@hugovdm could we reopen and just merge this one file? It _is_ an improvement.

**Comment by hugovdm** [comment]
I have reopened this, as requested by @srl295. I will then feel encouraged to push for further improvements.

I'd be happy to be a significant contributor behind any large-scale move to Markdown, but we need to first figure out our procedures? Whether this would be good for the CLDR repository?

What I think is important to decide: if every Pull Request needs to be assocatied with a CLDR ticket, small fixes to documentation might effectively be discouraged. If we keep the ticket requirement, could it make sense to just have a catch-all ticket for small doc fixes, to reduce the amount of overhead? Maybe we want appropriately labelled git commit messages to make doc-only tweaks obvious?

(I do very much like the idea of being able to update documentation in the same PR as code.)

**Comment by srl295** [comment]
would you be willing/interested to discuss this in CLDR-TC tomorrow? ( cc @sffc/@macchiati )

**Comment by hugovdm** [comment]
Yes, I'd like to get involved. What's the proper procedure for me to get invited to the meeting?
Thanks!

**Comment by macchiati** [comment]
Before doing work on PRs, we need to get agreement on the ticket in the committee.

I'm in favor of moving to Markdown, if we can develop a plan for how that would work. And it is sizable: we have over 300 pages on Sites. Now, some of them are obsolete, and need not be converted, but that takes work to decide that.

Here is a list from using the Sites tools:
https://docs.google.com/document/d/18Bm9o9hWN-Hy1ROGELp3SkwS6nbewZBHlQjJXHLMbHQ/edit
(it loses formatting, so you don't see the tree structure, but gives a sense of the magnitude.)

**Comment by macchiati** [comment]
Closing this for now, pending decision to move to Markdown.

**Pull request closed without merging**
