### PR TITLE
CLDR-16816 Apple should cover modern for mi

### PR DESCRIPTION
**Pull request by stenshamn**
CLDR-16816

- [X] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by AEApple — DISMISSED** [review]

**Review by srl295 — DISMISSED** [review]
Change LGTM, but SMH on the err

> _Error:  (TestCLDRLocaleCoverage.java:476)  Error: : cldr level = max for mi (Māori): expected org.unicode.cldr.util.Level<basic>, got org.unicode.cldr.util.Level<modern>_

Too high, Māori! Reduce it!

**Comment by AEApple** [comment]
> Error: (TestCLDRLocaleCoverage.java:476) Error: : cldr level = max for mi (Māori): expected org.unicode.cldr.util.Level, got org.unicode.cldr.util.Level

Does that mean the coverage level in the CLDR org also needs to be updated?

**Comment by srl295** [comment]
Be less cryptic anyone? 

I THINK it's complaining about this line:

```
Cldr  ; mi  ; basic
```

Something like:  "the `Cldr` line is the maximum of `apple`, `google`, `microsoft`, and  `special`" (yes the code is that specific)


Probably changing Cldr to `modern` also could fix it

Please file a ticket for the error message, it should explain what it's looking for and what to change.

**Comment by stenshamn** [comment]
Do I need to change the `Cldr` level too or are we OK?

**Comment by AEApple** [comment]
That's super cryptic. Could we update the error message if that's what it turns out to be?

**Comment by srl295** [comment]
> Do I need to change the `Cldr` level too or are we OK?

needs change

**Review by AEApple — APPROVED** [review]

**Comment by stenshamn** [comment]
Filed https://unicode-org.atlassian.net/browse/CLDR-16817 for the error message.

**Pull request merged**
