### PR TITLE
CLDR-15821 site: add Analytics to site

### PR DESCRIPTION
**Pull request by srl295**
CLDR-15821

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
I don't see a change in the site yet

**Comment by srl295** [comment]
> I don't see a change in the site yet

It's there _ https://cldr.unicode.org

image

**Comment by srl295** [comment]
I'm seeing analytics data come in [here](https://analytics.google.com/analytics/web/#/p353755487/realtime/pages?params=_u..nav%3Dmaui)

**Comment by macchiati** [comment]
Ah, I was looking at the bottom, where I think it used to be. Thanks!

**Pull request merged**
