### PR TITLE
CLDR-16531 BRS: GenerateValidityXml

### PR DESCRIPTION
**Pull request by srl295**
- Zanb moved to special

CLDR-16531

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by btangmu** [comment]
testLanguageTagParserIsValid
Error:  (TestLocale.java:921)  Error: : und_Zanb: expected "", got "Disallowed script=Zanb, status=special"

Error:  (TestLocale.java:927)  Error: : cmg_Zanb_MN: expected "", got "Disallowed script=Zanb, status=special"

**Comment by srl295** [comment]
> ```
>  testLanguageTagParserIsValid
> ```
> 
> 
>     
>   
> 
> Error:  (TestLocale.java:921)  Error: : und_Zanb: expected "", got "Disallowed script=Zanb, status=special"
> 
> 
> Error:  (TestLocale.java:927)  Error: : cmg_Zanb_MN: expected "", got "Disallowed script=Zanb, status=special"

I saw that, I'm not sure why validity changed the status of `Zanb`

**Comment by markusicu** [comment]
> I'm not sure why validity changed the status of `Zanb`, hoping @markusicu or @macchiati might know

I don't know what changed.
Zanabazar_Square was added in Unicode 10. It is one of many historic scripts with ID Usage=Exclusion but doesn't seem to fit in with the short list of "special" scripts in script.xml.
Script_Metadata.csv hasn't changed since 2022-jan-04.

I suggest some live debugging of the script.xml generator to see why Zanb ends up in "special" now, and looking for a strategic place to prevent that from happening.

**Review by macchiati — CHANGES_REQUESTED** [review]
There is a problem in the tooling. Zanb is correct as regular, *not* special. So we can't commit this file. Since that is the only change I recommend we file a ticket to fix, and close this PR

**Comment by srl295** [comment]
@macchiati  https://github.com/unicode-org/cldr/commit/c500a2c734258867d70441c2bb6ad6523aa25855 explicitly added `Zanb` to special… by you!

**Pull request closed without merging**
