### PR TITLE
CLDR-17349 One-off import of emoji search keywords

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-17349

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Looks like some small errors:

illegal character: common/annotations/ur.xml#L1Error: Bidi markup can only include LRM RLM ALM, not paired characters such as FSI PDI
--
build: tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java#L927(TestTransforms.java:927) Error: Transliterator for Arab missing 2: [ٰؑ]=[\u0611\u0670]

[illegal character: common/annotations/ur.xml#L1](https://github.com/unicode-org/cldr/pull/3689/files#annotation_21336087811)
Error: Bidi markup can only include LRM RLM ALM, not paired characters such as FSI PDI
[check](https://github.com/unicode-org/cldr/actions/runs/8996850989/job/24713964823#step:7:2046)


[build: tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java#L927](https://github.com/unicode-org/cldr/pull/3689/files#annotation_21336314797)
(TestTransforms.java:927) Error: Transliterator for Arab missing 2: [ٰؑ]=[\u0611\u0670]

**Comment by macchiati** [comment]
I think we should go ahead and merge this. We can tweak thereafter, before Submission starts.

**Review by srl295 — APPROVED** [review]
spot check lgtm

**Review by stenshamn — APPROVED** [review]
I spot-checked the linguistic changes in a few locales and overall it looks good. Did not check the code changes since I can't really read code...

**Pull request merged**
