### PR TITLE
CLDR-17830 BRS Alpha release page 2

### PR DESCRIPTION
**Pull request by macchiati**
Small updates from TC meeting.

CLDR-17830

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by AEApple — DISMISSED** [review]

**Comment by macchiati** [comment]
Hi, I'd like to get these changes merged in, and then put it out to the TC for further refinements. Could you take a look?

**Review by srl295 — APPROVED** [review]
LGTM (will fixup syntax errs later)

**Review by AEApple — APPROVED** [review]
LGTM

I think we should still do another PR later and add the locale codes for all the locales which have increased coverage. Happy to put that in after this one merges if you'd like?

**Comment by srl295** [comment]
Site issues cleared up in #4020

**Comment by macchiati** [comment]
> LGTM
> 
> I think we should still do another PR later and add the locale codes for all the locales which have increased coverage. Happy to put that in after this one merges if you'd like?

Yes, that's be great!

**Pull request merged**
