### PR TITLE
CLDR-16956 Updating the charts refreshed the coverage levels.

### PR DESCRIPTION
**Pull request by macchiati**
CLDR-16956

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by macchiati** [comment]
Review is mostly pro forma. The downgrade of Breton was a surprise, however, because I don't think we added anything at modern coverage.

**Comment by macchiati** [comment]
I meant: added any paths at moderate coverage.

**Review by srl295 — APPROVED** [review]

**Comment by srl295** [comment]
> Review is mostly pro forma. The downgrade of Breton was a surprise, however, because I don't think we added anything at modern coverage.

that is surprising, and curious why it changed now.

Oh— actually, thoughts:

- sr_Latn etc is due to algorithmic. should update BRS to regen this chart when algorithmic is turned.
- Sierra Leone currency?  
- Remember, that we've been having to add new languages (vmw, etc) to coverage80 once they "make basic".  perhaps that's causing some of these downgrades at this juncture.

**Comment by srl295** [comment]
if it is the language stuff, then we should have some mechanism so that the coverage only changes "next time"

**Comment by srl295** [comment]
@macchiati here's what's missing from breton at modern:

image

**Comment by srl295** [comment]
SLE is going to bite a lot of locales because it was in _comprehensive_ until after close of surveytool.

**Comment by macchiati** [comment]
We had talked about copying the values, but there wasn't a ticket to do so. I filed one at https://unicode-org.atlassian.net/browse/CLDR-17038

Because of shift in dates we should have time to get this in.

**Pull request merged**
