### PR TITLE
CLDR-16835 fix phase check for adding items

### PR DESCRIPTION
**Pull request by srl295**
- adding items was using the overall phase instead of the specific phase

CLDR-16835

- [ ] This PR completes the ticket.

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Review by AEApple — APPROVED** [review]

**Review by btangmu — DISMISSED** [review]

**Comment by macchiati** [comment]
Let's get this pushed this morning.

**Comment by btangmu** [comment]
Error:    TestSTFactory.TestVotePerf:470->runDataDrivenTest:486 Unexpected exception: org.unicode.cldr.web.SurveyException: Status action is forbidden: FORBID_UNLESS_DATA_SUBMISSION

**Comment by macchiati** [comment]
Once it works, of course.

**Comment by btangmu** [comment]
// Allow items if submission
            if (this == Phase.SUBMISSION || isUnitTest()) {
                return StatusAction.ALLOW;
            }

surprising if isUnitTest() returns false in this context?

**Comment by srl295** [comment]
working on it

**Comment by btangmu** [comment]
org.unicode.cldr.web.SurveyException: Status action is forbidden: FORBID_UNLESS_DATA_SUBMISSION
	at org.unicode.cldr.web.api.VoteAPIHelper.getHandleVoteResponse(VoteAPIHelper.java:521)
	at org.unicode.cldr.web.DataDrivenSTTestHandler.handleElementApivote(DataDrivenSTTestHandler.java:468)
	at org.unicode.cldr.web.DataDrivenSTTestHandler.handlePathValue(DataDrivenSTTestHandler.java:83)
	at org.unicode.cldr.util.XMLFileReader$MyContentHandler.endElement(XMLFileReader.java:439)
...
...
	at org.unicode.cldr.util.XMLFileReader.read(XMLFileReader.java:147)
	at org.unicode.cldr.web.TestSTFactory.runDataDrivenTest(TestSTFactory.java:486)
	at org.unicode.cldr.web.TestSTFactory.TestVotePerf(TestSTFactory.java:470)

**Comment by srl295** [comment]
Took some digging but PTAL

**Comment by srl295** [comment]
Could I get someone else to merge/drive this once it passes and is reviewed? Have to jump off for some time.

**Review by macchiati — APPROVED** [review]

**Review by Koh-8888 — COMMENTED** [review]
Thanks

**Pull request merged**
